import './admin.js?v=40.0.0';
import './admin-courses-v32.js?v=40.0.0';
import {rpc,toast} from './core.js?v=40.0.0';

const passwordKey='uon_admin_password';
const getPassword=()=>sessionStorage.getItem(passwordKey)||'';
const reload=()=>location.reload();

document.querySelectorAll('.admin-section.active').forEach(section=>section.classList.remove('active'));
document.querySelector('#sec-overview')?.classList.add('active');

document.querySelector('#logout')?.addEventListener('click',()=>{sessionStorage.removeItem(passwordKey);sessionStorage.removeItem('uon_admin')},true);
if(sessionStorage.getItem('uon_admin')==='1'&&!getPassword()){sessionStorage.removeItem('uon_admin');location.reload()}
async function requirePassword(){const password=getPassword();if(!password)throw new Error('انتهت جلسة الإدارة، سجّل الدخول مرة ثانية');return password}
async function run(button,task,success,{refresh=true}={}){if(button)button.disabled=true;try{await task();toast(success);if(refresh)setTimeout(reload,250)}catch(error){toast(error.message||'تعذر تنفيذ العملية',true)}finally{if(button)button.disabled=false}}
function formPayload(form){return Object.fromEntries(new FormData(form).entries())}

document.addEventListener('click',event=>{const button=event.target.closest('#saveSite');if(!button)return;event.preventDefault();event.stopImmediatePropagation();run(button,async()=>rpc('uon_admin_save_site_settings',{p_password:await requirePassword(),p_settings:{maintenance_enabled:document.querySelector('#maintenance')?.checked||false,maintenance_message:document.querySelector('#maintenanceMessage')?.value||'',maintenance_until:document.querySelector('#maintenanceUntil')?.value||null,whatsapp_channel_url:document.querySelector('#whatsappUrl')?.value||'',instagram_url:document.querySelector('#instagramUrl')?.value||''}}),'تم حفظ إعدادات الموقع بأمان')},true);
document.addEventListener('change',event=>{const select=event.target;if(!(select instanceof HTMLSelectElement))return;if(select.matches('[data-feature]')){event.stopImmediatePropagation();run(select,async()=>rpc('uon_admin_set_feature',{p_password:await requirePassword(),p_key:select.dataset.feature,p_status:select.value}),'تم تحديث الخدمة')}if(select.matches('[data-tool]')){event.stopImmediatePropagation();run(select,async()=>rpc('uon_admin_set_tool',{p_password:await requirePassword(),p_tool_id:select.dataset.tool,p_status:select.value}),'تم تحديث الأداة')}},true);
document.addEventListener('click',event=>{const approve=event.target.closest('[data-ok]'),reject=event.target.closest('[data-no]'),suggestionReview=event.target.closest('[data-sug-ok]'),suggestionDelete=event.target.closest('[data-sug-del]'),target=approve||reject||suggestionReview||suggestionDelete;if(!target)return;event.preventDefault();event.stopImmediatePropagation();const table=suggestionReview||suggestionDelete?'feature_suggestions':document.querySelector('#pendingTable')?.value;const id=approve?.dataset.ok||reject?.dataset.no||suggestionReview?.dataset.sugOk||suggestionDelete?.dataset.sugDel;const action=approve?'approve':reject?'reject':suggestionReview?'review':'delete';run(target,async()=>rpc('uon_admin_moderate',{p_password:await requirePassword(),p_table:table,p_id:String(id),p_action:action}),action==='approve'?'تم القبول':action==='review'?'تمت المراجعة':action==='delete'?'تم الحذف':'تم الرفض')},true);
document.addEventListener('click',event=>{const add=event.target.closest('#addAd'),toggle=event.target.closest('[data-togglead]'),del=event.target.closest('[data-delad]'),target=add||toggle||del;if(!target)return;event.preventDefault();event.stopImmediatePropagation();const action=add?'create':toggle?'toggle':'delete',id=toggle?.dataset.togglead||del?.dataset.delad||null,payload=add?{title:document.querySelector('#adTitle')?.value||'',body:document.querySelector('#adBody')?.value||'',button_url:document.querySelector('#adUrl')?.value||'',starts_at:document.querySelector('#adStartsAt')?.value||'',ends_at:document.querySelector('#adEndsAt')?.value||'',priority:10}:{};run(target,async()=>rpc('uon_admin_announcement',{p_password:await requirePassword(),p_action:action,p_id:id,p_payload:payload}),action==='create'?'تمت إضافة الإعلان':action==='toggle'?'تم تحديث حالة الإعلان':'تم حذف الإعلان')},true);
document.addEventListener('click',event=>{const add=event.target.closest('#addTg'),del=event.target.closest('[data-deltg]'),target=add||del;if(!target)return;event.preventDefault();event.stopImmediatePropagation();const action=add?'create':'delete',payload=add?{name:document.querySelector('#tgName')?.value||'',chat_id:document.querySelector('#tgChat')?.value||'',role:document.querySelector('#tgRole')?.value||'moderator'}:{};run(target,async()=>rpc('uon_admin_catalog_action',{p_password:await requirePassword(),p_entity:'telegram_admins',p_action:action,p_id:del?.dataset.deltg||null,p_payload:payload}),action==='create'?'تمت إضافة المشرف':'تم حذف المشرف')},true);
document.addEventListener('click',event=>{const mappings=[['[data-cal-del]','academic_calendar_events','calDel','تم حذف الموعد'],['[data-course-del]','courses','courseDel','تم حذف المادة'],['[data-notify-del]','site_notifications','notifyDel','تم حذف الإشعار']];for(const[selector,entity,key,message]of mappings){const target=event.target.closest(selector);if(!target)continue;event.preventDefault();event.stopImmediatePropagation();run(target,async()=>rpc('uon_admin_catalog_action',{p_password:await requirePassword(),p_entity:entity,p_action:'delete',p_id:target.dataset[key],p_payload:{}}),message);return}},true);
document.addEventListener('submit',event=>{const form=event.target,map={calendarForm:['academic_calendar_events','تمت إضافة الموعد'],notificationForm:['site_notifications','تم نشر الإشعار']},config=map[form.id];if(!config)return;event.preventDefault();event.stopImmediatePropagation();const[entity,message]=config,submit=form.querySelector('[type="submit"],button');run(submit,async()=>rpc('uon_admin_catalog_action',{p_password:await requirePassword(),p_entity:entity,p_action:'create',p_id:null,p_payload:formPayload(form)}),message)},true);
document.addEventListener('submit',event=>{const form=event.target;if(!['anjizSettings','masalikSettings'].includes(form.id))return;event.preventDefault();event.stopImmediatePropagation();const prefix=form.id==='anjizSettings'?'anjiz':'masalik',data=formPayload(form),submit=form.querySelector('[type="submit"],button');run(submit,async()=>rpc('uon_admin_save_site_settings',{p_password:await requirePassword(),p_settings:{[`${prefix}_title`]:data.title||'',[`${prefix}_description`]:data.description||'',[`${prefix}_booking_url`]:data.booking_url||'',[`${prefix}_cta`]:data.cta||''}}),'تم حفظ بيانات المركز')},true);

// V40: ترتيب لوحة الإدارة بدون حذف أي وظيفة.
const groups=[
 ['الرئيسية',[['overview','نظرة عامة'],['pending','الطلبات المعلقة'],['features','الخدمات وحالتها'],['health','حالة النظام']]],
 ['المحتوى',[['courses-admin','المقررات'],['programs','دليل الجامعة'],['announcements','الإعلانات'],['calendar-admin','التقويم'],['suggestions','الاقتراحات والبلاغات']]],
 ['الإدارة',[['telegram','المشرفون والصلاحيات'],['imports','الاستيراد الجماعي'],['backups','النسخ الاحتياطي'],['audit','سجل العمليات'],['analytics','الإحصائيات']]],
 ['إعدادات إضافية',[['site','الموقع والصيانة'],['tools','الأدوات الخارجية'],['notifications-admin','إشعارات الموقع'],['centers','مراكز الدعم'],['operations-v31','العمليات المتقدمة']]]
];
function buildCleanSidebar(){
 const sidebar=document.querySelector('#sidebar');if(!sidebar)return;
 sidebar.innerHTML='<div class="admin40-brand"><strong>UON Hub</strong><span>لوحة الإدارة V40</span></div>'+groups.map(([title,items],index)=>`<details class="admin40-group" ${index<2?'open':''}><summary>${title}</summary><div>${items.map(([id,label])=>`<button class="btn" data-section="${id}">${label}</button>`).join('')}</div></details>`).join('');
 const style=document.createElement('style');style.textContent=`.admin40-brand{padding:8px 4px 18px;display:grid;gap:3px}.admin40-brand strong{font-size:21px}.admin40-brand span{font-size:12px;opacity:.65}.admin40-group{border-top:1px solid #ffffff12;padding:10px 0}.admin40-group summary{cursor:pointer;font-weight:900;padding:8px 4px}.admin40-group>div{display:grid;gap:6px;padding-top:6px}.admin40-group .btn{text-align:right;width:100%;justify-content:flex-start}.admin-layout{grid-template-columns:minmax(230px,270px) 1fr}.admin-main{max-width:1500px}.admin-section{animation:admin40In .18s ease}@keyframes admin40In{from{opacity:.3;transform:translateY(4px)}}@media(max-width:850px){.admin-layout{display:block}.sidebar{position:fixed;z-index:80;inset:0 auto 0 0;width:min(86vw,320px);overflow:auto;transform:translateX(-105%);transition:.2s}.sidebar.open{transform:none}}`;
 document.head.append(style);
}
function removeLegacyDuplication(){document.querySelector('#sec-v16-overview')?.remove();document.querySelectorAll('#pendingTable option[value="confessions"]').forEach(option=>option.remove());const pending=document.querySelector('#pendingTable');if(pending&&!pending.querySelector('option[value="course_requests"]'))pending.insertAdjacentHTML('beforeend','<option value="course_requests">طلبات محتوى المقررات</option><option value="content_reports">بلاغات المحتوى</option>')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{buildCleanSidebar();removeLegacyDuplication()},{once:true});else{buildCleanSidebar();removeLegacyDuplication()}
