
import {$,$$,get,insert,update,remove,rpc,toast,esc} from './core.js';
let authed=false;
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await rpc('check_admin_password',{p_password:$('#password').value});if(!(r?.ok??r===true))throw new Error('كلمة المرور غير صحيحة');authed=true;sessionStorage.setItem('uon_admin','1');$('#login').hidden=true;$('#dashboard').hidden=false;loadAll()}catch(err){toast(err.message,true)}};
if(sessionStorage.getItem('uon_admin')==='1'){authed=true;$('#login').hidden=true;$('#dashboard').hidden=false;loadAll()}
$('#logout').onclick=()=>{sessionStorage.clear();location.reload()};$('#menuAdmin').onclick=()=>$('#sidebar').classList.toggle('open');
$$('[data-section]').forEach(b=>b.onclick=()=>{$$('.admin-section').forEach(x=>x.classList.remove('active'));$('#sec-'+b.dataset.section).classList.add('active');$('#sidebar').classList.remove('open');if(b.dataset.section==='pending')loadPending()});
async function settings(){const r=await get('site_settings','select=key,value');const m=Object.fromEntries(r.map(x=>[x.key,x.value]));$('#maintenance').checked=m.maintenance_enabled===true||String(m.maintenance_enabled).toLowerCase()==='true';$('#maintenanceMessage').value=m.maintenance_message||'';$('#whatsappUrl').value=m.whatsapp_channel_url||''}
async function upsertSetting(key,value){const r=await get('site_settings',`select=key&key=eq.${encodeURIComponent(key)}`);return r.length?update('site_settings',`key=eq.${encodeURIComponent(key)}`,{value,updated_at:new Date().toISOString()}):insert('site_settings',{key,value})}
$('#saveSite').onclick=async()=>{try{await Promise.all([upsertSetting('maintenance_enabled',$('#maintenance').checked),upsertSetting('maintenance_message',$('#maintenanceMessage').value),upsertSetting('whatsapp_channel_url',$('#whatsappUrl').value)]);toast('تم الحفظ')}catch(e){toast(e.message,true)}};
async function features(){const r=await get('platform_features','select=*&order=sort_order.asc');$('#featuresList').innerHTML=r.map(x=>`<div class="list-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.key)}</small></div><select data-feature="${esc(x.key)}"><option value="active" ${x.status==='active'?'selected':''}>تشغيل</option><option value="disabled" ${x.status==='disabled'?'selected':''}>إيقاف</option><option value="coming_soon" ${x.status==='coming_soon'?'selected':''}>قريبًا</option><option value="maintenance" ${x.status==='maintenance'?'selected':''}>صيانة</option></select></div>`).join('');$$('[data-feature]').forEach(s=>s.onchange=async()=>{await update('platform_features',`key=eq.${encodeURIComponent(s.dataset.feature)}`,{status:s.value,updated_at:new Date().toISOString()});toast('تم تحديث الخدمة')})}
const defs={summaries:['title','approved'],whatsapp_groups:['subject','approved'],student_market:['title','status'],rating_submissions:['target_name','status'],confessions:['content','status']};
async function loadPending(){const t=$('#pendingTable').value,[title,col]=defs[t];const q=col==='approved'?`${col}=eq.false`:`${col}=eq.pending`;const r=await get(t,`select=*&${q}&order=created_at.desc`);$('#pendingList').innerHTML=r.length?r.map(x=>`<div class="list-row"><div><strong>${esc(x[title])}</strong><small>${new Date(x.created_at).toLocaleString('ar')}</small></div><div class="actions"><button class="btn success" data-ok="${x.id}">قبول</button><button class="btn danger" data-no="${x.id}">رفض</button></div></div>`).join(''):'<div class="empty">لا توجد طلبات</div>';$$('[data-ok]').forEach(b=>b.onclick=()=>moderate(t,b.dataset.ok,true));$$('[data-no]').forEach(b=>b.onclick=()=>moderate(t,b.dataset.no,false))}
async function moderate(t,id,ok){const col=defs[t][1];if(!ok&&col==='approved')await remove(t,`id=eq.${id}`);else await update(t,`id=eq.${id}`,col==='approved'?{approved:true}:{status:ok?'approved':'rejected'});toast(ok?'تم القبول':'تم الرفض');loadPending()}
$('#pendingTable').onchange=loadPending;
async function ads(){const r=await get('site_announcements','select=*&order=created_at.desc');$('#adsList').innerHTML=r.map(x=>`<div class="list-row"><strong>${esc(x.title)}</strong><button class="btn danger" data-delad="${x.id}">حذف</button></div>`).join('');$$('[data-delad]').forEach(b=>b.onclick=async()=>{await remove('site_announcements',`id=eq.${b.dataset.delad}`);ads()})}
$('#addAd').onclick=async()=>{await insert('site_announcements',{title:$('#adTitle').value,body:$('#adBody').value,button_url:$('#adUrl').value||null,active:true,priority:10});toast('تمت الإضافة');ads()}
async function tools(){const r=await get('tools_items','select=*&order=name.asc');$('#toolsList').innerHTML=r.map(x=>`<div class="list-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.url||'')}</small></div><select data-tool="${esc(x.id)}"><option value="active" ${x.status==='active'?'selected':''}>تشغيل</option><option value="disabled" ${x.status==='disabled'?'selected':''}>إيقاف</option><option value="coming_soon" ${x.status==='coming_soon'?'selected':''}>قريبًا</option><option value="maintenance" ${x.status==='maintenance'?'selected':''}>صيانة</option></select></div>`).join('');$$('[data-tool]').forEach(s=>s.onchange=()=>update('tools_items',`id=eq.${encodeURIComponent(s.dataset.tool)}`,{status:s.value,disabled:s.value!=='active'}))}
async function programs(){const r=await get('university_programs','select=*&order=college.asc,name_ar.asc');$('#programsList').innerHTML=r.map(x=>`<div class="list-row"><div><strong>${esc(x.name_ar)}</strong><small>${esc(x.college)}</small></div><span>${x.credit_hours||'—'} ساعة</span></div>`).join('')}
async function tg(){const r=await get('telegram_admins','select=*&order=created_at.desc');$('#tgList').innerHTML=r.map(x=>`<div class="list-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.chat_id)} • ${esc(x.role)}</small></div><button class="btn danger" data-deltg="${x.id}">حذف</button></div>`).join('');$$('[data-deltg]').forEach(b=>b.onclick=async()=>{await remove('telegram_admins',`id=eq.${b.dataset.deltg}`);tg()})}
$('#addTg').onclick=async()=>{await insert('telegram_admins',{name:$('#tgName').value,chat_id:$('#tgChat').value,role:$('#tgRole').value,active:true,notifications_enabled:true});toast('تمت الإضافة');tg()}
async function stats(){const names=['summaries','whatsapp_groups','student_market','rating_submissions'];const counts=[];for(const t of names){const r=await get(t,'select=id');counts.push(r.length)}$('#stats').innerHTML=names.map((n,i)=>`<div class="card stat"><span>${n}</span><strong>${counts[i]}</strong></div>`).join('')}
async function loadAll(){await Promise.allSettled([settings(),features(),loadPending(),ads(),tools(),programs(),tg(),stats()])}
