import{$,enforceUonMaintenance,watchUonMaintenance,trackEvent,applyFeatureStates}from'./core.js?v=42.0.0';
const API='https://irkhvydgxpseflggbeqq.supabase.co/functions/v1/uon-ai-chat-v64';
const form=$('#chatForm'),input=$('#question'),chat=$('#chat'),submitButton=form?.querySelector('button[type="submit"]');
const history=[];let sending=false,currentController=null,lastQuestion='';
const sessionKey='uon_ai_session_v46',clientKey='uon_ai_client_v55',planKey='uon_ai_pending_schedule_v1';
function uuid(){try{return crypto.randomUUID()}catch{return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}}
function getSessionId(){let id=sessionStorage.getItem(sessionKey)||'';if(!/^[0-9a-f-]{36}$/i.test(id)){id=uuid();sessionStorage.setItem(sessionKey,id)}return id}
function getClientToken(){let id='';try{id=localStorage.getItem(clientKey)||''}catch{}if(!/^[0-9a-f-]{36}$/i.test(id)){id=uuid();try{localStorage.setItem(clientKey,id)}catch{}}return id}
const sessionId=getSessionId(),clientToken=getClientToken();
const lang=()=>localStorage.getItem('uon_language')==='en'?'en':'ar',t=(ar,en)=>lang()==='en'?en:ar;
const cleanText=value=>String(value??'').replace(/^#{1,6}\s*/gm,'').replace(/\*\*(.*?)\*\*/g,'$1').replace(/__(.*?)__/g,'$1').trim();
function addResponseTools(article,question){if(!article||!question)return;const row=document.createElement('div');row.className='assistant-response-tools';const copy=document.createElement('button');copy.type='button';copy.className='assistant-response-tool';copy.innerHTML='⧉ <span>'+t('نسخ','Copy')+'</span>';copy.onclick=async()=>{const text=article.querySelector('.message-content')?.textContent?.trim()||'';if(!text)return;try{await navigator.clipboard.writeText(text);copy.innerHTML='✓ <span>'+t('تم النسخ','Copied')+'</span>'}catch{}};const retry=document.createElement('button');retry.type='button';retry.className='assistant-response-tool';retry.innerHTML='↻ <span>'+t('إعادة الإجابة','Regenerate')+'</span>';retry.onclick=()=>{if(!sending)void submitQuestion(question,{repeat:true})};row.append(copy,retry);article.appendChild(row)}
function addMinimalLink(article,links=[]){const item=Array.isArray(links)?links.find(x=>x?.url):null;if(!article||!item)return;const row=document.createElement('div');row.className='assistant-links assistant-links-minimal';const a=document.createElement('a');a.href=item.url;a.target=/^https?:/i.test(item.url)?'_blank':'_self';a.rel='noopener noreferrer';a.textContent=item.type==='Google Maps'?t('فتح في Google Maps','Open in Google Maps'):(item.official?t('المصدر الرسمي','Official source'):t('المصدر','Source'));row.appendChild(a);article.appendChild(row)}
function addMessage(role,content,links=[]){if(!chat)return null;const article=document.createElement('article');article.className=`message ${role}`;const body=document.createElement('div');body.className='message-content';body.textContent=cleanText(content);article.appendChild(body);if(role==='bot')addMinimalLink(article,links);chat.appendChild(article);chat.scrollTop=chat.scrollHeight;return article}
function addTyping(){const el=document.createElement('article');el.className='message bot typing-message';el.innerHTML='<div class="typing-dots" aria-hidden="true"><span></span><span></span><span></span></div>';chat?.appendChild(el);return el}
function scheduleRows(plan){const courses=plan?.schedule?.courses;if(!Array.isArray(courses))return[];const out=[];for(const c of courses){const meetings=Array.isArray(c.meetings)?c.meetings:(Array.isArray(c.times)?c.times:[]);for(const m of meetings)out.push({course:c.course_code||c.course||'',day:m.day_name||m.day||'',start:String(m.start_time||m.start||'').slice(0,5),end:String(m.end_time||m.end||'').slice(0,5),room:m.room||c.room||'',teacher:m.instructor||c.instructor||'',type:'lecture'})}return out.filter(x=>x.course&&x.day&&x.start&&x.end)}
function attachPlanAction(article,result){if(!article||result?.mode!=='semester_planner'||result?.semester_plan?.status!=='ready')return;const rows=scheduleRows(result.semester_plan);if(!rows.length)return;const row=document.createElement('div');row.className='assistant-response-tools';const b=document.createElement('button');b.type='button';b.className='assistant-response-tool';b.textContent=t('أضف هذا الجدول','Apply this schedule');b.onclick=()=>{try{sessionStorage.setItem(planKey,JSON.stringify({term:result.semester_plan.term,rows,created_at:Date.now()}));location.href='/schedule.html?from=ai'}catch{b.textContent=t('تعذر إضافة الجدول','Could not apply')}};row.appendChild(b);article.appendChild(row)}
function attachGooglePlaces(article,result){const places=Array.isArray(result?.google_places)?result.google_places.slice(0,4):[];if(!article||!places.length)return;const wrap=document.createElement('section');wrap.className='assistant-google-places';const head=document.createElement('div');head.className='assistant-google-places-head';head.innerHTML=`<strong>${t('نتائج مباشرة من Google Maps','Live Google Maps results')}</strong><small>${t('تُجلب مباشرة ولا نخزن تفاصيل Google في قاعدة البيانات','Fetched live; Google place details are not stored in UON Hub')}</small>`;wrap.appendChild(head);for(const place of places){const card=document.createElement('a');card.className='assistant-google-place';card.href=place.maps_url||'#';card.target='_blank';card.rel='noopener noreferrer';const state=typeof place.open_now==='boolean'?(place.open_now?t('مفتوح الآن','Open now'):t('مغلق الآن','Closed now')):'';card.innerHTML=`<span><strong></strong><small></small></span><b>${state}</b>`;card.querySelector('strong').textContent=place.name||'';card.querySelector('small').textContent=place.address||'';wrap.appendChild(card)}const attribution=document.createElement('div');attribution.className='assistant-google-attribution';attribution.textContent='Google Maps';wrap.appendChild(attribution);article.appendChild(wrap)}
async function ask(question,signal,regenerate=false){const response=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,history:history.slice(-12),language:lang(),page_context:location.pathname,session_id:sessionId,client_token:clientToken,channel:'web',regenerate:Boolean(regenerate)}),cache:'no-store',signal});const data=await response.json().catch(()=>({}));if(!response.ok||!data.answer)throw new Error(data.error||`AI HTTP ${response.status}`);return data}
async function sendFeedback(result,question,rating){if(!result?.request_id)return false;return(await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'feedback',request_id:result.request_id,rating,question,answer:result.answer})})).ok}
function attachFeedback(article,question,result){if(!article||!result?.request_id)return;const row=document.createElement('div');row.className='assistant-feedback';const label=document.createElement('span');label.textContent=t('هل أفادك الرد؟','Was this helpful?');row.appendChild(label);[-1,1].forEach(rating=>{const b=document.createElement('button');b.type='button';b.className='assistant-feedback-btn';b.textContent=rating===1?'👍':'👎';b.onclick=async()=>{if(row.dataset.sent)return;row.dataset.sent='1';try{await sendFeedback(result,question,rating);label.textContent=t('وصلت 👍','Got it 👍')}catch{row.dataset.sent=''}};row.appendChild(b)});article.appendChild(row)}
function setSendingState(active){sending=active;if(submitButton){submitButton.disabled=active;submitButton.hidden=active}const stop=$('#assistantStop');if(stop)stop.hidden=!active}
async function submitQuestion(question,opts={}){if(sending||!question)return;lastQuestion=question;setSendingState(true);if(!opts.repeat){addMessage('user',question);history.push({role:'user',content:question});input.value=''}const typing=addTyping();currentController=new AbortController();const timer=setTimeout(()=>currentController?.abort(),30000);try{const result=await ask(question,currentController.signal,Boolean(opts.repeat));typing.remove();const article=addMessage('bot',result.answer,result.links||[]);history.push({role:'assistant',content:result.answer});attachGooglePlaces(article,result);attachPlanAction(article,result);attachFeedback(article,question,result);addResponseTools(article,question)}catch{typing.remove();addMessage('bot',t('تعذر الوصول إلى UON AI الآن. جرّب مرة أخرى بعد قليل.','UON AI is unavailable right now. Try again shortly.'))}finally{clearTimeout(timer);currentController=null;setSendingState(false);input?.focus()}}
function handleSubmit(e){e?.preventDefault();const q=input?.value?.trim()||'';if(q)void submitQuestion(q);return false}
if(form){form.action='javascript:void(0)';form.addEventListener('submit',handleSubmit,true)}input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handleSubmit(e)}});$('#assistantStop')?.addEventListener('click',()=>currentController?.abort());document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt||b.textContent.trim();input.focus()}));
async function initialize(){try{await enforceUonMaintenance()}catch{}try{watchUonMaintenance()}catch{}try{await applyFeatureStates(document)}catch{}try{trackEvent('page_view',{page:'assistant-v64'})}catch{}}
initialize();