import './assistant-schedule-actions-v63.js?v=63.0.0';
const SESSION_KEY='uon_ai_session_v46';
const STORE_KEY='uon_ai_history_v47';
const CLIENT_KEY='uon_ai_client_v55';
const CHAT_API='https://irkhvydgxpseflggbeqq.supabase.co/functions/v1/uon-ai-chat-v64';
const qs=new URLSearchParams(location.search),requested=qs.get('chat')||'';
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v||'');
const makeId=()=>{try{return crypto.randomUUID()}catch{return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}};
function clientToken(){let token='';try{token=localStorage.getItem(CLIENT_KEY)||''}catch{}if(!/^[0-9a-f-]{36}$/i.test(token)){token=makeId();try{localStorage.setItem(CLIENT_KEY,token)}catch{}}return token}
const CLIENT_TOKEN=clientToken();
if(isUuid(requested))sessionStorage.setItem(SESSION_KEY,requested);
if(!isUuid(sessionStorage.getItem(SESSION_KEY)||''))sessionStorage.setItem(SESSION_KEY,makeId());
const activeId=()=>sessionStorage.getItem(SESSION_KEY);
const readStore=()=>{try{return JSON.parse(localStorage.getItem(STORE_KEY)||'{}')||{}}catch{return{}}};
const writeStore=data=>{try{localStorage.setItem(STORE_KEY,JSON.stringify(data))}catch{}};
const msgText=el=>el?.querySelector('.message-content')?.textContent?.trim()||el?.textContent?.trim()||'';
function snapshot(){const chat=document.querySelector('#chat');if(!chat)return;const messages=[...chat.querySelectorAll(':scope > .message.user,:scope > .message.bot')].map(el=>({role:el.classList.contains('user')?'user':'assistant',content:msgText(el)})).filter(x=>x.content&&!/^هلا 👋/.test(x.content)&&!/^تم إيقاف الرد/.test(x.content));if(!messages.length)return;const data=readStore(),id=activeId(),firstUser=messages.find(x=>x.role==='user')?.content||'محادثة UON AI';data[id]={id,title:firstUser.slice(0,55),updated_at:Date.now(),messages:messages.slice(-30)};writeStore(data);renderHistory()}
function appendMeta(article,meta){if(!article||!meta)return;if(Array.isArray(meta.links)&&meta.links.length){const item=meta.links.find(x=>x?.url);if(item){const row=document.createElement('div');row.className='assistant-links assistant-links-minimal';const a=document.createElement('a');a.href=item.url;a.target=/^https?:/i.test(item.url)?'_blank':'_self';a.rel='noopener noreferrer';a.textContent=item.type==='Instagram'||/instagram\.com/i.test(item.url)?'@uonhub':(item.official?'المصدر الرسمي':'المصدر');row.appendChild(a);article.appendChild(row)}}}
function paint(messages){const chat=document.querySelector('#chat');if(!chat||!Array.isArray(messages)||!messages.length)return false;chat.innerHTML='';for(const m of messages){if(!m?.content)continue;const role=m.role==='user'?'user':'bot',article=document.createElement('article');article.className=`message ${role}`;const body=document.createElement('div');body.className='message-content';body.textContent=m.content;article.appendChild(body);if(role==='bot')appendMeta(article,m.meta);chat.appendChild(article)}chat.scrollTop=chat.scrollHeight;return true}
function restoreLocal(){const data=readStore(),entry=data[activeId()];return entry?.messages?.length?paint(entry.messages):false}
async function restoreServer(){const id=activeId();if(!isUuid(id))return false;try{const res=await fetch(CHAT_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'history',session_id:id,client_token:CLIENT_TOKEN,limit:30}),cache:'no-store',signal:AbortSignal.timeout(9000)});if(!res.ok)return false;const data=await res.json().catch(()=>({})),messages=Array.isArray(data.messages)?data.messages.filter(x=>x?.content):[];if(!messages.length)return false;const store=readStore(),firstUser=messages.find(x=>x.role==='user')?.content||'محادثة UON AI';store[id]={id,title:firstUser.slice(0,55),updated_at:data.last_message_at?Date.parse(data.last_message_at)||Date.now():Date.now(),messages:messages.slice(-30).map(x=>({role:x.role,content:x.content,request_id:x.request_id||null,meta:x.meta||null}))};writeStore(store);paint(messages);renderHistory();return true}catch{return false}}
function startNew(){sessionStorage.setItem(SESSION_KEY,makeId());location.href='assistant.html'}
function openConversation(id){if(!isUuid(id))return;sessionStorage.setItem(SESSION_KEY,id);location.href=`assistant.html?chat=${encodeURIComponent(id)}`}
function removeConversation(id,event){event?.stopPropagation();const data=readStore();delete data[id];writeStore(data);if(id===activeId())return startNew();renderHistory()}
function renderHistory(){const host=document.querySelector('#assistantHistoryItems');if(!host)return;const rows=Object.values(readStore()).sort((a,b)=>(b.updated_at||0)-(a.updated_at||0)).slice(0,20);host.innerHTML='';if(!rows.length){host.innerHTML='<p class="assistant-history-empty">ما عندك محادثات محفوظة للحين.</p>';return}for(const row of rows){const b=document.createElement('button');b.type='button';b.className='assistant-history-item'+(row.id===activeId()?' active':'');const date=new Date(row.updated_at||Date.now()).toLocaleDateString('ar-OM',{month:'short',day:'numeric'});b.innerHTML=`<span><strong></strong><small>${date}</small></span><i aria-label="حذف">×</i>`;b.querySelector('strong').textContent=row.title||'محادثة UON AI';b.addEventListener('click',()=>openConversation(row.id));b.querySelector('i').addEventListener('click',e=>removeConversation(row.id,e));host.appendChild(b)}}
async function boot(){const chat=document.querySelector('#chat'),restored=restoreLocal();renderHistory();if(isUuid(requested))await restoreServer();else if(!restored)await restoreServer();document.querySelector('#assistantNewChat')?.addEventListener('click',startNew);const drawer=document.querySelector('#assistantHistoryDrawer'),open=document.querySelector('#assistantHistoryOpen'),close=document.querySelector('#assistantHistoryClose');open?.addEventListener('click',()=>drawer?.classList.add('open'));close?.addEventListener('click',()=>drawer?.classList.remove('open'));if(chat){let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(snapshot,140)}).observe(chat,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>void boot(),{once:true});else void boot();
