import{$,esc,enforceUonMaintenance,watchUonMaintenance,trackEvent,applyFeatureStates,get}from'./core.js?v=42.0.0';
const API='https://irkhvydgxpseflggbeqq.supabase.co/functions/v1/uon-ai-v3';
const LIVE_API='https://irkhvydgxpseflggbeqq.supabase.co/functions/v1/uon-ai-live-sync';
const form=$('#chatForm'),input=$('#question'),chat=$('#chat'),submitButton=form?.querySelector('button[type="submit"]');
const HISTORY_KEY='uon_ai_history_v6',SESSION_KEY='uon_ai_session_v1',TOKEN_KEY='uon_ai_client_token_v1';
const MAX_STORED=16;let history=[];let sending=false;let liveTimer=null;let liveStatus='ai';let liveLastId=0;let liveBusy=false;
const lang=()=>localStorage.getItem('uon_language')==='en'?'en':'ar';const t=(ar,en)=>lang()==='en'?en:ar;
function newToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function clientToken(){let token=localStorage.getItem(TOKEN_KEY);if(!token){token=newToken();localStorage.setItem(TOKEN_KEY,token)}return token}
function sessionId(){let id=localStorage.getItem(SESSION_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(SESSION_KEY,id)}return id}
function lastKey(){return `uon_ai_live_last_${sessionId()}`}
function pageContext(){const title=document.title||'';const path=location.pathname;return `${title} | ${path}`.slice(0,240)}
function isHandoff(q){return /(^|\s)(مشرف|موظف|انسان|إنسان|بشري|human|admin|supervisor)(\s|$)/i.test(q)}
function loadHistory(){try{const saved=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');if(Array.isArray(saved))history=saved.slice(-MAX_STORED).filter(x=>x&&['user','assistant','supervisor','system'].includes(x.role)&&typeof x.content==='string')}catch{history=[]}try{liveLastId=Number(localStorage.getItem(lastKey())||0)||0}catch{liveLastId=0}}
function saveHistory(){try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history.slice(-MAX_STORED)))}catch{}}
function saveLiveLast(){try{localStorage.setItem(lastKey(),String(liveLastId||0))}catch{}}
function setLiveBadge(status){liveStatus=status||'ai';const el=document.querySelector('#aiLiveState');if(!el)return;el.dataset.status=liveStatus;el.textContent=liveStatus==='human'?t('المشرف متصل بالمحادثة 👤','Human support active 👤'):liveStatus==='closed'?t('المحادثة مغلقة','Conversation closed'):t('UON AI متاح','UON AI available')}
async function liveRequest(payload){const response=await fetch(LIVE_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId(),client_token:clientToken(),...payload}),cache:'no-store',signal:AbortSignal.timeout(10000)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Live HTTP ${response.status}`);return data}
async function registerLiveSession(){try{const data=await liveRequest({action:'register',channel:'web',page_context:pageContext()});setLiveBadge(data.status||'ai');if(data.status==='human')startLiveSync();return true}catch(error){console.warn('UON AI live register',error);return false}}
function stopLiveSync(){if(liveTimer){clearInterval(liveTimer);liveTimer=null}}
function appendLiveMessage(row){if(!row?.content)return;if(row.role==='supervisor'){addMessage('supervisor',row.content,[],{live:true});history.push({role:'supervisor',content:row.content});saveHistory()}else if(row.role==='system'){addMessage('system',row.content,[],{live:true});history.push({role:'system',content:row.content});saveHistory()}}
async function pollLive(){if(liveBusy)return;liveBusy=true;try{const data=await liveRequest({action:'poll',after_id:liveLastId});for(const row of data.messages||[]){appendLiveMessage(row);liveLastId=Math.max(liveLastId,Number(row.id||0))}saveLiveLast();const previous=liveStatus;setLiveBadge(data.status||'ai');if(previous==='human'&&data.status==='ai'){addMessage('system',t('رجع المشرف المحادثة إلى UON AI 🤖','The supervisor returned this conversation to UON AI 🤖'));stopLiveSync()}else if(data.status==='closed'){addMessage('system',t('تم إغلاق المحادثة من المشرف. تقدر تبدأ محادثة جديدة.','The supervisor closed this conversation. You can start a new chat.'));stopLiveSync()}}catch(error){console.warn('UON AI live poll',error)}finally{liveBusy=false}}
function startLiveSync(){if(liveTimer)return;pollLive();liveTimer=setInterval(pollLive,2500)}
async function clearConversation(){stopLiveSync();history=[];saveHistory();localStorage.setItem(SESSION_KEY,crypto.randomUUID());localStorage.setItem(TOKEN_KEY,newToken());liveLastId=0;liveStatus='ai';if(chat){chat.innerHTML='';addMessage('bot',t('هلا 👋 أنا UON AI. اسألني عن المقررات، الملخصات، المجموعات، الخدمات، المواعيد أو دليل الجامعة.','Hi 👋 I’m UON AI. Ask me about courses, summaries, groups, services, dates, or the university guide.'))}setLiveBadge('ai');await registerLiveSession();input?.focus();try{trackEvent('assistant_clear_v6',{})}catch{}}
function renderActions(article,actions=[]){if(!Array.isArray(actions)||!actions.length)return;const box=document.createElement('div');box.className='assistant-actions';actions.slice(0,3).forEach(item=>{if(!item?.url)return;const a=document.createElement('a');a.href=item.url;a.className='assistant-action';a.innerHTML=`<span>${esc(item.icon||'↗')}</span><strong>${esc(item.label||t('فتح','Open'))}</strong>`;box.appendChild(a)});if(box.childElementCount)article.appendChild(box)}
function renderSuggestions(article,suggestions=[]){if(!Array.isArray(suggestions)||!suggestions.length)return;const box=document.createElement('div');box.className='assistant-suggestions';suggestions.slice(0,4).forEach(text=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',()=>submitQuestion(String(text)));box.appendChild(b)});article.appendChild(box)}
function renderFeedback(article,meta,content){if(!meta?.request_id)return;const box=document.createElement('div');box.className='assistant-feedback';const label=document.createElement('span');label.textContent=t('هل كانت الإجابة مفيدة؟','Was this answer helpful?');box.appendChild(label);[[1,'👍'],[-1,'👎']].forEach(([rating,icon])=>{const b=document.createElement('button');b.type='button';b.textContent=icon;b.addEventListener('click',async()=>{if(box.dataset.sent)return;box.dataset.sent='1';box.querySelectorAll('button').forEach(x=>x.disabled=true);try{await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'feedback',request_id:meta.request_id,rating,question:meta.question||'',answer:content,session_id:sessionId()}),cache:'no-store'});label.textContent=t('شكراً على تقييمك 🤍','Thanks for your feedback 🤍')}catch{label.textContent=t('تم تسجيل اختيارك.','Your choice was recorded.')}});box.appendChild(b)});article.appendChild(box)}
function addMessage(role,content,links=[],meta={}){if(!chat)return null;const article=document.createElement('article');article.className=`message ${role}`;if(role==='supervisor'){const tag=document.createElement('div');tag.className='assistant-human-tag';tag.textContent=t('رد المشرف','Supervisor reply');article.appendChild(tag)}const body=document.createElement('div');body.className='message-content';body.textContent=content;article.appendChild(body);if(role==='bot'&&meta.grounded){const evidence=document.createElement('div');evidence.className='assistant-source-note';const confidence=Math.round(Number(meta.confidence||0)*100);evidence.textContent=`${t('إجابة مدعومة من بيانات UON Hub','Grounded in UON Hub data')}${confidence?` • ${t('الثقة','Confidence')} ${confidence}%`:''}${meta.sources_count!=null?` • ${meta.sources_count} ${t('مصدر','sources')}`:''}`;article.appendChild(evidence)}if(Array.isArray(links)&&links.length){const box=document.createElement('div');box.className='assistant-links';links.forEach(item=>{if(!item?.url)return;const a=document.createElement('a');a.href=item.url;a.target=/^https?:/i.test(item.url)?'_blank':'_self';a.rel='noopener noreferrer';a.innerHTML=`<span>${esc(item.official?t('مصدر رسمي','Official source'):item.type||t('مصدر','Source'))}</span><strong>${esc(item.title||item.url)}</strong>`;box.appendChild(a)});if(box.childElementCount)article.appendChild(box)}if(role==='bot'){renderActions(article,meta.actions);renderSuggestions(article,meta.suggestions);renderFeedback(article,meta,content)}chat.appendChild(article);chat.scrollTop=chat.scrollHeight;return article}
function addTyping(){const el=document.createElement('article');el.className='message bot typing-message';el.innerHTML='<div class="typing-dots"><span></span><span></span><span></span></div>';chat?.appendChild(el);return el}
async function ask(question){await registerLiveSession();const response=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,history:history.filter(x=>x.role==='user'||x.role==='assistant').slice(-10),language:lang(),session_id:sessionId(),channel:'web',page_context:pageContext(),handoff_requested:isHandoff(question)}),cache:'no-store',signal:AbortSignal.timeout(30000)});const data=await response.json().catch(()=>({}));if(!response.ok||!data.answer){const error=new Error(data.message||data.error||`AI HTTP ${response.status}`);error.status=response.status;throw error}return data}
async function submitQuestion(question){question=String(question||'').trim();if(sending||!question)return;if(liveStatus==='closed'){addMessage('system',t('هذي المحادثة مغلقة. اضغط «محادثة جديدة» للبدء من جديد.','This conversation is closed. Tap “New chat” to start again.'));return}sending=true;addMessage('user',question);history.push({role:'user',content:question});saveHistory();if(input)input.value='';const typing=addTyping();const original=submitButton?.textContent||t('إرسال','Send');if(submitButton){submitButton.disabled=true;submitButton.textContent=t('جاري التفكير...','Thinking...')}try{trackEvent('assistant_question_v6',{query:question.slice(0,100),handoff:isHandoff(question)})}catch{}try{const result=await ask(question);typing.remove();result.question=question;addMessage('bot',result.answer,result.links||[],result);history.push({role:'assistant',content:result.answer});saveHistory();if(result.handoff){setLiveBadge('human');startLiveSync()}}catch(error){typing.remove();const message=error?.status===429?t('وصلنا للحد المؤقت للأسئلة. انتظر دقيقة وجرب مرة ثانية.','Temporary question limit reached. Wait a minute and try again.'):/timeout|abort/i.test(String(error?.message||error))?t('تأخر الاتصال. جرّب السؤال بشكل أقصر.','The request timed out. Try a shorter question.'):t('تعذر الوصول إلى UON AI الآن. جرّب مرة أخرى بعد قليل.','UON AI is unavailable right now. Try again shortly.');addMessage('bot',message)}finally{sending=false;if(submitButton){submitButton.disabled=false;submitButton.textContent=original}input?.focus()}}
function handleSubmit(event){event?.preventDefault();event?.stopPropagation();const question=input?.value?.trim()||'';if(!question){input?.focus();return false}submitQuestion(question);return false}
function installToolbar(){const host=document.querySelector('.v175-ai-chat');if(!host||host.querySelector('.assistant-toolbar'))return;const bar=document.createElement('div');bar.className='assistant-toolbar';bar.innerHTML=`<div><strong>UON AI</strong><small id="aiLiveState" data-status="ai">${t('UON AI متاح','UON AI available')}</small></div><div class="assistant-toolbar-actions"><button type="button" class="btn" id="humanAiChat">${t('👤 مشرف','👤 Human')}</button><button type="button" class="btn" id="clearAiChat">${t('محادثة جديدة','New chat')}</button></div>`;host.insertBefore(bar,host.firstChild);bar.querySelector('#clearAiChat')?.addEventListener('click',clearConversation);bar.querySelector('#humanAiChat')?.addEventListener('click',()=>submitQuestion(t('أريد مشرف','I need a human supervisor')))}
function restoreConversation(){if(!chat||!history.length)return;chat.innerHTML='';addMessage('bot',t('رجعت لك آخر محادثة محفوظة 👋','I restored your latest conversation 👋'));history.slice(-12).forEach(item=>addMessage(item.role==='assistant'?'bot':item.role,item.content))}
if(form){form.action='javascript:void(0)';form.addEventListener('submit',handleSubmit,true);form.onsubmit=handleSubmit}submitButton?.addEventListener('click',handleSubmit);input?.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();handleSubmit(event)}});document.querySelectorAll('[data-prompt]').forEach(button=>{button.type='button';button.addEventListener('click',()=>{input.value=button.dataset.prompt||button.textContent.trim();input.focus()})});
async function loadOfficialQuickActions(){const target=$('#officialQuickActions');if(!target)return;let actions=[['📘',t('ماذا يوجد لمادة STAT101؟','What is available for STAT101?')],['🎓',t('ما رابط القبول والتسجيل الرسمي؟','What is the official admissions link?')],['📅',t('ما مواعيد التقويم الأكاديمي؟','What are the academic calendar dates?')],['📚',t('أين أجد ملخصات واختبارات المقررات؟','Where can I find course summaries and exams?')]];try{const rows=await get('useful_sites','select=title_ar,title_en,icon&active=eq.true&category=eq.university&order=sort_order.asc&limit=6');if(rows?.length)actions=rows.map(x=>[x.icon||'🔗',t(`أعطني رابط ${x.title_ar} الرسمي`,`Give me the official ${x.title_en||x.title_ar} link`)])}catch{}target.innerHTML=actions.map(([icon,q])=>`<button type="button" data-official-question="${esc(q)}"><span>${esc(icon)}</span>${esc(q)}</button>`).join('');target.querySelectorAll('[data-official-question]').forEach(button=>button.addEventListener('click',()=>{input.value=button.dataset.officialQuestion;input.focus()}))}
function injectStyles(){if(document.getElementById('assistantV6Styles'))return;const style=document.createElement('style');style.id='assistantV6Styles';style.textContent=`.assistant-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;margin-bottom:10px;border:1px solid var(--line,#dfe7e2);border-radius:16px;background:color-mix(in srgb,var(--card,#fff) 92%,#0f7a4b 8%)}.assistant-toolbar>div{display:flex;gap:8px;align-items:center}.assistant-toolbar>div:first-child{display:grid;gap:2px}.assistant-toolbar small{opacity:.72}.assistant-toolbar small[data-status="human"]{font-weight:800;opacity:1}.assistant-toolbar small[data-status="closed"]{opacity:.55}.assistant-actions,.assistant-suggestions,.assistant-feedback{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.assistant-action,.assistant-suggestions button,.assistant-feedback button{border:1px solid var(--line,#dfe7e2);background:var(--card,#fff);color:inherit;border-radius:999px;padding:8px 11px;text-decoration:none;font:inherit}.assistant-action{display:inline-flex;align-items:center;gap:6px}.assistant-suggestions button,.assistant-feedback button{cursor:pointer}.assistant-feedback{align-items:center;font-size:.88rem;opacity:.9}.message-content{white-space:pre-wrap}.message.supervisor{margin-inline-start:auto;border:1px solid color-mix(in srgb,#0f7a4b 35%,transparent);background:color-mix(in srgb,var(--card,#fff) 88%,#0f7a4b 12%)}.assistant-human-tag{font-size:.75rem;font-weight:800;margin-bottom:5px;opacity:.72}.message.system{margin-inline:auto;max-width:88%;font-size:.83rem;text-align:center;opacity:.75;background:transparent;border:0;box-shadow:none}@media(max-width:640px){.assistant-toolbar{align-items:flex-start;flex-direction:column}.assistant-toolbar-actions{width:100%;justify-content:space-between}.assistant-toolbar .btn{font-size:.82rem;padding:8px 10px}}`;document.head.appendChild(style)}
async function initialize(){loadHistory();injectStyles();installToolbar();restoreConversation();await registerLiveSession();try{await enforceUonMaintenance()}catch{}try{watchUonMaintenance()}catch{}try{await applyFeatureStates(document)}catch{}try{trackEvent('page_view',{page:'assistant-v6'})}catch{}loadOfficialQuickActions()}
window.addEventListener('beforeunload',stopLiveSync);initialize();