import{$,enforceUonMaintenance,watchUonMaintenance,trackEvent,applyFeatureStates}from'./core.js?v=42.0.0';
const API='https://irkhvydgxpseflggbeqq.supabase.co/functions/v1/uon-ai-chat';
const form=$('#chatForm'),input=$('#question'),chat=$('#chat'),submitButton=form?.querySelector('button[type="submit"]');
const history=[];let sending=false,currentController=null,lastQuestion='';
const sessionKey='uon_ai_session_v46',clientKey='uon_ai_client_v55',planKey='uon_ai_pending_schedule_v1';
const SCHEDULE_KEY='uon-v7-schedule',TASKS_KEY='uon_student_tasks_v61',STUDY_KEY='uon_study_sessions_v62';
function uuid(){try{return crypto.randomUUID()}catch{return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}}
function getSessionId(){let id=sessionStorage.getItem(sessionKey)||'';if(!/^[0-9a-f-]{36}$/i.test(id)){id=uuid();sessionStorage.setItem(sessionKey,id)}return id}
function getClientToken(){let id='';try{id=localStorage.getItem(clientKey)||''}catch{}if(!/^[0-9a-f-]{36}$/i.test(id)){id=uuid();try{localStorage.setItem(clientKey,id)}catch{}}return id}
const sessionId=getSessionId(),clientToken=getClientToken();
const lang=()=>localStorage.getItem('uon_language')==='en'?'en':'ar',t=(ar,en)=>lang()==='en'?en:ar;
const cleanText=value=>String(value??'').replace(/^#{1,6}\s*/gm,'').replace(/\*\*(.*?)\*\*/g,'$1').replace(/__(.*?)__/g,'$1').trim();
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function escText(value){return String(value??'').replace(/[<>]/g,'')}
function minutes(value){const m=/^(\d{1,2}):(\d{2})$/.exec(String(value||''));return m?Number(m[1])*60+Number(m[2]):0}
function time(total){const hour24=Math.floor(total/60),minute=String(total%60).padStart(2,'0'),hour12=hour24%12||12;return `${hour12}:${minute} ${hour24<12?'ص':'م'}`}
function muscatInfo(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Muscat',weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));const day={Sun:'الأحد',Mon:'الاثنين',Tue:'الثلاثاء',Wed:'الأربعاء',Thu:'الخميس',Fri:'الجمعة',Sat:'السبت'}[map.weekday]||'';return {day,date:`${map.year}-${map.month}-${map.day}`,minutes:(Number(map.hour)||0)*60+(Number(map.minute)||0)}}
function scheduleRowsLocal(){const rows=readJson(SCHEDULE_KEY,[]);return Array.isArray(rows)?rows.filter(r=>r?.day&&r?.course):[]}
function tasksLocal(){const rows=readJson(TASKS_KEY,[]);return Array.isArray(rows)?rows.filter(r=>r&&!r.done):[]}
function studyLocal(){const rows=readJson(STUDY_KEY,[]);return Array.isArray(rows)?rows.filter(Boolean):[]}
function todayClasses(){const now=muscatInfo();return scheduleRowsLocal().filter(r=>r.day===now.day).map(r=>({...r,startMin:minutes(r.start),endMin:minutes(r.end)})).filter(r=>r.endMin>r.startMin).sort((a,b)=>a.startMin-b.startMin)}
function nextTaskLocal(){return tasksLocal().slice().sort((a,b)=>{if(!a.due&&!b.due)return 0;if(!a.due)return 1;if(!b.due)return-1;return new Date(a.due)-new Date(b.due)})[0]||null}
function formatDue(task){if(!task?.due)return 'بدون موعد';try{return new Intl.DateTimeFormat('ar-OM',{timeZone:'Asia/Muscat',weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(task.due))}catch{return 'موعد غير معروف'}}
function studyTodayMinutes(){const today=muscatInfo().date;return studyLocal().filter(r=>r.date===today).reduce((sum,r)=>sum+(Number(r.duration_minutes)||0),0)}
function normalizeQ(q){return String(q||'').trim().toLowerCase().replace(/[؟?!.,،]/g,' ').replace(/\s+/g,' ')}
function localSmartAnswer(question){
 const q=normalizeQ(question),now=muscatInfo(),classes=todayClasses(),tasks=tasksLocal();
 if(/(وش|ايش|ما|ماذا).*(عندي|جدولي).*(اليوم)|محاضراتي اليوم|جدولي اليوم/.test(q)){
  if(!classes.length)return {answer:`اليوم ${now.day} ما عندك محاضرات محفوظة في جدول UON Hub. تقدر تستغل اليوم للمهام أو Focus.`,actions:[['فتح الجدول','schedule.html'],['ابدأ Focus','study-focus.html']]};
  const lines=classes.map((r,i)=>`${i+1}) ${escText(r.course)} — ${time(r.startMin)} إلى ${time(r.endMin)}${r.room?` — القاعة ${escText(r.room)}`:''}`);
  const current=classes.find(r=>r.startMin<=now.minutes&&r.endMin>now.minutes),next=classes.find(r=>r.startMin>now.minutes);
  const pulse=current?`\n\nالحين عندك ${current.course} إلى ${time(current.endMin)}.`:next?`\n\nأقرب محاضرة ${next.course} الساعة ${time(next.startMin)}.`:'\n\nخلصت محاضرات اليوم ✅';
  return {answer:`جدولك اليوم ${now.day}:\n${lines.join('\n')}${pulse}`,actions:[['فتح الجدول','schedule.html'],['Focus','study-focus.html']]};
 }
 if(/(وش|ايش|ما).*(مهم|واجب|تسليم)|مهامي|واجباتي|تسليماتي|أقرب مهمة|اقرب مهمة/.test(q)){
  if(!tasks.length)return {answer:'ما عندك مهام مفتوحة محفوظة حاليًا 🎉',actions:[['فتح مهامي','tasks.html'],['إضافة مهمة','tasks.html']]};
  const next=nextTaskLocal();const top=tasks.slice().sort((a,b)=>{if(!a.due)return 1;if(!b.due)return-1;return new Date(a.due)-new Date(b.due)}).slice(0,5);
  const lines=top.map((r,i)=>`${i+1}) ${escText(r.title)}${r.course?` — ${escText(r.course)}`:''} — ${formatDue(r)}`);
  return {answer:`عندك ${tasks.length} مهام مفتوحة.${next?` أقربها: ${escText(next.title)} (${formatDue(next)}).`:''}\n\n${lines.join('\n')}`,actions:[['فتح مهامي','tasks.html'],['خطط يومي','assistant.html?prompt='+encodeURIComponent('خطط لي يومي حسب جدولي ومهامي')]]};
 }
 if(/خطط.*يومي|خطة اليوم|نظم.*يومي|رتب.*يومي/.test(q)){
  const next=nextTaskLocal(),todayStudy=studyTodayMinutes();const free=[];let cursor=8*60;for(const r of classes){if(r.startMin-cursor>=45)free.push([cursor,r.startMin]);cursor=Math.max(cursor,r.endMin)}if(18*60-cursor>=45)free.push([cursor,18*60]);
  const parts=[];if(classes.length)parts.push(`عندك ${classes.length} محاضرات اليوم من ${time(classes[0].startMin)} إلى ${time(classes.at(-1).endMin)}.`);else parts.push('ما عندك محاضرات محفوظة اليوم.');if(next)parts.push(`أولوية المهام: ${escText(next.title)}${next.course?` (${escText(next.course)})`:''} — ${formatDue(next)}.`);parts.push(`مذاكرتك المسجلة اليوم: ${todayStudy} دقيقة.`);
  if(free.length){parts.push('\nخطة مقترحة:');free.slice(0,3).forEach((w,i)=>{const len=w[1]-w[0],focus=len>=65?50:25;parts.push(`${i+1}) ${time(w[0])} – ${time(w[1])}: جلسة Focus ${focus} دقيقة${next?.course?` لـ ${escText(next.course)}`:''}.`)})}else parts.push('\nجدولك متقارب اليوم؛ خذ جلسة Focus بعد آخر محاضرة.');
  return {answer:parts.join('\n'),actions:[['فتح الجدول','schedule.html'],['مهامي','tasks.html'],['ابدأ Focus','study-focus.html']]};
 }
 if(/كم.*ذاكرت|مذاكرتي اليوم|وقت مذاكرتي|focus اليوم/.test(q)){
  const total=studyTodayMinutes();return {answer:total?`مسجل عندك اليوم ${total} دقيقة مذاكرة في Focus. ${total>=120?'ممتاز جدًا 🔥':total>=50?'شغل حلو 👏':'تقدر تضيف جلسة ثانية قصيرة.'}`:'ما سجلت جلسة Focus اليوم للحين.',actions:[['فتح Focus','study-focus.html'],['لوحتي','user-dashboard.html']]};
 }
 return null;
}
function addResponseTools(article,question){if(!article||!question)return;const row=document.createElement('div');row.className='assistant-response-tools';const copy=document.createElement('button');copy.type='button';copy.className='assistant-response-tool';copy.innerHTML='⧉ <span>'+t('نسخ','Copy')+'</span>';copy.onclick=async()=>{const text=article.querySelector('.message-content')?.textContent?.trim()||'';if(!text)return;try{await navigator.clipboard.writeText(text);copy.innerHTML='✓ <span>'+t('تم النسخ','Copied')+'</span>'}catch{}};const retry=document.createElement('button');retry.type='button';retry.className='assistant-response-tool';retry.innerHTML='↻ <span>'+t('إعادة الإجابة','Regenerate')+'</span>';retry.onclick=()=>{if(!sending)void submitQuestion(question,{repeat:true})};row.append(copy,retry);article.appendChild(row)}
function addMinimalLink(article,links=[]){const item=Array.isArray(links)?links.find(x=>x?.url):null;if(!article||!item)return;const row=document.createElement('div');row.className='assistant-links assistant-links-minimal';const a=document.createElement('a');a.href=item.url;a.target=/^https?:/i.test(item.url)?'_blank':'_self';a.rel='noopener noreferrer';a.textContent=item.official?t('المصدر الرسمي','Official source'):t('المصدر','Source');row.appendChild(a);article.appendChild(row)}
function addLocalActions(article,actions=[]){if(!article||!actions.length)return;const row=document.createElement('div');row.className='assistant-local-actions';for(const [label,href] of actions){const a=document.createElement('a');a.className='assistant-local-action';a.href=href;a.textContent=label;row.appendChild(a)}article.appendChild(row)}
function addMessage(role,content,links=[]){if(!chat)return null;const article=document.createElement('article');article.className=`message ${role}`;const body=document.createElement('div');body.className='message-content';body.textContent=cleanText(content);article.appendChild(body);if(role==='bot')addMinimalLink(article,links);chat.appendChild(article);chat.scrollTop=chat.scrollHeight;return article}
function addTyping(){const el=document.createElement('article');el.className='message bot typing-message';el.innerHTML='<div class="typing-dots" aria-hidden="true"><span></span><span></span><span></span></div>';chat?.appendChild(el);return el}
function scheduleRows(plan){const courses=plan?.schedule?.courses;if(!Array.isArray(courses))return[];const out=[];for(const c of courses){const meetings=Array.isArray(c.meetings)?c.meetings:(Array.isArray(c.times)?c.times:[]);for(const m of meetings)out.push({course:c.course_code||c.course||'',day:m.day_name||m.day||'',start:String(m.start_time||m.start||'').slice(0,5),end:String(m.end_time||m.end||'').slice(0,5),room:m.room||c.room||'',teacher:m.instructor||c.instructor||'',type:'lecture'})}return out.filter(x=>x.course&&x.day&&x.start&&x.end)}
function attachPlanAction(article,result){if(!article||result?.mode!=='semester_planner'||result?.semester_plan?.status!=='ready')return;const rows=scheduleRows(result.semester_plan);if(!rows.length)return;const row=document.createElement('div');row.className='assistant-response-tools';const b=document.createElement('button');b.type='button';b.className='assistant-response-tool';b.textContent=t('أضف هذا الجدول','Apply this schedule');b.onclick=()=>{try{sessionStorage.setItem(planKey,JSON.stringify({term:result.semester_plan.term,rows,created_at:Date.now()}));location.href='/schedule.html?from=ai'}catch{b.textContent=t('تعذر إضافة الجدول','Could not apply')}};row.appendChild(b);article.appendChild(row)}
async function ask(question,signal,regenerate=false){const response=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,history:history.slice(-12),language:lang(),page_context:location.pathname,session_id:sessionId,client_token:clientToken,channel:'web',regenerate:Boolean(regenerate)}),cache:'no-store',signal});const data=await response.json().catch(()=>({}));if(!response.ok||!data.answer)throw new Error(data.error||`AI HTTP ${response.status}`);return data}
async function sendFeedback(result,question,rating){if(!result?.request_id)return false;return(await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'feedback',request_id:result.request_id,rating,question,answer:result.answer})})).ok}
function attachFeedback(article,question,result){if(!article||!result?.request_id)return;const row=document.createElement('div');row.className='assistant-feedback';const label=document.createElement('span');label.textContent=t('هل أفادك الرد؟','Was this helpful?');row.appendChild(label);[-1,1].forEach(rating=>{const b=document.createElement('button');b.type='button';b.className='assistant-feedback-btn';b.textContent=rating===1?'👍':'👎';b.onclick=async()=>{if(row.dataset.sent)return;row.dataset.sent='1';try{await sendFeedback(result,question,rating);label.textContent=t('وصلت 👍','Got it 👍')}catch{row.dataset.sent=''}};row.appendChild(b)});article.appendChild(row)}
function setSendingState(active){sending=active;if(submitButton){submitButton.disabled=active;submitButton.hidden=active}const stop=$('#assistantStop');if(stop)stop.hidden=!active}
function renderDeviceContext(){const aside=document.querySelector('.v175-ai-info');if(!aside||document.querySelector('#assistantDeviceContext'))return;const classes=todayClasses(),next=nextTaskLocal(),study=studyTodayMinutes();const box=document.createElement('section');box.id='assistantDeviceContext';box.className='assistant-device-context';box.innerHTML=`<span class="assistant-device-label">على جهازك فقط</span><h3>سياقك اليوم</h3><div class="assistant-device-grid"><button type="button" data-local-prompt="وش عندي اليوم؟"><span>🎓</span><strong>${classes.length}</strong><small>محاضرات اليوم</small></button><button type="button" data-local-prompt="وش أقرب مهمة عندي؟"><span>✅</span><strong>${tasksLocal().length}</strong><small>${next?'مهام مفتوحة':'ما عندك مهام'}</small></button><button type="button" data-local-prompt="كم ذاكرت اليوم؟"><span>⏱️</span><strong>${study}د</strong><small>مذاكرة اليوم</small></button></div><button class="assistant-plan-day" type="button" data-local-prompt="خطط لي يومي حسب جدولي ومهامي">✨ خطط لي يومي</button><p>هذه البيانات تُقرأ محليًا ولا تُرسل للسيرفر عند استخدام الأوامر أعلاه.</p>`;aside.appendChild(box);box.querySelectorAll('[data-local-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.localPrompt||'';void submitQuestion(input.value)}))}
async function submitQuestion(question,opts={}){if(sending||!question)return;lastQuestion=question;setSendingState(true);if(!opts.repeat){addMessage('user',question);history.push({role:'user',content:question});input.value=''}const local=localSmartAnswer(question);if(local&&!opts.repeat){const article=addMessage('bot',local.answer);history.push({role:'assistant',content:local.answer});addLocalActions(article,local.actions||[]);addResponseTools(article,question);setSendingState(false);renderDeviceContext();input?.focus();try{trackEvent('assistant_local_answer',{type:normalizeQ(question).slice(0,80)})}catch{}return}const typing=addTyping();currentController=new AbortController();const timer=setTimeout(()=>currentController?.abort(),30000);try{const result=await ask(question,currentController.signal,Boolean(opts.repeat));typing.remove();const article=addMessage('bot',result.answer,result.links||[]);history.push({role:'assistant',content:result.answer});attachPlanAction(article,result);attachFeedback(article,question,result);addResponseTools(article,question)}catch{typing.remove();addMessage('bot',t('تعذر الوصول إلى UON AI الآن. جرّب مرة أخرى بعد قليل.','UON AI is unavailable right now. Try again shortly.'))}finally{clearTimeout(timer);currentController=null;setSendingState(false);input?.focus()}}
function handleSubmit(e){e?.preventDefault();const q=input?.value?.trim()||'';if(q)void submitQuestion(q);return false}
if(form){form.action='javascript:void(0)';form.addEventListener('submit',handleSubmit,true)}input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handleSubmit(e)}});$('#assistantStop')?.addEventListener('click',()=>currentController?.abort());document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt||b.textContent.trim();input.focus()}));
async function initialize(){try{await enforceUonMaintenance()}catch{}try{watchUonMaintenance()}catch{}try{await applyFeatureStates(document)}catch{}try{trackEvent('page_view',{page:'assistant-v63'})}catch{}renderDeviceContext();const prompt=new URLSearchParams(location.search).get('prompt')?.trim();if(prompt){input.value=prompt;history.length===0&&setTimeout(()=>void submitQuestion(prompt),120)}}
initialize();
