import{toast,trackEvent,uid}from'./core.js?v=42.0.0';
const ignore=['admin.html','owner-dashboard.html','maintenance.html','offline.html','404.html','reset.html'];
if(!ignore.some(x=>location.pathname.endsWith(x))){
 const sessionKey='uon_report_session_v42';let session=localStorage.getItem(sessionKey);if(!session){session=uid();localStorage.setItem(sessionKey,session)}
 const button=document.createElement('button');button.className='content-report-fab';button.type='button';button.textContent='⚑ بلاغ';button.title='الإبلاغ عن محتوى أو مشكلة';document.body.appendChild(button);
 const wrap=document.createElement('div');wrap.className='modal';wrap.id='contentReportModal';wrap.innerHTML=`<div class="card modal-card"><div class="section-head"><div><h2>الإبلاغ عن محتوى</h2><p class="muted">حدد المشكلة حتى تصل للمشرف الصحيح بسرعة.</p></div><button class="icon-btn" id="closeContentReport">✕</button></div><form id="contentReportForm" class="form-grid"><div class="field"><label>نوع البلاغ</label><select name="reason" required><option value="">اختر</option><option value="broken_link">رابط لا يعمل</option><option value="incorrect">معلومة أو تصنيف خاطئ</option><option value="outdated">محتوى قديم</option><option value="duplicate">محتوى مكرر</option><option value="missing">محتوى ناقص</option><option value="inappropriate">محتوى غير مناسب</option><option value="privacy">بيانات شخصية</option><option value="other">أخرى</option></select></div><div class="field"><label>الأولوية</label><select name="priority"><option value="normal">عادية</option><option value="high">مهمة</option><option value="urgent">عاجلة — خصوصية أو ضرر</option><option value="low">منخفضة</option></select></div><div class="field"><label>رمز المقرر — اختياري</label><input name="course_code" maxlength="20" placeholder="STAT101"></div><div class="field"><label>عنوان المحتوى — اختياري</label><input name="content_title" maxlength="180"></div><div class="field wide"><label>التفاصيل</label><textarea name="details" rows="5" maxlength="1200" minlength="5" required placeholder="اشرح المشكلة ومكانها بدقة"></textarea></div><div class="field wide"><label>وسيلة تواصل — اختيارية</label><input name="contact" maxlength="160" placeholder="بريد أو رقم إذا تحتاج ردًا"></div><button class="btn primary field wide" type="submit">إرسال للمراجعة</button></form></div>`;document.body.appendChild(wrap);
 const close=()=>wrap.classList.remove('open');button.onclick=()=>wrap.classList.add('open');wrap.querySelector('#closeContentReport').onclick=close;wrap.addEventListener('click',event=>{if(event.target===wrap)close()});
 document.addEventListener('click',event=>{const source=event.target.closest('[data-report-table]');if(!source)return;event.preventDefault();wrap.querySelector('[name="content_title"]').value=source.dataset.reportTitle||'';wrap.dataset.sourceTable=source.dataset.reportTable||'';wrap.dataset.sourceId=source.dataset.reportId||'';wrap.dataset.sourceUrl=source.dataset.reportUrl||'';wrap.classList.add('open')});
 wrap.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,submit=form.querySelector('button[type="submit"]');const body=Object.fromEntries(new FormData(form));body.page_url=location.href;body.page_title=document.title;body.status='pending';body.session_id=session;body.language=document.documentElement.lang||'ar';body.viewport=`${innerWidth}x${innerHeight}`;body.online=navigator.onLine;body.source_table=wrap.dataset.sourceTable||null;body.source_id=wrap.dataset.sourceId||null;body.source_url=wrap.dataset.sourceUrl||null;if(body.course_code)body.course_code=String(body.course_code).toUpperCase().replace(/\s+/g,'');try{submit.disabled=true;submit.textContent='جاري الإرسال...';const response=await fetch('https://irkhvydgxpseflggbeqq.supabase.co/functions/v1/content-report-submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok||payload.ok===false)throw new Error(payload.error||'report_submit_failed');trackEvent('content_report_v42',{reason:body.reason,priority:body.priority,page:location.pathname});toast(payload.duplicate?'هذا البلاغ وصل مسبقًا للمراجعة':'وصل البلاغ للمراجعة، شكرًا لك');form.reset();wrap.dataset.sourceTable='';wrap.dataset.sourceId='';wrap.dataset.sourceUrl='';close()}catch(error){console.error(error);toast('تعذر إرسال البلاغ، حاول مرة أخرى',true)}finally{submit.disabled=false;submit.textContent='إرسال للمراجعة'}};
}
