import {checkFeature,whatsappShare,installErrorCapture,$,get,esc,enforceUonMaintenance,watchUonMaintenance,trackEvent,debounce} from './core.js';
await enforceUonMaintenance();watchUonMaintenance();installErrorCapture();
const featureState=await checkFeature('courses');if(featureState!=='active')throw new Error('COURSES_FEATURE_DISABLED');
const lang=()=>localStorage.getItem('uon_language')||'ar';
const state={rows:[],colleges:[],departments:[],programs:[],links:[],query:'',college:'',department:'',program:'',sort:'code',view:localStorage.getItem('uon_course_view')||'grid'};
const tr=(ar,en)=>lang()==='ar'?ar:en; const norm=v=>String(v||'').trim().toLowerCase(); const byOrder=(a,b)=>(a.sort_order||100)-(b.sort_order||100)||String(lang()==='ar'?a.name_ar:a.name_en).localeCompare(String(lang()==='ar'?b.name_ar:b.name_en),lang());
function opts(rows,label){return `<option value="">${label}</option>`+rows.map(x=>`<option value="${esc(x.id||x.name_ar)}">${esc(lang()==='ar'?x.name_ar:x.name_en)}</option>`).join('')}
function refresh(){const ds=state.departments.filter(x=>!state.college||x.college_id===state.college).sort(byOrder);$('#courseDepartment').innerHTML=opts(ds,tr('كل الأقسام','All departments'));if(!ds.some(x=>x.id===state.department))state.department='';const ps=state.programs.filter(x=>(!state.college||x.college_id===state.college)&&(!state.department||x.department_id===state.department)).sort(byOrder);$('#courseProgram').innerHTML=opts(ps,tr('كل التخصصات','All programs'));if(!ps.some(x=>x.id===state.program))state.program=''}
function filtered(){const codes=state.program?new Set(state.links.filter(x=>x.program_id===state.program).map(x=>x.course_code)):null,q=norm(state.query);return state.rows.filter(r=>(!q||norm([r.code,r.name_ar,r.name_en,r.college_ar,r.college_en,r.department_ar,r.department_en].join(' ')).includes(q))&&(!state.college||state.colleges.find(c=>c.id===state.college)?.name_ar===(r.college_ar||r.college))&&(!state.department||state.departments.find(d=>d.id===state.department)?.name_ar===(r.department_ar||r.department))&&(!codes||codes.has(r.code))).sort((a,b)=>state.sort==='name'?String(lang()==='ar'?a.name_ar:a.name_en).localeCompare(String(lang()==='ar'?b.name_ar:b.name_en),lang()):state.sort==='hours'?Number(b.credit_hours||0)-Number(a.credit_hours||0):String(a.code).localeCompare(String(b.code),'en'))}
function render(){const list=filtered();$('#courseCount').textContent=tr(`${list.length} مقرر`,`${list.length} courses`);$('#courseCards').innerHTML=list.length?list.map(r=>{const url=`course.html?code=${encodeURIComponent(r.code)}`,name=lang()==='ar'?(r.name_ar||r.name_en):(r.name_en||r.name_ar),college=lang()==='ar'?(r.college_ar||r.college):(r.college_en||r.college_ar||r.college);return `<article class="v31-course-card"><a href="${url}"><div class="v31-course-card-head"><span class="v31-course-code">${esc(r.code)}</span><span class="v31-course-hours">${r.credit_hours||'—'} ${tr('ساعات','credits')}</span></div><span class="v31-course-college">${esc(college||tr('جامعة نزوى','University of Nizwa'))}</span><h2>${esc(name||r.code)}</h2><p>${esc(tr(r.department_ar||r.department||'',r.department_en||r.department_ar||''))}</p></a><footer><a class="btn primary" href="${url}">${tr('فتح المقرر','Open course')}</a></footer></article>`}).join(''):`<div class="course-empty"><strong>${tr('ما حصلنا مقررات مطابقة','No matching courses')}</strong></div>`}
async function load(){[state.rows,state.colleges,state.departments,state.programs,state.links]=await Promise.all([get('courses','select=*&active=eq.true&order=code.asc'),get('academic_colleges','select=*&active=eq.true&order=sort_order.asc'),get('academic_departments','select=*&active=eq.true&order=sort_order.asc'),get('academic_programs','select=*&active=eq.true&order=sort_order.asc'),get('course_programs','select=course_code,program_id,requirement_type')]);$('#courseCollege').innerHTML=opts(state.colleges.sort(byOrder),tr('كل الكليات','All colleges'));refresh();render();trackEvent('page_view',{page:'courses',count:state.rows.length})}
$('#courseSearch').addEventListener('input',debounce(e=>{state.query=e.target.value;render()},180));$('#courseCollege').addEventListener('change',e=>{state.college=e.target.value;refresh();render()});$('#courseDepartment').addEventListener('change',e=>{state.department=e.target.value;refresh();render()});$('#courseProgram').addEventListener('change',e=>{state.program=e.target.value;render()});$('#courseSort').addEventListener('change',e=>{state.sort=e.target.value;render()});load().catch(e=>{$('#courseCards').innerHTML=`<div class="course-empty"><strong>${esc(e.message)}</strong></div>`});
