import {checkFeature,whatsappShare,installErrorCapture,$,get,esc,enforceUonMaintenance,watchUonMaintenance,trackEvent,debounce} from './core.js';
await enforceUonMaintenance();watchUonMaintenance();installErrorCapture();
const featureState=await checkFeature('courses');
if(featureState!=='active'){document.querySelector('main').innerHTML=`<section class="page-hero"><div class="container"><h1>مركز المقررات</h1><p>${featureState==='maintenance'?'الخدمة تحت الصيانة حاليًا':featureState==='coming_soon'?'الخدمة قادمة قريبًا':'الخدمة متوقفة حاليًا'}</p></div></section>`;throw new Error('COURSES_FEATURE_DISABLED')}
const state={rows:[],query:'',college:'',department:'',sort:'code',view:localStorage.getItem('uon_course_view')||'grid'};
const normalize=value=>String(value||'').trim().toLocaleLowerCase('ar');
const unique=values=>[...new Set(values.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ar'));
function optionList(values,label){return `<option value="">${label}</option>`+values.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('')}
function applyView(){const list=state.view==='list';$('#courseCards')?.classList.toggle('list-view',list);$('#gridView')?.classList.toggle('active',!list);$('#listView')?.classList.toggle('active',list)}
function filteredRows(){const q=normalize(state.query);const rows=state.rows.filter(row=>{const haystack=normalize([row.code,row.name_ar,row.name_en,row.college,row.department,row.description].join(' '));return(!q||haystack.includes(q))&&(!state.college||row.college===state.college)&&(!state.department||row.department===state.department)});return rows.sort((a,b)=>state.sort==='name'?String(a.name_ar||'').localeCompare(String(b.name_ar||''),'ar'):state.sort==='hours'?Number(b.credit_hours||0)-Number(a.credit_hours||0):String(a.code||'').localeCompare(String(b.code||''),'en'))}
function render(){const list=filteredRows();$('#courseCount').textContent=`${list.length.toLocaleString('ar')} مقرر`;$('#courseHint').textContent=state.query?' — نتائج البحث الحالية':'';$('#courseCards').innerHTML=list.length?list.map(row=>{const url=`course.html?code=${encodeURIComponent(row.code)}`;return `<article class="v31-course-card"><a href="${url}"><div class="v31-course-card-head"><span class="v31-course-code">${esc(row.code)}</span><span class="v31-course-hours">${Number(row.credit_hours||0)||'—'} ساعات</span></div><span class="v31-course-college">${esc(row.college||'جامعة نزوى')}</span><h2>${esc(row.name_ar||row.name_en||'مقرر بدون اسم')}</h2><p>${esc(row.description||row.department||'افتح صفحة المقرر للاطلاع على مواده ومصادره.')}</p></a><footer><a class="btn primary" href="${url}">فتح المقرر</a><a class="btn" target="_blank" rel="noopener" href="${whatsappShare(`${row.code} — ${row.name_ar||row.name_en}`,`${location.origin}/${url}`)}">مشاركة</a></footer></article>`}).join(''):`<div class="course-empty"><strong>ما حصلنا مقررات مطابقة</strong><span>جرّب رمزًا أقصر أو غيّر الكلية والقسم.</span></div>`;applyView()}
async function load(){try{state.rows=await get('courses','select=*&active=eq.true&order=code.asc');$('#courseCollege').innerHTML=optionList(unique(state.rows.map(row=>row.college)),'كل الكليات');refreshDepartments();render();trackEvent('page_view',{page:'courses',count:state.rows.length})}catch(error){$('#courseCards').innerHTML=`<div class="course-empty"><strong>تعذر تحميل المقررات</strong><span>${esc(error.message)}</span><br><button class="btn primary" id="retryCourses">إعادة المحاولة</button></div>`;$('#courseCount').textContent='حدث خطأ';$('#retryCourses')?.addEventListener('click',load)}}
function refreshDepartments(){const rows=state.college?state.rows.filter(row=>row.college===state.college):state.rows;const departments=unique(rows.map(row=>row.department));$('#courseDepartment').innerHTML=optionList(departments,'كل الأقسام');if(!departments.includes(state.department))state.department=''}
$('#courseSearch').addEventListener('input',debounce(event=>{state.query=event.target.value;render()},180));$('#courseCollege').addEventListener('change',event=>{state.college=event.target.value;refreshDepartments();render()});$('#courseDepartment').addEventListener('change',event=>{state.department=event.target.value;render()});$('#courseSort').addEventListener('change',event=>{state.sort=event.target.value;render()});$('#gridView').addEventListener('click',()=>{state.view='grid';localStorage.setItem('uon_course_view',state.view);applyView()});$('#listView').addEventListener('click',()=>{state.view='list';localStorage.setItem('uon_course_view',state.view);applyView()});load();
