import {checkFeature,installErrorCapture,$,get,esc,enforceUonMaintenance,watchUonMaintenance,trackEvent,debounce} from './core.js';
await enforceUonMaintenance();watchUonMaintenance();installErrorCapture();
const featureState=await checkFeature('courses');if(featureState!=='active')throw new Error('COURSES_FEATURE_DISABLED');
const lang=()=>localStorage.getItem('uon_language')||'ar';
const state={rows:[],colleges:[],departments:[],programs:[],links:[],query:'',college:'',department:'',program:'',sort:'code',view:localStorage.getItem('uon_course_view')||'grid'};
const tr=(ar,en)=>lang()==='ar'?ar:en;
const norm=v=>String(v||'').trim().toLowerCase();
const first=(obj,keys)=>{for(const key of keys){const value=obj?.[key];if(value!==undefined&&value!==null&&String(value).trim()!=='')return String(value).trim()}return''};
const collegeName=r=>first(r,['college_ar','college','college_name_ar','college_name']);
const departmentName=r=>first(r,['department_ar','department','department_name_ar','department_name']);
const programName=r=>first(r,['program_ar','program','major_ar','major','specialization_ar','specialization']);
const byOrder=(a,b)=>(a.sort_order||100)-(b.sort_order||100)||String(lang()==='ar'?(a.name_ar||a.name):(a.name_en||a.name_ar||a.name)).localeCompare(String(lang()==='ar'?(b.name_ar||b.name):(b.name_en||b.name_ar||b.name)),lang());
const uniqueRows=(rows,nameGetter,parentGetter)=>{const map=new Map();rows.forEach(r=>{const name=nameGetter(r);if(!name)return;const parent=parentGetter?parentGetter(r):'';const key=`${parent}::${name}`;if(!map.has(key))map.set(key,{id:name,name_ar:name,name_en:first(r,[name==='college'?'college_en':'name_en'])||name,college_id:parent,department_id:parent})});return [...map.values()]};
function opts(rows,label){return `<option value="">${label}</option>`+rows.map(x=>`<option value="${esc(x.id||x.name_ar||x.name)}">${esc(lang()==='ar'?(x.name_ar||x.name):(x.name_en||x.name_ar||x.name))}</option>`).join('')}
function selectedCollegeName(){return state.colleges.find(c=>String(c.id||c.name_ar)===state.college)?.name_ar||state.college}
function selectedDepartmentName(){return state.departments.find(d=>String(d.id||d.name_ar)===state.department)?.name_ar||state.department}
function refresh(){const college=selectedCollegeName();const ds=state.departments.filter(x=>!state.college||String(x.college_id||x.college||'')===state.college||String(x.college_name_ar||'')===college).sort(byOrder);$('#courseDepartment').innerHTML=opts(ds,tr('كل الأقسام','All departments'));if(state.department&&!ds.some(x=>String(x.id||x.name_ar)===state.department))state.department='';const department=selectedDepartmentName();const ps=state.programs.filter(x=>(!state.college||String(x.college_id||x.college||'')===state.college||String(x.college_name_ar||'')===college)&&(!state.department||String(x.department_id||x.department||'')===state.department||String(x.department_name_ar||'')===department)).sort(byOrder);$('#courseProgram').innerHTML=opts(ps,tr('كل التخصصات','All programs'));if(state.program&&!ps.some(x=>String(x.id||x.name_ar)===state.program))state.program=''}
function filtered(){const college=selectedCollegeName(),department=selectedDepartmentName();const selectedProgram=state.programs.find(p=>String(p.id||p.name_ar)===state.program)?.name_ar||state.program;const linkedCodes=state.program?new Set(state.links.filter(x=>String(x.program_id)===state.program).map(x=>String(x.course_code||'').toUpperCase())):null;const q=norm(state.query);return state.rows.filter(r=>{const code=String(r.code||r.course_code||'').toUpperCase();const programMatches=!state.program||linkedCodes?.has(code)||programName(r)===selectedProgram;return(!q||norm([code,r.name_ar,r.name_en,collegeName(r),r.college_en,departmentName(r),r.department_en,programName(r)].join(' ')).includes(q))&&(!state.college||collegeName(r)===college)&&(!state.department||departmentName(r)===department)&&programMatches}).sort((a,b)=>state.sort==='name'?String(lang()==='ar'?a.name_ar:a.name_en).localeCompare(String(lang()==='ar'?b.name_ar:b.name_en),lang()):state.sort==='hours'?Number(b.credit_hours||b.hours||0)-Number(a.credit_hours||a.hours||0):String(a.code||a.course_code).localeCompare(String(b.code||b.course_code),'en'))}
function render(){const list=filtered();$('#courseCount').textContent=tr(`${list.length} مقرر`,`${list.length} courses`);$('#courseHint').textContent=state.rows.length?tr(`من أصل ${state.rows.length}`,`of ${state.rows.length}`):'';$('#courseCards').innerHTML=list.length?list.map(r=>{const code=r.code||r.course_code||'',url=`course.html?code=${encodeURIComponent(code)}`,name=lang()==='ar'?(r.name_ar||r.name_en):(r.name_en||r.name_ar),college=lang()==='ar'?collegeName(r):(r.college_en||collegeName(r));return `<article class="v31-course-card"><a href="${url}"><div class="v31-course-card-head"><span class="v31-course-code">${esc(code)}</span><span class="v31-course-hours">${r.credit_hours||r.hours||'—'} ${tr('ساعات','credits')}</span></div><span class="v31-course-college">${esc(college||tr('جامعة نزوى','University of Nizwa'))}</span><h2>${esc(name||code)}</h2><p>${esc(lang()==='ar'?departmentName(r):(r.department_en||departmentName(r)))}</p></a><footer><a class="btn primary" href="${url}">${tr('فتح المقرر','Open course')}</a></footer></article>`}).join(''):`<div class="course-empty"><strong>${tr('ما حصلنا مقررات مطابقة','No matching courses')}</strong></div>`}
async function safeGet(table,query='select=*'){try{const result=await get(table,query);return Array.isArray(result)?result:[]}catch(error){console.warn(`[courses] ${table}`,error);return[]}}
async function load(){state.rows=await safeGet('courses','select=*&order=code.asc');const [colleges,departments,programs,links]=await Promise.all([safeGet('academic_colleges','select=*&order=sort_order.asc'),safeGet('academic_departments','select=*&order=sort_order.asc'),safeGet('academic_programs','select=*&order=sort_order.asc'),safeGet('course_programs','select=course_code,program_id,requirement_type')]);state.rows=state.rows.filter(r=>r.active!==false&&r.status!=='inactive');state.colleges=colleges.filter(x=>x.active!==false);state.departments=departments.filter(x=>x.active!==false);state.programs=programs.filter(x=>x.active!==false);state.links=links;
if(!state.colleges.length)state.colleges=uniqueRows(state.rows,collegeName);
if(!state.departments.length){const map=new Map();state.rows.forEach(r=>{const name=departmentName(r),college=collegeName(r);if(name&&!map.has(`${college}::${name}`))map.set(`${college}::${name}`,{id:name,name_ar:name,name_en:r.department_en||name,college_id:college,college_name_ar:college})});state.departments=[...map.values()]}
if(!state.programs.length){const map=new Map();state.rows.forEach(r=>{const name=programName(r),college=collegeName(r),department=departmentName(r);if(name&&!map.has(`${college}::${department}::${name}`))map.set(`${college}::${department}::${name}`,{id:name,name_ar:name,name_en:r.program_en||r.major_en||name,college_id:college,college_name_ar:college,department_id:department,department_name_ar:department})});state.programs=[...map.values()]}
$('#courseCollege').innerHTML=opts(state.colleges.sort(byOrder),tr('كل الكليات','All colleges'));refresh();render();trackEvent('page_view',{page:'courses',count:state.rows.length})}
$('#courseSearch').addEventListener('input',debounce(e=>{state.query=e.target.value;render()},180));$('#courseCollege').addEventListener('change',e=>{state.college=e.target.value;state.department='';state.program='';refresh();render()});$('#courseDepartment').addEventListener('change',e=>{state.department=e.target.value;state.program='';refresh();render()});$('#courseProgram').addEventListener('change',e=>{state.program=e.target.value;render()});$('#courseSort').addEventListener('change',e=>{state.sort=e.target.value;render()});load().catch(e=>{$('#courseCount').textContent=tr('تعذر تحميل المقررات','Could not load courses');$('#courseCards').innerHTML=`<div class="course-empty"><strong>${esc(e.message)}</strong></div>`});
