
import {get,insert,notifyPending} from './api.js';import {$,esc,toast,setupNav} from './ui.js';import {initI18n} from './i18n.js';
setupNav();initI18n();let rows=[];
function card(p){return `<article class="card item-card"><div class="item-image" style="background-image:url('${esc(p.image_url||'')}')"></div><div class="item-body"><span class="badge">${p.featured?'مميز ⭐':esc(p.major||'مشروع')}</span><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="meta"><span class="badge">${esc(p.owner_name||'')}</span></div><div class="actions">${p.github_url?`<a href="${esc(p.github_url)}" target="_blank">GitHub</a>`:''}${p.demo_url?`<a href="${esc(p.demo_url)}" target="_blank">عرض المشروع</a>`:''}</div></div></article>`}
function render(){const q=$('#search').value.toLowerCase();const list=rows.filter(x=>`${x.title||''} ${x.description||''} ${x.major||''}`.toLowerCase().includes(q));$('#grid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">لا توجد مشاريع</div>';const f=rows.find(x=>x.featured);if(f){$('#featured').hidden=false;$('#featured').innerHTML=`<div><span class="badge">مشروع مميز ⭐</span><h2>${esc(f.title)}</h2><p>${esc(f.description)}</p></div><div class="featured-image" style="background-image:url('${esc(f.image_url||'')}')"></div>`}}
async function load(){try{rows=await get('student_projects','select=*&status=eq.approved&order=featured.desc,created_at.desc');render()}catch(e){toast(e.message,true)}}
window.openSubmit=()=>$('#modal').classList.add('show');window.closeSubmit=()=>$('#modal').classList.remove('show');
window.submitProject=async()=>{const body={title:$('#pTitle').value.trim(),owner_name:$('#pOwner').value.trim(),major:$('#pMajor').value.trim(),description:$('#pDescription').value.trim(),github_url:$('#pGithub').value.trim()||null,demo_url:$('#pDemo').value.trim()||null,image_url:$('#pImage').value.trim()||null,contact:$('#pContact').value.trim(),status:'pending',featured:false};if(!body.title||!body.owner_name||!body.description||!body.contact)return toast('أكمل الحقول المطلوبة',true);try{const created=await insert('student_projects',body);await notifyPending('student_projects',created?.[0]?.id);toast('تم الإرسال للمراجعة');closeSubmit()}catch(e){toast(e.message,true)}};
$('#search').addEventListener('input',render);load();
