import {setupNav,enforceUonMaintenance,watchUonMaintenance,$,toast,esc,uid} from './core.js?v=43.1.0';

setupNav();
await enforceUonMaintenance();
watchUonMaintenance();

const STORAGE_KEY='uon-v7-schedule';
const EXPORT_FORMAT='uonhub-schedule';
const days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس'];
const dayNames={'الأحد':{ar:'الأحد',en:'Sunday'},'الاثنين':{ar:'الاثنين',en:'Monday'},'الثلاثاء':{ar:'الثلاثاء',en:'Tuesday'},'الأربعاء':{ar:'الأربعاء',en:'Wednesday'},'الخميس':{ar:'الخميس',en:'Thursday'}};
const typeNames={lecture:{ar:'محاضرة',en:'Lecture'},lab:{ar:'مختبر / عملي',en:'Lab / Practical'},tutorial:{ar:'تمارين',en:'Tutorial'},workshop:{ar:'ورشة',en:'Workshop'},other:{ar:'أخرى',en:'Other'}};
const allowedTypes=Object.keys(typeNames),palette=['#22d3ee','#818cf8','#34d399','#fbbf24','#fb7185','#c084fc','#60a5fa','#f97316'];
const form=$('#scheduleForm'),week=$('#week'),courseInput=$('#course'),typeInput=$('#classType'),startInput=$('#start'),startPeriodInput=$('#startPeriod'),endInput=$('#end'),endPeriodInput=$('#endPeriod'),roomInput=$('#room'),teacherInput=$('#teacher'),countElement=$('#scheduleCount'),clearButton=$('#clearSchedule'),submitButton=$('#add'),cancelEditButton=$('#cancelEdit'),editingBadge=$('#editingBadge'),formTitle=$('#scheduleFormTitle'),exportImageButton=$('#exportImage'),printButton=$('#printSchedule'),exportJsonButton=$('#exportJson'),importJsonButton=$('#importJson'),importFileInput=$('#importFile'),dayCheckboxes=Array.from(document.querySelectorAll('input[name="days"]'));
const language=()=>document.documentElement.lang?.toLowerCase().startsWith('en')?'en':'ar',t=(ar,en)=>language()==='en'?en:ar;
function parseTime(value){const m=/^(\d{1,2}):(\d{2})$/.exec(String(value||''));if(!m)return null;const h=Number(m[1]),min=Number(m[2]);return h<0||h>23||min<0||min>59?null:h*60+min}
function clockToMinutes(value,period){const parsed=parseTime(value);if(parsed==null)return null;let hour=Math.floor(parsed/60);const minute=parsed%60;if(hour>12)return parsed;if(hour===0)hour=12;if(period==='pm'&&hour<12)hour+=12;if(period==='am'&&hour===12)hour=0;return hour*60+minute}
function legacyStoredMinutes(value,period){if(period==='am'||period==='pm')return clockToMinutes(value,period);const p=parseTime(value);if(p==null)return null;const h=Math.floor(p/60);return h>=1&&h<=7?p+720:p}
function toTimeValue(total){const s=((Number(total)||0)%1440+1440)%1440;return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function splitClock(total){const s=((Number(total)||0)%1440+1440)%1440,h=Math.floor(s/60),m=s%60;return{value:`${String(h%12||12).padStart(2,'0')}:${String(m).padStart(2,'0')}`,period:h<12?'am':'pm'}}
function formatTime(total){const s=((Number(total)||0)%1440+1440)%1440,h=Math.floor(s/60),m=String(s%60).padStart(2,'0'),h12=h%12||12;return language()==='en'?`${h12}:${m} ${h<12?'AM':'PM'}`:`${h12}:${m} ${h<12?'ص':'م'}`}
function normaliseCourse(value){const c=String(value||'').trim();return/^[a-z]{2,8}\s*\d{2,4}[a-z]?$/i.test(c)?c.toUpperCase().replace(/\s+/g,''):c}
function colourForCourse(course){let h=0;for(const c of String(course||''))h=(h*31+c.charCodeAt(0))>>>0;return palette[h%palette.length]}
function normaliseRows(rawRows){if(!Array.isArray(rawRows))return[];const groups=new Map(),seen=new Set(),out=[];for(const raw of rawRows){if(!raw||!days.includes(raw.day))continue;const course=normaliseCourse(raw.course),sm=legacyStoredMinutes(raw.start,raw.startPeriod),em=legacyStoredMinutes(raw.end,raw.endPeriod);if(!course||sm==null||em==null||em<=sm)continue;const type=allowedTypes.includes(raw.type)?raw.type:'lecture',room=String(raw.room||'').trim(),teacher=String(raw.teacher||'').trim(),key=[course,sm,em,room,teacher,type].join('|');let seriesId=String(raw.seriesId||raw.series_id||'');if(!seriesId){if(!groups.has(key))groups.set(key,uid());seriesId=groups.get(key)}let id=String(raw.id||uid());while(seen.has(id))id=uid();seen.add(id);out.push({id,seriesId,course,day:raw.day,start:toTimeValue(sm),end:toTimeValue(em),room,teacher,type})}return out}
function loadRows(){try{return normaliseRows(JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'))}catch{return[]}}
let rows=loadRows(),editingSeriesId=null;
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(rows))}catch{toast(t('تعذر حفظ الجدول على الجهاز','Could not save schedule'),true)}render()}
function selectedDays(){return dayCheckboxes.filter(i=>i.checked).map(i=>i.value)}function setSelectedDays(v){const s=new Set(v);dayCheckboxes.forEach(i=>i.checked=s.has(i.value))}
function countLabel(){const courses=new Set(rows.map(r=>r.course)).size;return language()==='en'?`${rows.length} classes • ${courses} courses`:`${rows.length} محاضرة • ${courses} مادة`}
function seriesCount(id){return rows.filter(r=>r.seriesId===id).length}
function eventMarkup(item){const repeatCount=seriesCount(item.seriesId),accent=colourForCourse(item.course),meta=[];if(item.room)meta.push(`<div class="schedule-meta-row"><dt>${t('القاعة','Room')}</dt><dd>${esc(item.room)}</dd></div>`);if(item.teacher)meta.push(`<div class="schedule-meta-row"><dt>${t('الدكتور','Instructor')}</dt><dd>${esc(item.teacher)}</dd></div>`);return`<article class="schedule-event" style="--event-accent:${accent}"><div class="schedule-event-top"><div class="schedule-event-title"><strong class="schedule-course">${esc(item.course)}</strong><div class="schedule-badges"><span class="schedule-type-badge">${typeNames[item.type][language()]}</span>${repeatCount>1?`<span class="schedule-repeat-badge">${t(`يتكرر ${repeatCount} أيام`,`Repeats ${repeatCount} days`)}</span>`:''}</div></div><span class="schedule-time" dir="ltr">${formatTime(parseTime(item.start))} – ${formatTime(parseTime(item.end))}</span></div>${meta.length?`<dl class="schedule-meta">${meta.join('')}</dl>`:''}<div class="schedule-event-actions"><button class="schedule-event-button edit" type="button" data-edit-id="${esc(item.id)}">${t('تعديل','Edit')}</button><button class="schedule-event-button delete" type="button" data-delete-id="${esc(item.id)}">${t('حذف','Delete')}</button>${repeatCount>1?`<button class="schedule-event-button delete-series" type="button" data-delete-series="${esc(item.seriesId)}">${t('حذف كل الأيام','Delete all days')}</button>`:''}</div></article>`}
function render(){if(!week)return;week.innerHTML=days.map(day=>{const events=rows.filter(i=>i.day===day).sort((a,b)=>parseTime(a.start)-parseTime(b.start));return`<section class="schedule-day"><h3>${dayNames[day][language()]}</h3><div class="schedule-day-events">${events.length?events.map(eventMarkup).join(''):`<p class="schedule-empty">${t('فارغ','Empty')}</p>`}</div></section>`}).join('');week.querySelectorAll('[data-edit-id]').forEach(b=>b.onclick=()=>beginEdit(b.dataset.editId));week.querySelectorAll('[data-delete-id]').forEach(b=>b.onclick=()=>deleteDay(b.dataset.deleteId));week.querySelectorAll('[data-delete-series]').forEach(b=>b.onclick=()=>deleteSeries(b.dataset.deleteSeries));if(countElement)countElement.textContent=countLabel();if(clearButton)clearButton.hidden=!rows.length;[exportImageButton,printButton,exportJsonButton].forEach(b=>{if(b)b.disabled=!rows.length})}
function syncFormMode(){const e=Boolean(editingSeriesId);if(formTitle)formTitle.textContent=e?t('تعديل المادة','Edit course'):t('إضافة محاضرة','Add a class');if(submitButton)submitButton.textContent=e?t('حفظ التعديلات','Save changes'):t('إضافة للجدول','Add to schedule');if(cancelEditButton)cancelEditButton.hidden=!e;if(editingBadge)editingBadge.hidden=!e}
function resetForm({focus=true}={}){editingSeriesId=null;form?.reset();setSelectedDays(['الأحد']);if(startInput)startInput.value='08:00';if(endInput)endInput.value='09:50';if(startPeriodInput)startPeriodInput.value='am';if(endPeriodInput)endPeriodInput.value='am';if(typeInput)typeInput.value='lecture';syncFormMode();if(focus)courseInput?.focus()}
function beginEdit(id){const item=rows.find(r=>r.id===id);if(!item)return;const group=rows.filter(r=>r.seriesId===item.seriesId);editingSeriesId=item.seriesId;courseInput.value=item.course;typeInput.value=item.type;roomInput.value=item.room;teacherInput.value=item.teacher;const s=splitClock(parseTime(item.start)),e=splitClock(parseTime(item.end));startInput.value=s.value;startPeriodInput.value=s.period;endInput.value=e.value;endPeriodInput.value=e.period;setSelectedDays(group.map(r=>r.day));syncFormMode();form?.scrollIntoView({behavior:'smooth',block:'center'})}
function findConflict(candidates,excludeSeriesId=null,sourceRows=rows){for(const c of candidates){const sm=parseTime(c.start),em=parseTime(c.end),x=sourceRows.find(i=>{if(excludeSeriesId&&i.seriesId===excludeSeriesId)return false;if(i.day!==c.day)return false;return sm<parseTime(i.end)&&em>parseTime(i.start)});if(x)return{candidate:c,conflict:x}}return null}
function findInternalConflict(list){for(const day of days){const a=list.filter(r=>r.day===day).sort((x,y)=>parseTime(x.start)-parseTime(y.start));for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){if(parseTime(a[j].start)>=parseTime(a[i].end))break;if(parseTime(a[j].start)<parseTime(a[i].end))return{first:a[i],second:a[j]}}}return null}
form?.addEventListener('submit',event=>{event.preventDefault();const course=normaliseCourse(courseInput.value),chosenDays=selectedDays(),sm=clockToMinutes(startInput.value,startPeriodInput.value),em=clockToMinutes(endInput.value,endPeriodInput.value);if(!course||!chosenDays.length||sm==null||em==null||em<=sm){toast(t('تحقق من بيانات المادة والوقت','Check course and time'),true);return}const seriesId=editingSeriesId||uid(),existing=new Map(rows.filter(r=>r.seriesId===seriesId).map(r=>[r.day,r])),common={course,start:toTimeValue(sm),end:toTimeValue(em),room:roomInput.value.trim(),teacher:teacherInput.value.trim(),type:allowedTypes.includes(typeInput.value)?typeInput.value:'lecture',seriesId},candidates=chosenDays.map(day=>({...common,day,id:existing.get(day)?.id||uid()})),conf=findConflict(candidates,editingSeriesId);if(conf){toast(t(`يوجد تعارض يوم ${conf.candidate.day} مع ${conf.conflict.course}`,'Schedule conflict'),true);return}rows=editingSeriesId?rows.filter(r=>r.seriesId!==editingSeriesId).concat(candidates):rows.concat(candidates);save();resetForm();toast(t('تم الحفظ','Saved'))});
cancelEditButton?.addEventListener('click',()=>resetForm());
function deleteDay(id){const item=rows.find(r=>r.id===id);if(!item)return;rows=rows.filter(r=>r.id!==id);save()}
function deleteSeries(seriesId){if(!confirm(t('حذف المادة من جميع الأيام؟','Delete course from all days?')))return;rows=rows.filter(r=>r.seriesId!==seriesId);save()}
clearButton?.addEventListener('click',()=>{if(rows.length&&confirm(t('متأكد تريد مسح جميع محاضرات الجدول؟','Clear schedule?'))){rows=[];save()}});
function downloadBlob(blob,fileName){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=fileName;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
exportJsonButton?.addEventListener('click',()=>downloadBlob(new Blob([JSON.stringify({format:EXPORT_FORMAT,version:2,exportedAt:new Date().toISOString(),rows},null,2)],{type:'application/json'}),`uonhub-schedule-${new Date().toISOString().slice(0,10)}.json`));
importJsonButton?.addEventListener('click',()=>importFileInput?.click());importFileInput?.addEventListener('change',async()=>{const file=importFileInput.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()),imported=normaliseRows(Array.isArray(parsed)?parsed:parsed?.rows);if(!imported.length||findInternalConflict(imported))throw 0;if(rows.length&&!confirm(t('استبدال الجدول الحالي؟','Replace current schedule?')))return;rows=imported;save();toast(t('تم استيراد الجدول','Schedule imported'))}catch{toast(t('تعذر استيراد الملف','Import failed'),true)}finally{importFileInput.value=''}});printButton?.addEventListener('click',()=>window.print());
exportImageButton?.addEventListener('click',()=>toast(t('تصدير الصورة متاح من الطباعة حاليًا','Use print/export for image'),false));
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){rows=loadRows();render()}});new MutationObserver(m=>{if(m.some(i=>i.attributeName==='lang'))render()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
try{localStorage.setItem(STORAGE_KEY,JSON.stringify(rows))}catch{}syncFormMode();render();