import{whatsappShare,reportBrokenLink,installErrorCapture,setupNav,enforceUonMaintenance,watchUonMaintenance,$,get,notifyPending,toast,fillCollege,esc,openModal,closeModal,trackEvent,rpc}from'./core.js?v=67.0.0';
setupNav();await enforceUonMaintenance();watchUonMaintenance();installErrorCapture();

const LANG_KEY='uon_language',lang=localStorage.getItem(LANG_KEY)==='en'?'en':'ar',en=lang==='en';
const t=(ar,enText)=>en?enText:ar;
const collegeNames={
 'كلية العلوم والآداب':'College of Arts and Sciences',
 'كلية الاقتصاد والإدارة ونظم المعلومات':'College of Economics, Management and Information Systems',
 'كلية الهندسة والعمارة':'College of Engineering and Architecture',
 'كلية العلوم الصحية':'College of Health Sciences',
 'أخرى':'Other'
};
function localizeCollegeSelect(select){if(!select||!en)return;[...select.options].forEach(option=>{if(!option.value){option.textContent=select.id==='collegeInput'?'Choose college':'All colleges';return}option.textContent=collegeNames[option.value]||option.textContent})}

const search=$('#summarySearch')||$('#search'),collegeFilter=$('#collegeFilter'),collegeInput=$('#collegeInput'),typeFilter=$('#typeFilter'),form=$('#submitForm'),items=$('#summaryGrid')||$('#items'),clearFilters=$('#clearFilters');
if(!items){console.error('UON Hub summaries: result container is missing');throw new Error('summaries_container_missing')}
if(collegeFilter){fillCollege(collegeFilter);localizeCollegeSelect(collegeFilter)}if(collegeInput){fillCollege(collegeInput);localizeCollegeSelect(collegeInput)}

const ratingPicker=$('#ratingPicker'),ratingForm=$('#ratingForm'),ratingModal=$('#ratingModal');
if(ratingPicker)ratingPicker.innerHTML=[1,2,3,4,5].map(n=>`<button type="button" data-value="${n}" aria-label="${n} ${t('نجوم','stars')}">★</button>`).join('');
let rows=[],stats=new Map(),activeItem=null,selectedRating=0,selectedRecommended=null;
const SESSION_KEY='uon_anon_session';let sessionId=localStorage.getItem(SESSION_KEY);if(!sessionId){sessionId=crypto.randomUUID();localStorage.setItem(SESSION_KEY,sessionId)}
const safeUrl=value=>{try{const u=new URL(String(value||''),location.origin);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return''}};
const formatDate=v=>v?new Date(v).toLocaleDateString(en?'en-GB':'ar-OM'):'—';
const starText=value=>{const n=Math.max(0,Math.min(5,Math.round(Number(value)||0)));return '★'.repeat(n)+'☆'.repeat(5-n)};
const normalizedType=item=>{const raw=String(item?.resource_type||item?.content_type||'').trim().toLowerCase();if(['exam','اختبار'].includes(raw))return'exam';if(['notes','ملاحظات'].includes(raw))return'notes';if(['summary','ملخص'].includes(raw))return'summary';return raw};
const typeLabel=value=>({summary:t('ملخص','Summary'),exam:t('اختبار','Exam'),notes:t('ملاحظات','Notes')}[normalizedType({resource_type:value})]||String(value||t('ملف','File')));
const collegeLabel=value=>en?(collegeNames[String(value||'').trim()]||String(value||t('غير محدد','Not specified'))):String(value||'غير محدد');

async function load(){items.innerHTML=`<div class="sum-loading">${t('جاري تحميل الملفات…','Loading files…')}</div>`;try{rows=await get('public_summaries','select=id,title,course_code,college,pdf_url,downloads,created_at,subject,tags,link,description,approved,url,views,rating,updated_at,resource_type,content_type,instructor_name,semester,academic_year,language,page_count&order=created_at.desc&limit=500');await loadStats();render();trackEvent('page_view',{page:'summaries',language:lang})}catch(error){console.error('UON Hub summaries load failed:',error);items.innerHTML=`<div class="sum-empty">${t('تعذر تحميل الملخصات حاليًا. حاول تحديث الصفحة.','Could not load files right now. Please refresh the page.')}</div>`;toast(t('تعذر تحميل الملخصات حاليًا','Could not load files right now'),true)}}
async function loadStats(){stats.clear();const ids=rows.map(x=>String(x.id));if(!ids.length)return;try{const data=await rpc('uon_summary_rating_stats',{p_ids:ids});for(const s of data||[])stats.set(String(s.resource_id),s)}catch(error){console.warn('Rating stats unavailable',error)}}
function card(item){const title=item.title||t('ملخص أو اختبار','Summary or exam'),url=safeUrl(item.url||item.link||item.pdf_url),type=normalizedType(item)||'file',code=item.course_code||item.subject||'',s=stats.get(String(item.id))||{},avg=Number(s.average||item.rating||0),count=Number(s.total||0);const ratingButton=ratingModal?`<button class="btn" data-rate>⭐ ${t('تقييم','Rate')}</button>`:'';return `<article class="sum-card" data-id="${esc(item.id)}"><div class="sum-card-head"><span class="sum-type">${esc(typeLabel(type))}</span><span class="sum-code">${esc(code)}</span></div><h3>${esc(title)}</h3><p class="sum-desc">${esc(item.description||t('ملف دراسي مرفوع لطلاب المقرر.','A study file shared for students in this course.'))}</p><div class="sum-meta"><span>🏫 ${esc(collegeLabel(item.college))}</span><span>👁 ${Number(item.views||0)}</span><span>📥 ${Number(item.downloads||0)}</span><span>🗓 ${formatDate(item.updated_at||item.created_at)}</span></div>${ratingModal?`<div class="sum-rating-line"><span class="sum-stars">${starText(avg)}</span><span class="sum-rating-num">${avg?avg.toFixed(1):t('جديد','New')}</span><small>(${count} ${t('تقييم','ratings')})</small></div>`:''}<div class="sum-actions">${url?`<a class="btn primary" data-open="view" target="_blank" rel="noopener" href="${esc(url)}">${t('فتح الملف','Open file')}</a>`:''}${ratingButton}${url?`<a class="btn" target="_blank" rel="noopener" href="${whatsappShare(title,url)}">${t('مشاركة','Share')}</a><button class="btn danger" data-report>${t('بلاغ','Report')}</button>`:''}</div></article>`}
function render(){const q=(search?.value||'').trim().toLowerCase(),college=collegeFilter?.value||'',type=typeFilter?.value||'';const list=rows.filter(x=>(!college||x.college===college)&&(!type||normalizedType(x)===type)&&`${x.title||''} ${x.subject||''} ${x.course_code||''} ${x.description||''}`.toLowerCase().includes(q));items.innerHTML=list.length?list.map(card).join(''):`<div class="sum-empty">${t('ما حصلنا ملفات تطابق بحثك.','No files match your search.')}</div>`}
function clearAllFilters(){if(search)search.value='';if(collegeFilter)collegeFilter.value='';if(typeFilter)typeFilter.value='';render()}
if(search)search.oninput=render;if(collegeFilter)collegeFilter.onchange=render;if(typeFilter)typeFilter.onchange=render;if(clearFilters)clearFilters.onclick=clearAllFilters;

const openForm=$('#openForm'),closeForm=$('#closeForm');if(openForm)openForm.onclick=()=>openModal('submitModal');if(closeForm)closeForm.onclick=()=>closeModal('submitModal');const closeRating=$('#closeRating');if(closeRating)closeRating.onclick=()=>closeModal('ratingModal');
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
if(form)form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('[type="submit"]'),body=Object.fromEntries(new FormData(form));const course=String(body.subject||'').trim().toUpperCase().replace(/\s+/g,''),type=String(body.resource_type||'').trim().toLowerCase(),original=btn.textContent;btn.disabled=true;btn.textContent=t('جاري الإرسال…','Submitting…');try{const id=await rpc('uon_submit_summary_link_v65',{p_title:String(body.title||'').trim(),p_course_code:course,p_college:String(body.college||'').trim(),p_resource_type:type,p_url:String(body.url||'').trim(),p_description:String(body.description||'').trim()||null,p_session_id:sessionId});await notifyPending('summaries',id);toast(t('تم إرسال الملف للمراجعة','File submitted for review'));form.reset();if(collegeInput){fillCollege(collegeInput);localizeCollegeSelect(collegeInput)}closeModal('submitModal');trackEvent('summary_submit',{course_code:course,resource_type:type})}catch(error){console.error(error);toast(error.message||t('تعذر إرسال الملف، تحقق من البيانات والرابط','Could not submit the file. Check the details and link.'),true)}finally{btn.disabled=false;btn.textContent=original}};

function ratingOverview(s={}){const avg=Number(s.average||0),total=Number(s.total||0),stars=s.stars||{},rec=s.recommended_percent;const bars=[5,4,3,2,1].map(n=>{const count=Number(stars[String(n)]||0),pct=total?Math.round(count/total*100):0;return `<div class="rating-bar"><span>${n}★</span><i><span style="width:${pct}%"></span></i><b>${count}</b></div>`}).join('');return `<div class="rating-overview"><div class="rating-score"><strong>${avg?avg.toFixed(1):'—'}</strong><div class="sum-stars">${starText(avg)}</div><small>${total} ${t('تقييم','ratings')}</small>${rec!==null&&rec!==undefined?`<p>${rec}% ${t('ينصحون به','recommend it')}</p>`:''}</div><div class="rating-bars">${bars}</div></div>`}
function reviewsHtml(s={}){const comments=Array.isArray(s.comments)?s.comments:[];return comments.length?comments.map(r=>`<article class="review"><div class="review-top"><strong>${esc(r.name||t('مجهول','Anonymous'))}</strong><span class="sum-stars">${starText(r.rating)}</span></div><p>${esc(r.comment||'')}</p><small>${formatDate(r.created_at)}</small></article>`).join(''):`<div class="sum-empty">${t('ما فيه آراء مكتوبة للحين.','No written reviews yet.')}</div>`}
function openRating(item){if(!ratingModal)return;activeItem=item;selectedRating=0;selectedRecommended=null;const rid=$('#ratingResourceId');if(rid)rid.value=item.id;const title=$('#ratingTitle');if(title)title.textContent=t('تقييم: ','Rate: ')+(item.title||t('الملف','File'));const subtitle=$('#ratingSubtitle');if(subtitle)subtitle.textContent=item.course_code||item.subject||'';const s=stats.get(String(item.id))||{};const overview=$('#ratingOverview');if(overview)overview.innerHTML=ratingOverview(s);const reviews=$('#reviewList');if(reviews)reviews.innerHTML=reviewsHtml(s);const comment=$('#ratingComment');if(comment)comment.value='';const name=$('#reviewerName');if(name)name.value='';syncPicker();document.querySelectorAll('[data-recommend]').forEach(b=>b.classList.remove('primary'));openModal('ratingModal')}
function syncPicker(){document.querySelectorAll('#ratingPicker [data-value]').forEach(b=>b.classList.toggle('active',Number(b.dataset.value)<=selectedRating))}
if(ratingPicker)ratingPicker.onclick=e=>{const b=e.target.closest('[data-value]');if(!b)return;selectedRating=Number(b.dataset.value);syncPicker()};
document.querySelectorAll('[data-recommend]').forEach(b=>b.onclick=()=>{selectedRecommended=b.dataset.recommend==='true';document.querySelectorAll('[data-recommend]').forEach(x=>x.classList.toggle('primary',x===b))});
if(ratingForm)ratingForm.onsubmit=async e=>{e.preventDefault();if(!selectedRating)return toast(t('اختر عدد النجوم أولًا','Choose a star rating first'),true);const btn=e.submitter||ratingForm.querySelector('[type="submit"]');if(btn)btn.disabled=true;try{await rpc('uon_submit_resource_rating',{p_resource_table:'summaries',p_resource_id:String(activeItem.id),p_session_id:sessionId,p_rating:selectedRating,p_recommended:selectedRecommended,p_comment:$('#ratingComment')?.value.trim()||null,p_reviewer_name:$('#reviewerName')?.value.trim()||null});toast(t('تم حفظ تقييمك ⭐','Your rating was saved ⭐'));await loadStats();render();openRating(activeItem);trackEvent('summary_rating',{rating:selectedRating})}catch(error){toast(error.message||t('تعذر حفظ التقييم','Could not save the rating'),true)}finally{if(btn)btn.disabled=false}};
items.onclick=async e=>{const cardEl=e.target.closest('[data-id]');if(!cardEl)return;const item=rows.find(x=>String(x.id)===cardEl.dataset.id);if(!item)return;if(e.target.closest('[data-rate]'))return openRating(item);if(e.target.closest('[data-report]')){const url=safeUrl(item.url||item.link||item.pdf_url);return reportBrokenLink({sourceTable:'summaries',sourceId:item.id,title:item.title,url})}const open=e.target.closest('[data-open]');if(open){rpc('uon_track_summary_open',{p_summary_id:item.id,p_kind:'view'}).catch(()=>{});item.views=Number(item.views||0)+1;trackEvent('summary_open',{id:item.id,course_code:item.course_code||item.subject||''})}};

load();
