import {get,esc,safeHref} from './core.js?v=67.0.0';

const grid=document.querySelector('#supportCentersGrid');
const count=document.querySelector('#supportCentersCount');
const lang=localStorage.getItem('uon_language')==='en'?'en':'ar',en=lang==='en',t=(ar,enText)=>en?enText:ar;

const KNOWN_CENTERS=[
 {match:/أنجز|anjiz/i,nameAr:'مركز أنجز',nameEn:'Anjiz Center',descriptionAr:'دعم مخصص لطلاب السنة التأسيسية في الإنجليزية والرياضيات والحاسب ومهارات الدراسة.',descriptionEn:'Support for foundation-year students in English, mathematics, computing, and study skills.'},
 {match:/مسالك|learning pathways/i,nameAr:'مركز تعزيز مسالك التعلم',nameEn:'Learning Pathways Enhancement Center',descriptionAr:'جلسات دعم أكاديمي وورش صغيرة لطلاب التخصص في المواد الأساسية.',descriptionEn:'Academic support sessions and small workshops for major students in foundational courses.'}
];
function known(center){const hay=`${center?.name||''} ${center?.name_ar||''} ${center?.name_en||''}`;return KNOWN_CENTERS.find(item=>item.match.test(hay))||null}
function centerName(center){const item=known(center);if(en)return String(center.name_en||item?.nameEn||center.name||center.name_ar||'Student Support Center').trim();return String(center.name_ar||center.name||item?.nameAr||center.name_en||'مركز دعم').trim()}
function centerDescription(center){const item=known(center);if(en)return String(center.description_en||item?.descriptionEn||'Student support service available to University of Nizwa students.').trim();return String(center.description_ar||center.description||item?.descriptionAr||'خدمة دعم طلابية متاحة لطلبة جامعة نزوى.').trim()}
function card(center){const booking=safeHref(center.booking_url,''),location=safeHref(center.location_url,''),actions=[];if(booking)actions.push(`<a class="btn primary" href="${esc(booking)}" target="_blank" rel="noopener noreferrer">${t('حجز موعد','Book appointment')}</a>`);if(location)actions.push(`<a class="btn" href="${esc(location)}" target="_blank" rel="noopener noreferrer">${t('الموقع','Location')}</a>`);return `<article class="support-center-card" dir="${en?'ltr':'rtl'}"><span class="support-card-label">${t('مركز دعم','Support center')}</span><h2>${esc(centerName(center))}</h2><p>${esc(centerDescription(center))}</p>${actions.length?`<div class="support-center-actions">${actions.join('')}</div>`:''}</article>`}

async function load(){if(!grid)return;try{let rows;try{rows=await get('support_centers','select=id,name,name_ar,name_en,description,description_ar,description_en,booking_url,location_url,sort_order&active=eq.true&order=sort_order.asc,created_at.asc')}catch{try{rows=await get('support_centers','select=id,name,name_en,description,description_en,booking_url,location_url,sort_order&active=eq.true&order=sort_order.asc,created_at.asc')}catch{rows=await get('support_centers','select=id,name,description,booking_url,location_url,sort_order&active=eq.true&order=sort_order.asc,created_at.asc')}}if(count)count.textContent=String(rows.length);grid.innerHTML=rows.length?rows.map(card).join(''):`<div class="support-centers-empty">${t('لا توجد مراكز دعم منشورة حاليًا.','No support centers are published right now.')}</div>`}catch(error){console.error(error);grid.innerHTML=`<div class="support-centers-empty">${t('تعذر تحميل مراكز الدعم الآن. جرّب مرة ثانية.','Could not load support centers right now. Please try again.')}</div>`}grid.removeAttribute('aria-busy')}
load();
