const pageMap={
 '/':'home','/index.html':'home','/summaries.html':'summaries','/courses.html':'courses','/course.html':'courses',
 '/ratings.html':'ratings','/tools.html':'tools','/university-guide.html':'guide','/groups.html':'groups',
 '/useful-sites.html':'useful','/assistant.html':'assistant','/gpa.html':'gpa','/schedule.html':'schedule',
 '/calendar.html':'calendar','/academic-calendar.html':'calendar','/projects.html':'projects','/feedback.html':'feedback',
 '/confessions.html':'confessions','/questions.html':'questions','/marketplace.html':'marketplace','/support-centers.html':'support'
};
const dictionary={
 ar:{home:'الرئيسية',courses:'المقررات',tools:'الأدوات',guide:'دليل الجامعة',summaries:'الملخصات',groups:'المجموعات',ratings:'التقييمات',useful:'روابط مهمة',assistant:'UON AI',gpa:'حاسبة المعدل',schedule:'الجدول الدراسي',calendar:'التقويم الأكاديمي',projects:'مشاريع الطلاب',feedback:'اقترح ميزة',confessions:'الاعترافات',questions:'بنك الأسئلة',marketplace:'سوق الطلاب',support:'مراكز الدعم',dark:'الوضع الداكن',light:'الوضع الفاتح',language:'English'},
 en:{home:'Home',courses:'Courses',tools:'Tools',guide:'University Guide',summaries:'Summaries',groups:'Groups',ratings:'Ratings',useful:'Useful Links',assistant:'UON AI',gpa:'GPA Calculator',schedule:'Study Schedule',calendar:'Academic Calendar',projects:'Student Projects',feedback:'Suggest a Feature',confessions:'Confessions',questions:'Question Bank',marketplace:'Student Market',support:'Support Centers',dark:'Dark Mode',light:'Light Mode',language:'العربية'}
};
const LANG_KEY='uon_language',LEGACY_LANG_KEY='uon_hub_lang',THEME_KEY='uon_theme',LEGACY_THEME_KEY='uonhub_theme';
const validLang=v=>v==='ar'||v==='en',validTheme=v=>v==='dark'||v==='light';
function currentLanguage(){const a=localStorage.getItem(LANG_KEY),b=localStorage.getItem(LEGACY_LANG_KEY),v=validLang(a)?a:(validLang(b)?b:'ar');try{localStorage.setItem(LANG_KEY,v);localStorage.setItem(LEGACY_LANG_KEY,v)}catch{}return v}
function currentTheme(){const a=localStorage.getItem(THEME_KEY),b=localStorage.getItem(LEGACY_THEME_KEY),v=validTheme(a)?a:(validTheme(b)?b:'dark');try{localStorage.setItem(THEME_KEY,v);localStorage.setItem(LEGACY_THEME_KEY,v)}catch{}return v}
const activePage=()=>pageMap[location.pathname]||'';
const tr=k=>dictionary[currentLanguage()]?.[k]||k;
let featureStatePromise=null,featureStateMap={},featureVisibilityMap={};
const featureAliases={university_guide:'university-guide',useful_sites:'useful-sites',support_centers:'support-centers',academic_calendar:'calendar'},normalizeFeatureKey=k=>featureAliases[k]||k||'';
const featureByPage={
 'courses.html':'courses','course.html':'courses','summaries.html':'summaries','groups.html':'groups','ratings.html':'ratings',
 'university-guide.html':'university-guide','tools.html':'tools','gpa.html':'gpa','schedule.html':'schedule','calendar.html':'calendar',
 'academic-calendar.html':'calendar','projects.html':'projects','useful-sites.html':'useful-sites','assistant.html':'assistant',
 'feedback.html':'feedback','confessions.html':'confessions','questions.html':'questions','marketplace.html':'marketplace','support-centers.html':'support-centers'
};
async function loadFeatureState(){
 if(featureStatePromise)return featureStatePromise;
 featureStatePromise=import('./core.js?v=61.2.1').then(m=>m.getUonState()).then(s=>{featureStateMap=s?.features||{};featureVisibilityMap=s?.visibility||{};return s}).catch(e=>{featureStatePromise=null;console.warn('Feature guard state failed',e);return null});
 return featureStatePromise;
}
const featureKeys={courses:'courses',summaries:'summaries',groups:'groups',ratings:'ratings',guide:'university-guide',tools:'tools',gpa:'gpa',schedule:'schedule',calendar:'calendar',projects:'projects',useful:'useful-sites',assistant:'assistant',feedback:'feedback',confessions:'confessions',questions:'questions',marketplace:'marketplace',support:'support-centers'};
function targetFeature(link){const d=normalizeFeatureKey(link?.dataset?.feature);if(d)return d;try{return normalizeFeatureKey(featureByPage[new URL(link.href,location.href).pathname.split('/').pop()]||'')}catch{return ''}}
const featureVisible=f=>featureVisibilityMap[normalizeFeatureKey(f)]!==false;
function visibilityHost(el){if(el.matches?.('[data-feature]'))return el;const p=el.closest?.('[data-feature]');if(p)return p;const li=el.closest?.('li');if(li)return li;const a=el.closest?.('article');if(a&&a.querySelectorAll('a[href]').length===1)return a;return el}
function applyFeatureVisibility(root=document){const nodes=[];if(root.matches?.('[data-feature],a[href]'))nodes.push(root);root.querySelectorAll?.('[data-feature],a[href]').forEach(n=>nodes.push(n));nodes.forEach(n=>{const f=targetFeature(n);if(!f)return;const h=visibilityHost(n);if(!h)return;const hidden=!featureVisible(f);h.hidden=hidden;h.toggleAttribute('aria-hidden',hidden);if(hidden)h.style.setProperty('display','none','important');else h.style.removeProperty('display')})}
function installVisibilityObserver(){if(document.documentElement.dataset.featureVisibilityObserver==='1')return;document.documentElement.dataset.featureVisibilityObserver='1';new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>n.nodeType===1&&applyFeatureVisibility(n)))).observe(document.body,{childList:true,subtree:true})}
function installFeatureNavigationGuard(){
 if(document.documentElement.dataset.featureGuardInstalled==='1')return;
 document.documentElement.dataset.featureGuardInstalled='1';
 document.addEventListener('click',async e=>{const link=e.target.closest('a[href]');if(!link||link.target==='_blank'||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const f=targetFeature(link);if(!f)return;e.preventDefault();e.stopImmediatePropagation();if(!featureStateMap[f]&&featureVisibilityMap[f]===undefined)await loadFeatureState();if(!featureVisible(f))return;const status=featureStateMap[f]||'active';if(status!=='active'){showFeatureStateBanner(status,link.textContent?.trim()||'');return}location.href=link.href},true);
 loadFeatureState().then(()=>{applyFeatureVisibility(document);installVisibilityObserver();const page=location.pathname.split('/').pop()||'index.html',f=featureByPage[page];if(f&&!featureVisible(f)&&page!=='index.html'){location.replace('index.html');return}if(f&&featureStateMap[f]&&featureStateMap[f]!=='active'&&page!=='coming-soon.html')location.replace(`coming-soon.html?${new URLSearchParams({feature:f,status:featureStateMap[f]})}`)});
}
function applyTheme(){const t=currentTheme();document.documentElement.setAttribute('data-theme',t);document.documentElement.style.colorScheme=t;document.body?.setAttribute('data-theme',t);document.querySelectorAll('[data-theme-toggle]').forEach(b=>{b.textContent=t==='dark'?'☀':'☾';b.setAttribute('aria-label',t==='dark'?tr('light'):tr('dark'))});const x=document.querySelector('#themeText');if(x)x.textContent=t==='dark'?tr('light'):tr('dark')}
function applyLanguage(){const l=currentLanguage();document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr';document.body?.setAttribute('data-language',l);document.body?.classList.toggle('is-english',l==='en');document.querySelectorAll('[data-ar][data-en]').forEach(el=>{const v=l==='ar'?el.dataset.ar:el.dataset.en;if(el.matches('input,textarea'))el.value=v;else el.textContent=v});document.querySelectorAll('[data-placeholder-ar][data-placeholder-en]').forEach(e=>e.setAttribute('placeholder',l==='ar'?e.dataset.placeholderAr:e.dataset.placeholderEn));document.querySelectorAll('[data-title-ar][data-title-en]').forEach(e=>e.title=l==='ar'?e.dataset.titleAr:e.dataset.titleEn);document.querySelectorAll('[data-label-ar][data-label-en]').forEach(e=>e.setAttribute('aria-label',l==='ar'?e.dataset.labelAr:e.dataset.labelEn));document.querySelectorAll('[data-language-toggle]').forEach(b=>b.textContent=l==='ar'?'EN':'ع')}
function installThemeLanguageObservers(){if(document.documentElement.dataset.uonPrefsObserver==='1')return;document.documentElement.dataset.uonPrefsObserver='1';window.addEventListener('storage',e=>{if(e.key===LANG_KEY||e.key===LEGACY_LANG_KEY){const v=validLang(e.newValue)?e.newValue:'ar';localStorage.setItem(LANG_KEY,v);localStorage.setItem(LEGACY_LANG_KEY,v);applyLanguage()}if(e.key===THEME_KEY||e.key===LEGACY_THEME_KEY){const v=validTheme(e.newValue)?e.newValue:'dark';localStorage.setItem(THEME_KEY,v);localStorage.setItem(LEGACY_THEME_KEY,v);applyTheme()}})}
function navLink(href,key){const f=featureKeys[key],a=f?` data-feature="${f}"`:'';return `<a href="${href}"${a} class="${activePage()===key?'active':''}">${tr(key)}</a>`}
function sideLink(href,key,icon){const f=featureKeys[key],a=f?` data-feature="${f}"`:'';return `<a href="${href}"${a} class="${activePage()===key?'active':''}"><span aria-hidden="true">${icon}</span><b>${tr(key)}</b></a>`}
export function setupV14Shell(){
 document.body.classList.add('v176-app','uon-green-public-shell');applyTheme();applyLanguage();installThemeLanguageObservers();installFeatureNavigationGuard();
 const h=document.querySelector('.site-header');
 if(h)h.innerHTML=`<div class="container v176-nav"><a class="v176-brand" href="index.html"><span>U</span><strong>UON Hub</strong></a><nav class="v176-desktop-nav">${navLink('index.html','home')}${navLink('summaries.html','summaries')}${navLink('groups.html','groups')}${navLink('university-guide.html','guide')}${navLink('tools.html','tools')}</nav><div class="v176-nav-actions"><button class="v176-nav-button" data-theme-toggle type="button"></button><button class="v176-nav-button" data-language-toggle type="button">${currentLanguage()==='ar'?'EN':'ع'}</button><button class="v176-nav-button" data-menu-open type="button" aria-label="${currentLanguage()==='ar'?'فتح القائمة':'Open menu'}">☰</button></div></div>`;
 document.querySelector('#v176SideMenu')?.remove();document.querySelector('#v176Backdrop')?.remove();
 document.body.insertAdjacentHTML('beforeend',`<aside class="v176-side-menu uon-green-menu" id="v176SideMenu"><div class="v176-menu-head"><div class="v176-brand"><span>U</span><strong>UON Hub</strong></div><button data-menu-close type="button" aria-label="${currentLanguage()==='ar'?'إغلاق':'Close'}">✕</button></div><div class="uon-green-menu-section"><small>${currentLanguage()==='ar'?'الأساسيات':'Essentials'}</small><nav>${sideLink('index.html','home','⌂')}${sideLink('assistant.html','assistant','AI')}${sideLink('summaries.html','summaries','📚')}${sideLink('groups.html','groups','💬')}${sideLink('courses.html','courses','🎓')}</nav></div><div class="uon-green-menu-section"><small>${currentLanguage()==='ar'?'الدراسة':'Study'}</small><nav>${sideLink('schedule.html','schedule','🗓️')}${sideLink('academic-calendar.html','calendar','📅')}${sideLink('gpa.html','gpa','◔')}${sideLink('questions.html','questions','🧠')}</nav></div><div class="uon-green-menu-section"><small>${currentLanguage()==='ar'?'المزيد':'More'}</small><nav>${sideLink('university-guide.html','guide','🏫')}${sideLink('tools.html','tools','🧰')}${sideLink('ratings.html','ratings','★')}${sideLink('projects.html','projects','💡')}${sideLink('support-centers.html','support','⊕')}${sideLink('useful-sites.html','useful','↗')}${sideLink('confessions.html','confessions','👀')}${sideLink('marketplace.html','marketplace','🛍️')}${sideLink('feedback.html','feedback','＋')}</nav></div><div class="v176-menu-settings"><button data-theme-toggle type="button"><span>◐</span><span id="themeText"></span></button><button data-language-toggle type="button"><span>◎</span><span>${tr('language')}</span></button></div></aside><div class="v176-backdrop" id="v176Backdrop"></div>`);
 const m=document.querySelector('#v176SideMenu'),b=document.querySelector('#v176Backdrop');const open=()=>{m?.classList.add('open');b?.classList.add('open');document.body.classList.add('uon-menu-open')},close=()=>{m?.classList.remove('open');b?.classList.remove('open');document.body.classList.remove('uon-menu-open')};
 document.querySelectorAll('[data-menu-open]').forEach(x=>x.addEventListener('click',open));document.querySelectorAll('[data-menu-close]').forEach(x=>x.addEventListener('click',close));b?.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});m?.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));
 document.querySelectorAll('[data-theme-toggle]').forEach(x=>x.addEventListener('click',()=>{const n=currentTheme()==='dark'?'light':'dark';localStorage.setItem(THEME_KEY,n);localStorage.setItem(LEGACY_THEME_KEY,n);applyTheme();applyLanguage()}));
 document.querySelectorAll('[data-language-toggle]').forEach(x=>x.addEventListener('click',()=>{const n=currentLanguage()==='ar'?'en':'ar';localStorage.setItem(LANG_KEY,n);localStorage.setItem(LEGACY_LANG_KEY,n);location.reload()}));
 if(!document.querySelector('#featureStateBanner'))document.body.insertAdjacentHTML('beforeend',`<div class="feature-state-banner" id="featureStateBanner"><button id="featureStateBannerClose" type="button">✕</button><div><strong id="featureStateBannerTitle"></strong><p id="featureStateBannerText"></p></div></div>`);
 document.querySelector('#featureStateBannerClose')?.addEventListener('click',()=>document.querySelector('#featureStateBanner')?.classList.remove('show'));applyTheme();applyLanguage();
}
export function showFeatureStateBanner(status,title=''){const l=currentLanguage(),m={ar:{maintenance:['الخدمة تحت الصيانة','نعمل على تحسين هذه الخدمة، جرّب مرة أخرى لاحقًا.'],disabled:['الخدمة غير متاحة حاليًا','تم إيقاف هذه الخدمة مؤقتًا.'],coming_soon:['الخدمة قادمة قريبًا','هذه الخدمة ستتوفر قريبًا.']},en:{maintenance:['Service under maintenance','We are improving this service. Please try again later.'],disabled:['Service unavailable','This service is temporarily disabled.'],coming_soon:['Coming soon','This service will be available soon.']}}[l]?.[status]||[];const b=document.querySelector('#featureStateBanner');if(!b)return;const t=b.querySelector('#featureStateBannerTitle'),p=b.querySelector('#featureStateBannerText');if(t)t.textContent=title?`${title} — ${m[0]||''}`:(m[0]||'');if(p)p.textContent=m[1]||'';b.className=`feature-state-banner ${status} show`;setTimeout(()=>b.classList.remove('show'),5000)}
