const pageMap={'/index.html':'home','/':'home','/summaries.html':'summaries','/courses.html':'courses','/ratings.html':'ratings','/tools.html':'tools','/university-guide.html':'guide','/groups.html':'groups'};
const active=()=>pageMap[location.pathname]||'';
const link=(href,label,key)=>`<a href="${href}" class="${active()===key?'active':''}">${label}</a>`;
export function setupV14Shell(){
 document.body.classList.add('v17-app');
 const header=document.querySelector('.site-header');
 if(header)header.innerHTML=`<div class="container v17-nav"><a class="v17-brand" href="index.html"><span>U1</span><strong>UON Hub</strong></a><nav>${link('index.html','الرئيسية','home')}${link('summaries.html','الملخصات','summaries')}${link('groups.html','المجموعات','groups')}${link('courses.html','المقررات','courses')}${link('university-guide.html','دليل الجامعة','guide')}</nav><div class="v17-nav-actions"><button id="v17SearchOpen" aria-label="البحث">بحث</button><button id="v17MenuOpen" class="v17-menu-button" aria-label="القائمة">☰</button></div></div>`;
 if(!document.querySelector('#v17MobileMenu'))document.body.insertAdjacentHTML('beforeend',`<aside id="v17MobileMenu" class="v17-mobile-menu"><div><strong>القائمة</strong><button id="v17MenuClose">✕</button></div><a href="index.html">الرئيسية</a><a href="summaries.html">الملخصات والاختبارات</a><a href="groups.html">مجموعات الواتساب</a><a href="courses.html">مركز المقررات</a><a href="ratings.html">التقييمات</a><a href="gpa.html">حاسبة المعدل</a><a href="university-guide.html">دليل الجامعة</a><a href="tools.html">كل الأدوات</a></aside>`);
 if(!document.querySelector('#v17SearchOverlay'))document.body.insertAdjacentHTML('beforeend',`<div id="v17SearchOverlay" class="v17-search-overlay"><form id="v17SearchForm"><input id="v17SearchInput" placeholder="ابحث عن مادة أو ملخص أو تخصص"><button>بحث</button><button type="button" id="v17SearchClose">إغلاق</button></form></div>`);
 const menu=document.querySelector('#v17MobileMenu');document.querySelector('#v17MenuOpen')?.addEventListener('click',()=>menu.classList.add('open'));document.querySelector('#v17MenuClose')?.addEventListener('click',()=>menu.classList.remove('open'));
 const overlay=document.querySelector('#v17SearchOverlay');document.querySelector('#v17SearchOpen')?.addEventListener('click',()=>overlay.classList.add('open'));document.querySelector('#v17SearchClose')?.addEventListener('click',()=>overlay.classList.remove('open'));document.querySelector('#v17SearchForm')?.addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#v17SearchInput').value.trim();if(q)location.href=`search.html?q=${encodeURIComponent(q)}`});
 const drawer=document.querySelector('#notificationDrawer');document.querySelector('#simpleNotificationOpen')?.addEventListener('click',()=>drawer?.classList.add('open'));
}
