import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.110.8';

declare const Deno:any;
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const GEMINI_API_KEY=Deno.env.get('GEMINI_API_KEY')||'';
const db=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const PRIORITY=['gemini-3.8-flash','gemini-3.7-flash','gemini-3.6-flash','gemini-3.5-flash','gemini-3.5-flash-lite','gemini-3.1-flash-lite','gemini-2.5-flash'];
const QUARANTINE_MS=15*60*1000;
const clean=(v:any,n=400)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n);
function out(body:any,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function authorized(req:Request){const token=req.headers.get('x-sync-secret')||'';if(!token)return false;const{data,error}=await db.rpc('uon_ai_sync_token_valid',{p_token:token});return !error&&data===true}
async function listModels(){if(!GEMINI_API_KEY)throw new Error('GEMINI_API_KEY_MISSING');const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models?pageSize=100',{headers:{'x-goog-api-key':GEMINI_API_KEY},signal:AbortSignal.timeout(6500)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`MODELS_HTTP_${r.status}`);return(d.models||[]).filter((m:any)=>{const methods=m.supportedGenerationMethods||m.supportedActions||[];return methods.includes('generateContent')}).map((m:any)=>String(m.name||'').replace(/^models\//,'')).filter(Boolean)}
async function probe(model:string){const started=Date.now();try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':GEMINI_API_KEY},body:JSON.stringify({contents:[{role:'user',parts:[{text:'Reply only: OK'}]}],generationConfig:{temperature:0,maxOutputTokens:8}}),signal:AbortSignal.timeout(8000)});const d=await r.json().catch(()=>({}));const latency=Date.now()-started;if(!r.ok)return{model,ok:false,latency_ms:latency,error:`HTTP_${r.status}:${clean(d?.error?.status||d?.error?.message||'probe_failed')}`};const text=clean(d?.candidates?.[0]?.content?.parts?.map((x:any)=>x?.text||'').join(''),40);return{model,ok:Boolean(text),latency_ms:latency,error:text?'':'empty_response',model_version:clean(d.modelVersion,120)} }catch(e){return{model,ok:false,latency_ms:Date.now()-started,error:clean((e as Error)?.message||e)}}
async function persist(result:any){const now=Date.now();if(result.ok){const{data}=await db.from('uon_ai_model_health').select('failure_count').eq('model',result.model).maybeSingle();await db.from('uon_ai_model_health').upsert({model:result.model,failure_count:Number(data?.failure_count||0),last_success_at:new Date(now).toISOString(),disabled_until:null,last_error:null,metadata:{probe_latency_ms:result.latency_ms,model_version:result.model_version||null,last_probe:'success'},updated_at:new Date(now).toISOString()},{onConflict:'model'});return}const{data}=await db.from('uon_ai_model_health').select('failure_count').eq('model',result.model).maybeSingle();await db.from('uon_ai_model_health').upsert({model:result.model,failure_count:Number(data?.failure_count||0)+1,last_failure_at:new Date(now).toISOString(),disabled_until:new Date(now+QUARANTINE_MS).toISOString(),last_error:result.error,metadata:{probe_latency_ms:result.latency_ms,last_probe:'failed'},updated_at:new Date(now).toISOString()},{onConflict:'model'})}
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return out({error:'method_not_allowed'},405);if(!(await authorized(req)))return out({error:'unauthorized'},401);try{const models=await listModels();const candidates=PRIORITY.filter(m=>models.includes(m)).slice(0,4);if(!candidates.length)return out({ok:true,available_count:models.length,probed:0,results:[]});const results=await Promise.all(candidates.map(probe));await Promise.all(results.map(persist));return out({ok:true,available_count:models.length,probed:results.length,results:results.map(x=>({model:x.model,ok:x.ok,latency_ms:x.latency_ms,model_version:x.model_version||null}))})}catch(e){return out({ok:false,error:clean((e as Error)?.message||e)},500)}});
