declare const Deno:any;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const COURSE_CODE=/\b([A-Z]{2,8})\s*[- ]?\s*(\d{3})(?:\s*\/\s*L)?\b/g;
const CREDIT_PATTERNS=[/\b([1-6])\s*\(\s*([0-9])\s*\+\s*([0-9])\s*\)/,/\b([1-6])\s+([0-9])\s+([0-9])\b/];
const clean=(value:any)=>String(value??'').replace(/\u00a0/g,' ').replace(/[\t ]+/g,' ').replace(/\s+/g,' ').trim();
function authorized(req:Request){return (req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'')===SERVICE_KEY;}
function safeUrl(value:any){const url=new URL(String(value||''));const host=url.hostname.toLowerCase();if(!(host==='unizwa.edu.om'||host.endsWith('.unizwa.edu.om'))||!['http:','https:'].includes(url.protocol)||!/\.pdf(?:$|[?#])/i.test(url.toString()))throw new Error('invalid_official_pdf');return url.toString();}
function codeMatches(value:string){COURSE_CODE.lastIndex=0;const rows=[...value.matchAll(COURSE_CODE)];COURSE_CODE.lastIndex=0;return rows;}
function normalizeCode(value:string){return value.replace(/[^A-Z0-9]/gi,'').toUpperCase().replace(/L$/,'');}
function titleClean(value:string){return clean(value).replace(/^[-–—:|,;.)\d\s]+/,'').replace(/\b(?:CODE|COURSE|CREDITS?|THEORY|PRACTICAL|CONTACT HOURS?|PRE-?REQUISITES?|CO-?REQUISITES?)\b/gi,' ').replace(/\s+/g,' ').trim();}
function requirement(value:string){const text=value.toLowerCase();if(/university requirements?|general requirements?|متطلبات الجامعة/.test(text))return'university';if(/college requirements?|متطلبات الكلية/.test(text))return'college';if(/technical electives?|department electives?|major electives?|اختياري/.test(text))return'elective';return'major';}
function scoreTitle(title:string){if(title.length<3||title.length>150)return-100;if(!/[A-Za-z\u0600-\u06ff]/.test(title))return-100;if(codeMatches(title).length)return-100;if(/^(?:none|null|course|code)$/i.test(title))return-100;let score=Math.min(title.length,60);if(/\b(?:AND|OF|IN|FOR|TO|WITH|THE)$/i.test(title))score-=12;if(/[0-9]/.test(title))score-=18;return score;}
async function extract(url:string){const response=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(45000),headers:{'user-agent':'UON-Hub Engineering Plan Review/32.6'}});if(!response.ok)throw new Error(`download_${response.status}`);const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.byteLength>20*1024*1024)throw new Error('file_too_large');const {extractText}=await import('npm:unpdf@1.2.2');const result:any=await extractText(bytes,{mergePages:false});const raw=result?.text??result;return Array.isArray(raw)?raw.map((page:any)=>String(page||'')):[String(raw||'')];}
function findCredit(value:string){let best:null|{index:number;credits:number;lecture:number;practical:number;raw:string}=null;for(const pattern of CREDIT_PATTERNS){const match=pattern.exec(value);pattern.lastIndex=0;if(!match)continue;const item={index:Number(match.index),credits:Number(match[1]),lecture:Number(match[2]),practical:Number(match[3]),raw:match[0]};if(!best||item.index<best.index)best=item;}return best;}
function parsePages(pages:string[],source:string){const candidates=new Map<string,any[]>();let globalRequirement='major';for(let pageIndex=0;pageIndex<pages.length;pageIndex++){const lines=String(pages[pageIndex]||'').replace(/\r/g,'\n').split(/\n+/).map(clean).filter(Boolean);for(let lineIndex=0;lineIndex<lines.length;lineIndex++){const context=lines.slice(Math.max(0,lineIndex-4),lineIndex+1).join(' ');if(/requirements?|electives?|متطلبات|اختياري/i.test(context))globalRequirement=requirement(context);const line=lines[lineIndex];for(const match of codeMatches(line)){const code=normalizeCode(match[0]);const prefix=line.slice(0,Number(match.index||0));const startsClean=/^\s*(?:\d{1,3}\s+)?$/i.test(prefix);let assembled=line.slice(Number(match.index||0)+match[0].length);let consumed=0;let credit=findCredit(assembled);while(!credit&&consumed<3&&lineIndex+consumed+1<lines.length){const next=lines[lineIndex+consumed+1];const nextCodes=codeMatches(next);if(nextCodes.length&&/^[A-Z]/.test(next)&&!findCredit(assembled))break;assembled=`${assembled} ${next}`;consumed++;credit=findCredit(assembled);}if(!credit)continue;let titlePart=assembled.slice(0,credit.index);const embedded=codeMatches(titlePart);if(embedded.length)titlePart=titlePart.slice(0,Number(embedded[0].index||0));const title=titleClean(titlePart);const baseScore=scoreTitle(title);if(baseScore<0)continue;const sequenceBonus=/^\s*\d{1,3}\s*$/i.test(prefix)?45:startsClean?30:0;const detailedPageBonus=pageIndex>=2?18:0;const singleColumnBonus=codeMatches(line.slice(0,Number(match.index||0)+match[0].length+titlePart.length+credit.raw.length)).length===1?12:0;const score=baseScore+sequenceBonus+detailedPageBonus+singleColumnBonus+(credit.credits?8:0);const item={code,name_en:title,credit_hours:credit.credits,lecture_hours:credit.lecture,practical_hours:credit.practical,requirement_type:requirement(context)||globalRequirement,source_url:source,score,page:pageIndex+1,line:lineIndex+1};if(!candidates.has(code))candidates.set(code,[]);candidates.get(code)!.push(item);}}}return[...candidates.entries()].map(([code,rows])=>rows.sort((a,b)=>b.score-a.score)[0]).sort((a,b)=>a.code.localeCompare(b.code));}
Deno.serve(async(req:Request)=>{const headers={'content-type':'application/json; charset=utf-8'};if(req.method!=='POST')return new Response('{}',{status:405,headers});if(!authorized(req))return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers});try{const body=await req.json().catch(()=>({}));const url=safeUrl(body.url);const rows=parsePages(await extract(url),url);return new Response(JSON.stringify({ok:true,read_only:true,source_url:url,courses:rows.length,rows}),{headers});}catch(error){return new Response(JSON.stringify({ok:false,error:String((error as Error)?.message||error)}),{status:500,headers});}});
