(()=>{if(window.__anjizReportsTimetableCommsRegInstStudentDemoQrV24)return;window.__anjizReportsTimetableCommsRegInstStudentDemoQrV24=1;
const reportUrl='https://raw.githubusercontent.com/wshukaili25-a11y/UON-COFFEE/6f208a721d1621ceef38937815d122ab09c6ca31/anjiz-v7/reports-v12.js';
const root='https://raw.githubusercontent.com/wshukaili25-a11y/UON-COFFEE/anjiz-system-v7/anjiz-v7/';
const qrScanLib='https://cdn.jsdelivr.net/npm/html5-qrcode@2.3.8/html5-qrcode.min.js';
const qrMakeLib='https://cdn.jsdelivr.net/npm/qrcode@1.5.4/build/qrcode.min.js';
async function text(u,n){return fetch(u,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(n+' '+r.status);return r.text()})}
async function gunzipB64(t){const b=Uint8Array.from(atob(t.trim()),c=>c.charCodeAt(0));return await new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream('gzip'))).text()}
async function unpack(url,marker,label){const p=await text(url,label);const raw=await gunzipB64(p),i=raw.indexOf(marker);if(i<0)throw new Error(label+' validation failed');return{js:raw.slice(0,i),css:raw.slice(i+marker.length)}}
function style(id,css){if(!css||document.getElementById(id))return;const s=document.createElement('style');s.id=id;s.textContent=css;document.head.appendChild(s)}
function loadScript(id,src,test){return new Promise((resolve,reject)=>{if(test())return resolve();let s=document.getElementById(id);if(s){s.addEventListener('load',resolve,{once:true});s.addEventListener('error',reject,{once:true});return}s=document.createElement('script');s.id=id;s.src=src;s.async=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function v24esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function scanValueV24(raw){let v=String(raw||'').trim();try{const u=new URL(v,location.href);for(const k of ['verifyUid','uid','id','user','verify']){const x=u.searchParams.get(k);if(x&&/^[A-Za-z0-9._-]{2,50}$/.test(x))return x.toUpperCase()}}catch(e){}const m=v.match(/(?:ANJIZ\s*[:#|\-]\s*)?([A-Z]{1,5}\d{2,15})/i);return (m?m[1]:v).toUpperCase()}
function finishScanV24(raw,fieldId){const val=scanValueV24(raw),field=document.getElementById(fieldId||'loginId');try{closeModal()}catch(e){}if(field){field.value=val;field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new Event('change',{bubbles:true}));field.focus()}if((fieldId||'loginId')==='loginId'){const p=document.getElementById('loginPass');if(p)p.focus()}}
async function decodeFileV24(file,fieldId){if(!file)return;const status=document.getElementById('anjizQrStatusV24');if(status)status.textContent='Reading QR…';try{await loadScript('anjiz-html5-qrcode-v24',qrScanLib,()=>!!window.Html5Qrcode);let host=document.getElementById('anjizQrDecodeV24');if(!host){host=document.createElement('div');host.id='anjizQrDecodeV24';host.style.display='none';document.body.appendChild(host)}const reader=new Html5Qrcode('anjizQrDecodeV24');const raw=await reader.scanFile(file,false);try{await reader.clear()}catch(e){}finishScanV24(raw,fieldId)}catch(e){if(status)status.innerHTML='<b>QR could not be read.</b> Try again with the QR centered and clearly visible.'}}
window.openAnjizQrScannerV24=function(fieldId='loginId'){
 showModal(`<div style="text-align:left"><span class="section-label">ANJIZ QR SCANNER</span><h3 style="margin:5px 0 5px">Scan Student ID / QR</h3><p class="muted" style="margin-top:0">Works on iPhone even when live browser barcode detection is unavailable.</p><div id="anjizQrStatusV24" class="notice" style="margin:12px 0">Use the iPhone camera or choose an existing QR image.</div><div class="row" style="gap:8px;flex-wrap:wrap"><label class="btn primary" style="cursor:pointer">Open Camera<input id="anjizQrCameraV24" type="file" accept="image/*" capture="environment" style="position:absolute;opacity:0;width:1px;height:1px"></label><label class="btn secondary" style="cursor:pointer">Choose QR Image<input id="anjizQrPhotoV24" type="file" accept="image/*" style="position:absolute;opacity:0;width:1px;height:1px"></label><button class="btn outline" onclick="closeModal()">Close</button></div><div id="anjizQrDecodeV24" style="display:none"></div></div>`);
 setTimeout(()=>{const a=document.getElementById('anjizQrCameraV24'),b=document.getElementById('anjizQrPhotoV24');if(a)a.onchange=()=>decodeFileV24(a.files?.[0],fieldId);if(b)b.onchange=()=>decodeFileV24(b.files?.[0],fieldId)},0)
};
window.scanBarcodeToField=function(fieldId){openAnjizQrScannerV24(fieldId||'loginId')};
document.addEventListener('click',e=>{const b=e.target.closest?.('[onclick*="scanBarcodeToField"]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const m=(b.getAttribute('onclick')||'').match(/scanBarcodeToField\(['\"]([^'\"]+)/);openAnjizQrScannerV24(m?.[1]||'loginId')},true);
function currentUserV24(){try{return me}catch(e){return null}}
function verificationUrlV24(uid){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('verifyUid',uid);return u.toString()}
window.openMyQrV24=async function(){const who=currentUserV24();if(!who)return;const verify=verificationUrlV24(who.uid);showModal(`<div style="text-align:center"><span class="section-label">ANJIZ DIGITAL ID</span><h3 style="margin:5px 0">My QR</h3><p class="muted">Scan to verify this ANJIZ identity.</p><div style="display:grid;place-items:center;min-height:270px"><canvas id="anjizMyQrCanvasV24" width="260" height="260" style="max-width:100%;background:#fff;border-radius:16px;padding:8px"></canvas></div><b style="display:block;margin-top:8px">${v24esc(who.name)}</b><span class="muted">${v24esc(who.uid)} · ${v24esc(who.sub||who.role||'')}</span><div class="row" style="justify-content:center;margin-top:14px;flex-wrap:wrap"><button class="btn secondary" onclick="navigator.clipboard?.writeText('${verify.replace(/'/g,"\\'")}');toast?.('Verification link copied')">Copy Verification Link</button><button class="btn outline" onclick="closeModal()">Close</button></div></div>`);try{await loadScript('anjiz-qrcode-make-v24',qrMakeLib,()=>!!window.QRCode);const c=document.getElementById('anjizMyQrCanvasV24');if(c&&window.QRCode?.toCanvas)await QRCode.toCanvas(c,verify,{width:260,margin:2})}catch(e){const c=document.getElementById('anjizMyQrCanvasV24');if(c){const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.font='14px system-ui';x.textAlign='center';x.fillText('QR generator unavailable',130,120);x.font='11px system-ui';x.fillText('Use Copy Verification Link',130,145)}}};
try{const baseDashboard=dashboard;dashboard=function(){let html=baseDashboard();const who=currentUserV24();if(who&&['student','visitor'].includes(String(who.role||'').toLowerCase()))html=`<div class="panel" style="margin-bottom:12px"><div class="toolbar"><div><span class="section-label">DIGITAL ID</span><h3>My ANJIZ QR</h3><p class="muted" style="margin:3px 0 0">Use your QR for identity verification and attendance.</p></div><button class="btn primary" onclick="openMyQrV24()">Open My QR</button></div></div>`+html;return html}}catch(e){}
function showVerifyV24(){const uid=new URLSearchParams(location.search).get('verifyUid');if(!uid)return;setTimeout(()=>{let u=null;try{u=typeof user==='function'?user(uid):null;if(!u&&window.db?.users)u=db.users.find(x=>String(x.uid).toUpperCase()===String(uid).toUpperCase())}catch(e){}if(u)showModal(`<div style="text-align:center"><div style="font-size:42px">✓</div><span class="section-label">ANJIZ IDENTITY</span><h3 style="margin:5px 0">Identity Verified</h3><p>${v24esc(u.name)}</p><div class="detail-grid"><div><small>University ID</small><b>${v24esc(u.uid)}</b></div><div><small>Role</small><b>${v24esc(u.role||u.sub||'ANJIZ User')}</b></div><div><small>Status</small><b>${u.active===false?'Inactive':'Active'}</b></div></div><p class="muted" style="margin-top:12px">Demo verification for CIS review. Production signing will be connected by CIS.</p></div>`);else showModal(`<h3>Verification Failed</h3><p>The ANJIZ ID in this QR could not be verified.</p>`)},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',showVerifyV24,{once:true});else showVerifyV24();
setInterval(()=>{let who=currentUserV24(),btn=document.getElementById('anjizStudentQrFabV24');let role=String(who?.role||'').toLowerCase(),sub=String(who?.sub||'').toLowerCase();let show=!!who&&(role==='student'||role==='visitor'||sub.includes('student')||sub.includes('visitor'));if(show&&!btn){btn=document.createElement('button');btn.id='anjizStudentQrFabV24';btn.className='btn primary';btn.textContent='My QR';btn.onclick=()=>openMyQrV24();btn.style.cssText='position:fixed;right:18px;bottom:18px;z-index:9997;min-width:92px;box-shadow:0 10px 28px rgba(0,0,0,.2)';document.body.appendChild(btn)}else if(!show&&btn)btn.remove()},700);
(async()=>{try{
const [reportCode,tt,comm,reg,inst,sv,svfix,demo,qr]=await Promise.all([
 text(reportUrl,'reports core'),
 unpack(root+'timetable-v13.pack.b64?v=20260901e','/*__ANJIZ_TIMETABLE_CSS_SPLIT__*/','timetable pack'),
 unpack(root+'comms-v14.pack.b64?v=20260901f','/*__ANJIZ_COMMS_CSS_SPLIT__*/','communications pack'),
 unpack(root+'registration-v15.pack.b64?v=20260901g','/*__ANJIZ_REGISTRATION_CSS_SPLIT__*/','registration pack'),
 unpack(root+'instructor-v16.pack.b64?v=20260901h','/*__ANJIZ_INSTRUCTOR_CSS_SPLIT__*/','instructor pack'),
 unpack(root+'student-v18.pack.b64?v=20260901i','/*__ANJIZ_STUDENT_CSS_SPLIT__*/','student visitor pack'),
 unpack(root+'student-v18-fix.pack.b64?v=20260901j','/*__ANJIZ_STUDENT_FIX_CSS_SPLIT__*/','student visitor record fix'),
 unpack(root+'demo-v19.pack.b64?v=20260901k','/*__ANJIZ_DEMO_V19_CSS_SPLIT__*/','demo services pack'),
 unpack(root+'qr-v20.pack.b64?v=20260901l','/*__ANJIZ_QR_V20_CSS_SPLIT__*/','qr identity pack')
]);
style('timetableV13-css',tt.css);style('commsV14-css',comm.css);style('registrationV15-css',reg.css);style('instructorV16-css',inst.css);style('studentV18-css',sv.css);style('demoV19-css',demo.css);style('qrV20-css',qr.css);
const blob=new Blob([reportCode+'\n'+tt.js+'\n'+comm.js+'\n'+reg.js+'\n'+inst.js+'\n'+sv.js+'\n'+svfix.js+'\n'+demo.js+'\n'+qr.js],{type:'text/javascript'}),url=URL.createObjectURL(blob);
await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});URL.revokeObjectURL(url);
window.__reportsV12CoreLoaded=1;window.__timetableV13Loaded=1;window.__commsV14Loaded=1;window.__registrationV15Loaded=1;window.__instructorV16Loaded=1;window.__studentV18Loaded=1;window.__demoV19Loaded=1;window.__qrV20Loaded=1;
}catch(e){console.warn('ANJIZ V24 core add-ons unavailable',e)}})()})();
