
import {$,setupNav,toast} from './ui.js';setupNav();
const G={'A':4,'A-':3.7,'B+':3.3,'B':3,'B-':2.7,'C+':2.3,'C':2,'C-':1.7,'D+':1.3,'D':1,'F':0};const body=$('#courseRows');
const options=(sel='A',blank=false)=>(blank?'<option value="">—</option>':'')+Object.keys(G).map(g=>`<option ${g===sel?'selected':''}>${g}</option>`).join('');
function addRow(d={}){const tr=document.createElement('tr');tr.innerHTML=`<td><input class="name" value="${d.name||''}" placeholder="STAT101"></td><td><input class="hours" type="number" min=".5" max="9" step=".5" value="${d.hours||3}"></td><td><select class="new-grade">${options(d.newGrade||'A')}</select></td><td><input class="repeat" type="checkbox" ${d.repeat?'checked':''}></td><td><select class="old-grade" ${d.repeat?'':'disabled'}>${options(d.oldGrade||'',true)}</select></td><td class="new-points">0.00</td><td class="old-points">0.00</td><td class="net">0.00</td><td><button class="icon-btn remove"><i class="fas fa-times"></i></button></td>`;tr.querySelector('.remove').onclick=()=>{tr.remove();calc()};tr.querySelector('.repeat').onchange=e=>{tr.querySelector('.old-grade').disabled=!e.target.checked;if(!e.target.checked)tr.querySelector('.old-grade').value='';calc()};tr.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calc));body.append(tr);calc()}
function data(){return [...body.rows].map(r=>({name:r.querySelector('.name').value,hours:+r.querySelector('.hours').value||0,newGrade:r.querySelector('.new-grade').value,repeat:r.querySelector('.repeat').checked,oldGrade:r.querySelector('.old-grade').value}))}
function calc(){let semesterPoints=0,currentHours=0,net=0,repeatHours=0;[...body.rows].forEach(r=>{const h=+r.querySelector('.hours').value||0,n=G[r.querySelector('.new-grade').value]||0,rep=r.querySelector('.repeat').checked,old=r.querySelector('.old-grade').value,op=rep&&old!==''?h*(G[old]||0):0,np=h*n,d=np-op;semesterPoints+=np;currentHours+=h;net+=d;if(rep)repeatHours+=h;r.querySelector('.new-points').textContent=np.toFixed(2);r.querySelector('.old-points').textContent=op.toFixed(2);r.querySelector('.net').textContent=d.toFixed(2)});const prevG=Math.min(4,Math.max(0,+$('#currentGpa').value||0)),prevH=Math.max(0,+$('#previousHours').value||0);const semester=currentHours?semesterPoints/currentHours:0;const addedHours=Math.max(0,currentHours-repeatHours);const totalH=prevH+addedHours;const cumulative=totalH?((prevG*prevH)+net)/totalH:semester;$('#semesterGpa').textContent=semester.toFixed(2);$('#semesterHours').textContent=`${currentHours} ساعة`;$('#netPoints').textContent=net.toFixed(2);$('#cumulativeGpa').textContent=Math.max(0,cumulative).toFixed(2);$('#totalHours').textContent=`${totalH} ساعة`}
function save(){localStorage.setItem('uon-gpa-v6',JSON.stringify({currentGpa:$('#currentGpa').value,previousHours:$('#previousHours').value,courses:data()}));toast('تم الحفظ')}
function load(){try{const s=JSON.parse(localStorage.getItem('uon-gpa-v6')||'null');if(s){$('#currentGpa').value=s.currentGpa||0;$('#previousHours').value=s.previousHours||0;(s.courses||[]).forEach(addRow);return}}catch{}addRow();addRow();addRow()}
$('#addCourse').onclick=()=>addRow();$('#saveGpa').onclick=save;$('#clearCourses').onclick=()=>{if(confirm('مسح البيانات؟')){body.innerHTML='';localStorage.removeItem('uon-gpa-v6');addRow()}};$('#currentGpa').oninput=calc;$('#previousHours').oninput=calc;load();calc();
