
import {get,insert,notifyPending} from './api.js';import {$,esc,toast,setupNav} from './ui.js';import {initI18n} from './i18n.js';
setupNav();initI18n();let rows=[],kind='course';
function stars(n){n=Math.round(Number(n||0));return'★'.repeat(n)+'☆'.repeat(5-n)}
function render(){const q=$('#search').value.toLowerCase();const list=rows.filter(x=>x.kind===kind&&`${x.target_name||''} ${x.college||''}`.toLowerCase().includes(q));$('#grid').innerHTML=list.length?list.map(x=>`<article class="card rating-card"><span class="badge">${x.kind==='course'?'مادة':'دكتور'}</span><h3>${esc(x.target_name)}</h3><p>${esc(x.college||'')}</p><div><span class="rating-score">${Number(x.overall_rating||0).toFixed(1)}</span> <span class="stars">${stars(x.overall_rating)}</span></div><p>${esc(x.latest_comment||'')}</p></article>`).join(''):'<div class="empty">لا توجد تقييمات</div>'}
window.setKind=(k,b)=>{kind=k;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};
window.openSubmit=()=>$('#modal').classList.add('show');window.closeSubmit=()=>$('#modal').classList.remove('show');
window.submitRating=async()=>{const body={kind:$('#rKind').value,target_name:$('#rName').value.trim(),college:$('#rCollege').value.trim(),overall_rating:Number($('#rOverall').value),difficulty_rating:Number($('#rDifficulty').value),clarity_rating:Number($('#rClarity').value),exams_rating:Number($('#rExams').value),workload_rating:Number($('#rWorkload').value),comment:$('#rComment').value.trim(),status:'pending'};if(!body.target_name||!body.comment)return toast('أكمل الحقول المطلوبة',true);try{const created=await insert('rating_submissions',body);await notifyPending('rating_submissions',created?.[0]?.id);toast('تم الإرسال للمراجعة');closeSubmit()}catch(e){toast(e.message,true)}};
$('#search').addEventListener('input',render);(async()=>{try{rows=await get('rating_public_summary','select=*&order=overall_rating.desc');render()}catch(e){toast(e.message,true)}})();
