import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.110.8';
declare const Deno:any;
const URL=Deno.env.get('SUPABASE_URL')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,GEMINI=Deno.env.get('GEMINI_API_KEY')||'';
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
function validPublishable(req:Request){const key=req.headers.get('apikey')||'';if(!key)return false;try{const keys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}');return Object.values(keys).includes(key)}catch{return key===Deno.env.get('SUPABASE_ANON_KEY')}}
const allowed=new Set(['https://uonhub.space','https://www.uonhub.space']);
function origin(req:Request){const value=req.headers.get('origin')||'';try{const host=new URL(value).hostname;if(allowed.has(value)||(host.endsWith('.vercel.app')&&(host.startsWith('uon-')||host.startsWith('uon-hub-'))))return value}catch{}return'https://uonhub.space'}
function headers(req:Request){return{'access-control-allow-origin':origin(req),'access-control-allow-headers':'authorization, apikey, content-type, x-client-info','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'no-store','vary':'Origin'}}
function out(req:Request,body:any,status=200){return new Response(JSON.stringify(body),{status,headers:headers(req)})}
const uuid=(value:any)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value||''));
function imagePart(value:any){const match=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/.exec(String(value||''));if(!match)return null;return{inline_data:{mime_type:match[1],data:match[2]}}}
function clean(value:any,max=120){return String(value??'').replace(/\s+/g,' ').trim().slice(0,max)}
function normalizeDay(value:any){const raw=clean(value,30).replace(/[أإآ]/g,'ا');const map:any={'ح':'الأحد','الاحد':'الأحد','الأحد':'الأحد','Sunday':'الأحد','ن':'الاثنين','الاثنين':'الاثنين','Monday':'الاثنين','ث':'الثلاثاء','الثلاثاء':'الثلاثاء','Tuesday':'الثلاثاء','ر':'الأربعاء','الاربعاء':'الأربعاء','الأربعاء':'الأربعاء','Wednesday':'الأربعاء','خ':'الخميس','الخميس':'الخميس','Thursday':'الخميس'};return map[raw]||map[clean(value,30)]||''}
function normalize(data:any){const courses=(Array.isArray(data?.courses)?data.courses:[]).slice(0,12).map((course:any)=>({course_code:clean(course.course_code,40).toUpperCase().replace(/\s+/g,''),course_name:clean(course.course_name,120),sections:(Array.isArray(course.sections)?course.sections:[]).slice(0,30).map((section:any)=>({section_no:clean(section.section_no,20),instructor:clean(section.instructor,100),capacity:Math.max(0,Math.min(999,Number(section.capacity)||0)),enrolled:Math.max(0,Math.min(999,Number(section.enrolled)||0)),meetings:(Array.isArray(section.meetings)?section.meetings:[]).slice(0,8).map((meeting:any)=>({day:normalizeDay(meeting.day),start:clean(meeting.start,20),end:clean(meeting.end,20),room:clean(meeting.room,50)})).filter((meeting:any)=>meeting.day&&meeting.start&&meeting.end)})).filter((section:any)=>section.meetings.length)})).filter((course:any)=>course.course_code&&course.sections.length);return{courses}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(req)});if(req.method!=='POST')return out(req,{error:'method_not_allowed'},405);if(!validPublishable(req))return out(req,{error:'invalid_api_key'},401);try{const body=await req.json().catch(()=>({}));if(!uuid(body.session_id)||!uuid(body.client_token))return out(req,{error:'invalid_session'},400);const values=Array.isArray(body.images)?body.images:[];if(!values.length||values.length>10)return out(req,{error:'invalid_image_count'},400);if(values.reduce((sum:number,value:any)=>sum+String(value||'').length,0)>32_000_000)return out(req,{error:'images_too_large'},413);const parts=values.map(imagePart);if(parts.some((part:any)=>!part))return out(req,{error:'invalid_image'},400);const{data:allowedRate,error:rateError}=await db.rpc('uon_public_rate_allow',{p_action:'schedule_image_parse',p_target_key:body.client_token,p_limit:12,p_window_seconds:3600});if(rateError||!allowedRate)return out(req,{error:'rate_limited'},429);if(!GEMINI)return out(req,{error:'vision_unavailable'},503);const prompt='اقرأ صور جداول الشعب من EduWave بجامعة نزوى. استخرج فقط ما يظهر بوضوح ولا تخمّن. أعد JSON فقط: courses: [{course_code, course_name, sections:[{section_no,instructor,capacity,enrolled,meetings:[{day,start,end,room}]}]}]. اجمع الصور التابعة للمادة نفسها. حوّل اختصارات الأيام: ح=الأحد، ن=الاثنين، ث=الثلاثاء، ر=الأربعاء، خ=الخميس. اكتب الوقت بصيغة 24 ساعة HH:MM. إذا كان للشعبة يومان أو أكثر أنشئ meeting لكل يوم. لا تخلط بيانات صفوف مختلفة.';
const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent',{method:'POST',headers:{'x-goog-api-key':GEMINI,'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt},...parts]}],generationConfig:{temperature:0,responseMimeType:'application/json',maxOutputTokens:7000}}),signal:AbortSignal.timeout(45000)});const payload=await response.json().catch(()=>({}));if(!response.ok)return out(req,{error:'vision_provider_failed'},502);const text=payload?.candidates?.[0]?.content?.parts?.map((part:any)=>part.text||'').join('')||'';let parsed:any={};try{parsed=JSON.parse(text.replace(/^\`\`\`json\s*|\s*\`\`\`$/g,''))}catch{return out(req,{error:'invalid_vision_response'},502)}const result=normalize(parsed);if(!result.courses.length)return out(req,{error:'no_sections_found'},422);return out(req,{ok:true,...result})}catch(error){console.error(error);return out(req,{error:'parser_unavailable'},500)}});
