import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.110.8';
declare const Deno:any;
const URL=Deno.env.get('SUPABASE_URL')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,GEMINI=Deno.env.get('GEMINI_API_KEY')||'';
const MODEL='gemini-3.7-flash';
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
function validPublishable(req:Request){const key=req.headers.get('apikey')||'';if(!key)return false;try{const keys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}');return Object.values(keys).includes(key)}catch{return key===Deno.env.get('SUPABASE_ANON_KEY')}}
const allowedOrigins=new Set(['https://uonhub.space','https://www.uonhub.space']);
function allowedOrigin(req:Request){const value=req.headers.get('origin')||'';if(allowedOrigins.has(value))return value;try{const host=new URL(value).hostname;if(host.endsWith('.vercel.app')&&(host.startsWith('uon-')||host.startsWith('uon-hub-')))return value}catch{}return''}
function headers(req:Request){return{'access-control-allow-origin':allowedOrigin(req)||'https://uonhub.space','access-control-allow-headers':'authorization, apikey, content-type, x-client-info','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'no-store','vary':'Origin'}}
function out(req:Request,body:any,status=200){return new Response(JSON.stringify(body),{status,headers:headers(req)})}
const uuid=(value:any)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value||''));
function imagePart(value:any){const match=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/.exec(String(value||''));if(!match)return null;return{inlineData:{mimeType:match[1],data:match[2]}}}
function clean(value:any,max=120){return String(value??'').replace(/\s+/g,' ').trim().slice(0,max)}
function normalizeDay(value:any){const raw=clean(value,30).replace(/[أإآ]/g,'ا').toLowerCase();const map:any={'ح':'الأحد','الاحد':'الأحد','الأحد':'الأحد','sunday':'الأحد','sun':'الأحد','ن':'الاثنين','الاثنين':'الاثنين','monday':'الاثنين','mon':'الاثنين','ث':'الثلاثاء','الثلاثاء':'الثلاثاء','tuesday':'الثلاثاء','tue':'الثلاثاء','ر':'الأربعاء','الاربعاء':'الأربعاء','الأربعاء':'الأربعاء','wednesday':'الأربعاء','wed':'الأربعاء','خ':'الخميس','الخميس':'الخميس','thursday':'الخميس','thu':'الخميس'};return map[raw]||''}
function normalTime(value:any){const raw=clean(value,20).replace(/[.]/g,':').toLowerCase();const m=raw.match(/^(\d{1,2}):(\d{2})\s*(am|pm|ص|م)?$/i);if(!m)return'';let h=Number(m[1]),min=Number(m[2]);if(h>23||min>59)return'';const p=(m[3]||'').toLowerCase();if((p==='pm'||p==='م')&&h<12)h+=12;if((p==='am'||p==='ص')&&h===12)h=0;return`${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`}
function normalize(data:any,imageIndex:number){const source=Array.isArray(data?.courses)?data.courses:[];const courses=source.slice(0,12).map((course:any,index:number)=>({course_code:clean(course.course_code||course.code,40).toUpperCase().replace(/\s+/g,'')||`IMAGE-${imageIndex+1}-COURSE-${index+1}`,course_name:clean(course.course_name||course.name,120),sections:(Array.isArray(course.sections)?course.sections:[]).slice(0,30).map((section:any)=>({section_no:clean(section.section_no||section.number,20),instructor:clean(section.instructor||section.teacher,100),capacity:0,enrolled:Math.max(0,Math.min(999,Number(section.enrolled||section.students_no||0)||0)),meetings:(Array.isArray(section.meetings)?section.meetings:[]).slice(0,10).map((meeting:any)=>({day:normalizeDay(meeting.day),start:normalTime(meeting.start),end:normalTime(meeting.end),room:clean(meeting.room,50)})).filter((meeting:any)=>meeting.day&&meeting.start&&meeting.end&&meeting.end>meeting.start)})).filter((section:any)=>section.section_no&&section.meetings.length)})).filter((course:any)=>course.sections.length);return courses}
function parseJson(text:string){const cleaned=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(cleaned)}catch{const first=cleaned.indexOf('{'),last=cleaned.lastIndexOf('}');if(first>=0&&last>first)return JSON.parse(cleaned.slice(first,last+1));throw new Error('invalid_json')}}
const BASE_PROMPT='اقرأ لقطة شاشة واحدة من جدول الشعب المتاحة في EduWave بجامعة نزوى. استخرج كل الشعب والصفوف الظاهرة في هذه الصورة فقط ولا تخمّن. أعد JSON فقط بالشكل: {"courses":[{"course_code":"INFS-102","course_name":"اسم المادة","sections":[{"section_no":"1","instructor":"اسم المحاضر","capacity":0,"enrolled":22,"meetings":[{"day":"الأحد","start":"16:00","end":"16:50","room":"17A"}]}]}]}. مهم جدًا: Students No. = عدد الطلبة المسجلين فقط ويذهب إلى enrolled وليس السعة، واجعل capacity=0. الصور مأخوذة أصلًا من الشعب المتاحة فلا تستبعد أي شعبة بسبب عدد الطلبة. اختصارات الأيام: ح=الأحد، ن=الاثنين، ث=الثلاثاء، ر=الأربعاء، خ=الخميس. حوّل AM/PM إلى 24 ساعة HH:MM. إذا ظهر نفس وقتين أو يومين في صف الشعبة فسجلهما كـ meetings منفصلة. Building-Class أو Building/Class هو القاعة. إذا ظهر رمز المادة أعلى الصورة فاستخدمه كما هو. إذا لم يظهر رمز المادة اترك course_code فارغًا بدل التخمين. لا تخلط صفوف شعب مختلفة.';
async function callVisionOne(part:any,imageIndex:number){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),23000);try{const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`,{method:'POST',headers:{'x-goog-api-key':GEMINI,'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:`${BASE_PROMPT}\nهذه الصورة رقم ${imageIndex+1}.`},part]}],generationConfig:{temperature:0,responseMimeType:'application/json',maxOutputTokens:2400,thinkingConfig:{thinkingLevel:'low'}}}),signal:controller.signal});const payload=await response.json().catch(()=>({}));if(!response.ok){const detail=clean(payload?.error?.status||payload?.error?.message||'',180);throw new Error(`provider_${response.status}${detail?`_${detail}`:''}`)}const text=payload?.candidates?.[0]?.content?.parts?.map((item:any)=>item.text||'').join('')||'';if(!text)throw new Error('empty_response');return normalize(parseJson(text),imageIndex)}finally{clearTimeout(timer)}}
function mergeCourses(groups:any[][]){const map=new Map<string,any>();for(const courses of groups){for(const course of courses){const key=clean(course.course_code,40).toUpperCase()||`COURSE-${map.size+1}`;if(!map.has(key))map.set(key,{course_code:key,course_name:course.course_name||'',sections:[]});const target=map.get(key);if(!target.course_name&&course.course_name)target.course_name=course.course_name;for(const section of course.sections||[]){let current=target.sections.find((item:any)=>item.section_no===section.section_no);if(!current){current={section_no:section.section_no,instructor:section.instructor||'',capacity:0,enrolled:Number(section.enrolled||0),meetings:[]};target.sections.push(current)}else{if(!current.instructor&&section.instructor)current.instructor=section.instructor;current.enrolled=Math.max(Number(current.enrolled||0),Number(section.enrolled||0))}for(const meeting of section.meetings||[]){const mk=`${meeting.day}|${meeting.start}|${meeting.end}|${meeting.room||''}`;if(!current.meetings.some((item:any)=>`${item.day}|${item.start}|${item.end}|${item.room||''}`===mk))current.meetings.push(meeting)}}}}return[...map.values()].filter(course=>course.sections?.length).slice(0,30)}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(req)});if(req.method!=='POST')return out(req,{error:'method_not_allowed'},405);if(!allowedOrigin(req))return out(req,{error:'origin_not_allowed'},403);if(!validPublishable(req))return out(req,{error:'invalid_api_key'},401);try{const body=await req.json().catch(()=>({}));if(!uuid(body.session_id)||!uuid(body.client_token))return out(req,{error:'invalid_session'},400);const values=Array.isArray(body.images)?body.images:[];if(!values.length||values.length>10)return out(req,{error:'invalid_image_count'},400);if(values.reduce((sum:number,value:any)=>sum+String(value||'').length,0)>24_000_000)return out(req,{error:'images_too_large'},413);const parts=values.map(imagePart);if(parts.some((part:any)=>!part))return out(req,{error:'invalid_image'},400);const{data:allowedRate,error:rateError}=await db.rpc('uon_public_rate_allow',{p_action:'schedule_image_parse',p_target_key:body.client_token,p_limit:20,p_window_seconds:3600});if(rateError||!allowedRate)return out(req,{error:'rate_limited'},429);if(!GEMINI)return out(req,{error:'vision_unavailable'},503);const settled=await Promise.allSettled((parts as any[]).map((part,index)=>callVisionOne(part,index)));const groups:any[][]=[];const errors:string[]=[];settled.forEach((item,index)=>{if(item.status==='fulfilled'&&item.value.length)groups.push(item.value);else if(item.status==='rejected')errors.push(`image_${index+1}:${clean((item.reason as Error)?.message||item.reason,100)}`)});const courses=mergeCourses(groups);if(!courses.length){const timedOut=errors.some(error=>/abort|timeout/i.test(error));return out(req,{error:timedOut?'vision_timeout':'no_sections_found',image_errors:errors.slice(0,10)},timedOut?504:422)}return out(req,{ok:true,model:MODEL,courses,images_total:values.length,images_read:groups.length,partial:groups.length<values.length,image_errors:errors.slice(0,10)})}catch(error){console.error(error);return out(req,{error:'parser_unavailable'},500)}});
