import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.110.8';
import {extractText} from 'npm:unpdf@1.2.2';
import mammoth from 'npm:mammoth@1.8.0';
const URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(URL,KEY,{auth:{persistSession:false}});
const OFFICIAL='https://www.unizwa.edu.om/program_details.php?contentid=1&lang=en';
const clean=(s:string)=>s.replace(/\s+/g,' ').trim();
const abs=(href:string)=>new URL(href,'https://www.unizwa.edu.om/').toString();
async function docText(url:string){const r=await fetch(url,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw new Error(`download_${r.status}`);const b=new Uint8Array(await r.arrayBuffer());if(/\.pdf(?:$|\?)/i.test(url)){const x:any=await extractText(b,{mergePages:true});return String(x?.text||x||'')}if(/\.docx?(?:$|\?)/i.test(url)){const x:any=await mammoth.extractRawText({arrayBuffer:b.buffer});return String(x.value||'')}return new TextDecoder().decode(b)}
function requirement(text:string){const s=text.toLowerCase();if(/university requirement|متطلبات الجامعة/.test(s))return'university';if(/college requirement|متطلبات الكلية/.test(s))return'college';if(/elective|اختياري/.test(s))return'elective';return'major'}
function parse(text:string,source:string){const lines=text.split(/\r?\n/).map(clean).filter(Boolean);const out:any[]=[];for(let i=0;i<lines.length;i++){const matches=[...lines[i].matchAll(/\b([A-Z]{2,8})\s*[- ]?\s*(\d{2,4}[A-Z]?)\b/g)];for(const m of matches){const code=(m[1]+m[2]).toUpperCase(),near=clean(lines.slice(Math.max(0,i-1),Math.min(lines.length,i+3)).join(' '));const name=clean(lines[i].replace(m[0],'').replace(/^[-–—:|\d. ]+|[-–—:|\d. ]+$/g,''));const h=near.match(/\b([1-6])\s*(?:cr|credit|hours?|ساعة|ساعات)\b/i);out.push({code,name_en:name&&name.length<160?name:null,credit_hours:h?Number(h[1]):null,requirement_type:requirement(near),source_url:source})}}return out}
Deno.serve(async req=>{try{const auth=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(auth!==KEY)return new Response(JSON.stringify({error:'unauthorized'}),{status:401});const html=await (await fetch(OFFICIAL)).text();const links=[...html.matchAll(/href=["']([^"']+\.(?:pdf|docx?)(?:\?[^"']*)?)["']/gi)].map(x=>abs(x[1]));const unique=[...new Set(links)].filter(x=>/study|plan|degree/i.test(x)).slice(0,150);let inserted=0,updated=0,duplicates=0,failed=0;const seen=new Set<string>();for(const link of unique){try{const rows=parse(await docText(link),link);for(const row of rows){if(seen.has(row.code)){duplicates++;continue}seen.add(row.code);const {data:old}=await db.from('courses').select('id,name_en,credit_hours').eq('code',row.code).maybeSingle();const payload={code:row.code,name_ar:old?.name_en||row.name_en||row.code,name_en:row.name_en||old?.name_en||row.code,credit_hours:row.credit_hours||old?.credit_hours||null,requirement_type:row.requirement_type,source_url:row.source_url,active:true,status:'approved',updated_at:new Date().toISOString()};const {error}=await db.from('courses').upsert(payload,{onConflict:'code'});if(error)throw error;old?updated++:inserted++}}catch{failed++}}return new Response(JSON.stringify({ok:true,sources:unique.length,inserted,updated,duplicates,failed}),{headers:{'content-type':'application/json'}})}catch(e){return new Response(JSON.stringify({ok:false,error:String((e as Error).message||e)}),{status:500,headers:{'content-type':'application/json'}})}});
