declare const Deno: any;
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const PUBLIC_KEY = Deno.env.get('SUPABASE_ANON_KEY') || Deno.env.get('SUPABASE_PUBLISHABLE_KEY') || '';
const CONNECTOR_SECRET = Deno.env.get('UON_AI_CONNECTOR_SECRET') || '';
const BASE = `${SUPABASE_URL}/functions/v1/uon-ai-chat`;
const GOOGLE = `${SUPABASE_URL}/functions/v1/uon-ai-google-v64`;
const allowed = new Set(['https://uonhub.space', 'https://www.uonhub.space']);
function origin(req: Request) { const value=req.headers.get('origin')||''; try{const host=new URL(value).hostname;if(allowed.has(value)||(host.endsWith('.vercel.app')&&(host.startsWith('uon-')||host.startsWith('uon-hub-'))))return value}catch{} return 'https://uonhub.space'; }
function headers(req: Request) { return {'Access-Control-Allow-Origin':origin(req),'Access-Control-Allow-Headers':'content-type, authorization, apikey, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',Vary:'Origin'}; }
function clean(v: unknown,n=1000){return String(v??'').replace(/\s+/g,' ').trim().slice(0,n)}
function norm(v: unknown){return clean(v).toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي')}
function placeIntent(q: string){const n=norm(q);return /(وين|اين|أين|موقع|خريط|قريب|اقرب|أقرب|طريق|اتجاه|مطعم|مقهى|كافيه|صيدليه|صيدلية|مطبعه|مطبعة|بنك|صراف|سوبرماركت|محل|مستشفى|عياده|عيادة|مسجد|مواقف|محطه|محطة|where|near|nearby|map|maps|directions|restaurant|cafe|pharmacy|bank|atm|hospital|clinic)/i.test(n)}
function googleQuery(question:string){const q=clean(question,220);if(/جامعه نزوى|جامعة نزوى|university of nizwa|uon/i.test(q))return q;return `${q} near University of Nizwa Oman`}
function mapsSearchUrl(question:string){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(googleQuery(question))}`}
function mapsDirectionsUrl(question:string){return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent('University of Nizwa, Oman')}&destination=${encodeURIComponent(googleQuery(question))}`}
async function callBase(req:Request,body:any){const r=await fetch(BASE,{method:'POST',headers:{'content-type':'application/json','Origin':origin(req),...(PUBLIC_KEY?{apikey:PUBLIC_KEY,Authorization:`Bearer ${PUBLIC_KEY}`}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(16000)});const text=await r.text();let data:any={};try{data=JSON.parse(text)}catch{}return{r,text,data}}
async function callGoogle(question:string){if(!CONNECTOR_SECRET)return null;try{const r=await fetch(GOOGLE,{method:'POST',headers:{'content-type':'application/json','x-connector-secret':CONNECTOR_SECRET},body:JSON.stringify({query:googleQuery(question),limit:5}),signal:AbortSignal.timeout(8000)});return r.ok?await r.json():null}catch{return null}}
function fallback(base:any,question:string,lang:string){const search=mapsSearchUrl(question),directions=mapsDirectionsUrl(question),links=[...(Array.isArray(base?.links)?base.links:[])];if(!links.some((x:any)=>x?.url===search))links.push({type:'Google Maps',title:lang==='en'?'Search in Google Maps':'البحث في Google Maps',url:search,official:false,provider:'google_maps_fallback'});if(!links.some((x:any)=>x?.url===directions))links.push({type:'Google Maps',title:lang==='en'?'Directions from University of Nizwa':'الاتجاهات من جامعة نزوى',url:directions,official:false,provider:'google_maps_fallback'});return{...base,links:links.slice(0,10),connectors:{...(base?.connectors||{}),google_maps:{used:false,live:false,fallback:true,attribution:'Google Maps',reason:CONNECTOR_SECRET?'places_unavailable':'connector_not_configured'}}}}
function merge(base:any,google:any,lang:string,question:string){if(!google?.available||!Array.isArray(google.places)||!google.places.length)return fallback(base,question,lang);const places=google.places.slice(0,5);const lines=places.slice(0,3).map((p:any,i:number)=>`${i+1}. ${clean(p.name,160)}${p.address?` — ${clean(p.address,240)}`:''}${typeof p.open_now==='boolean'?` — ${p.open_now?(lang==='en'?'open now':'مفتوح الآن'):(lang==='en'?'closed now':'مغلق الآن')}`:''}`);
 const prefix=lang==='en'?'Live Google Maps options:':'خيارات مباشرة من Google Maps:';const answer=clean(base?.answer,5200);const mergedAnswer=`${answer}${answer?'\n\n':''}${prefix}\n${lines.join('\n')}`.trim();
 const links=[...(Array.isArray(base?.links)?base.links:[])];for(const p of places){if(p.maps_url&&!links.some((x:any)=>x?.url===p.maps_url))links.push({type:'Google Maps',title:p.name,url:p.maps_url,official:false,provider:'google_maps'})}const directions=mapsDirectionsUrl(question);if(!links.some((x:any)=>x?.url===directions))links.push({type:'Google Maps',title:lang==='en'?'Directions from University of Nizwa':'الاتجاهات من جامعة نزوى',url:directions,official:false,provider:'google_maps'});
 return{...base,answer:mergedAnswer,links:links.slice(0,10),google_places:places.map((p:any)=>({...p,provider:'Google Maps'})),connectors:{...(base?.connectors||{}),google_maps:{used:true,live:true,count:places.length,attribution:'Google Maps'}},sources_count:Number(base?.sources_count||0)+places.length,grounded:true,confidence:Math.max(Number(base?.confidence||0),.82)} }
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(req)});if(req.method!=='POST')return new Response(JSON.stringify({error:'method_not_allowed'}),{status:405,headers:headers(req)});try{const body=await req.json().catch(()=>({}));const question=clean(body.question,800);if(body.action==='history'||body.action==='feedback'||!question){const base=await callBase(req,body);return new Response(base.text,{status:base.r.status,headers:headers(req)})}
 const useGoogle=placeIntent(question);const [base,google]=await Promise.all([callBase(req,body),useGoogle?callGoogle(question):Promise.resolve(null)]);if(!base.r.ok)return new Response(base.text,{status:base.r.status,headers:headers(req)});const lang=body.language==='en'?'en':'ar';const result=useGoogle?merge(base.data,google,lang,question):base.data;return new Response(JSON.stringify(result),{status:200,headers:headers(req)})}catch(e){console.error('uon-ai-chat-v64',e);return new Response(JSON.stringify({error:'assistant_unavailable'}),{status:500,headers:headers(req)})}});
