declare const Deno: any;
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const PUBLIC_KEY = Deno.env.get('SUPABASE_ANON_KEY') || Deno.env.get('SUPABASE_PUBLISHABLE_KEY') || '';
const CONNECTOR_SECRET = Deno.env.get('UON_AI_CONNECTOR_SECRET') || '';
const BASE = `${SUPABASE_URL}/functions/v1/uon-ai-chat`;
const GOOGLE = `${SUPABASE_URL}/functions/v1/uon-ai-google-v64`;
const PERSONAL = `${SUPABASE_URL}/functions/v1/uon-google-account-v64`;
const allowed = new Set(['https://uonhub.space', 'https://www.uonhub.space']);
function origin(req: Request) { const value=req.headers.get('origin')||''; try{const host=new URL(value).hostname;if(allowed.has(value)||(host.endsWith('.vercel.app')&&(host.startsWith('uon-')||host.startsWith('uon-hub-'))))return value}catch{} return 'https://uonhub.space'; }
function headers(req: Request) { return {'Access-Control-Allow-Origin':origin(req),'Access-Control-Allow-Headers':'content-type, authorization, apikey, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',Vary:'Origin'}; }
function clean(v: unknown,n=1000){return String(v??'').replace(/\s+/g,' ').trim().slice(0,n)}
function norm(v: unknown){return clean(v).toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي')}
function physicalPlaceIntent(q:string){return /(مبنى|المبنى|قاعة|قاعه|مختبر|مكتب|خريط|قريب|اقرب|أقرب|طريق|اتجاه|مطعم|مقهى|كافيه|صيدليه|صيدلية|مطبعه|مطبعة|بنك|صراف|سوبرماركت|محل|مستشفى|عياده|عيادة|مسجد|مواقف|محطه|محطة|building|room|lab|near|nearby|map|maps|directions|restaurant|cafe|pharmacy|bank|atm|hospital|clinic)/i.test(norm(q))}
function informationalIntent(q:string){const n=norm(q);return /(تقويم|اكاديمي|برامج|برنامج|تخصص|كليه|كلية|لائحه|لائحة|سياسه|سياسة|تسجيل|قبول|رابط|بوابه|بوابة|موقع الكتروني|موقع إلكتروني|calendar|academic|programs|program|major|policy|registration|admission|link|portal)/i.test(n)}
function placeIntent(q:string){const n=norm(q);if(physicalPlaceIntent(q))return true;if(informationalIntent(q))return false;return /(وين|اين|أين|موقع|where|location)/i.test(n)}
function canonicalBaseQuestion(q0:string){let q=clean(q0,800);const n=norm(q);if(informationalIntent(q)&&!physicalPlaceIntent(q)){q=q.replace(/^\s*(?:وين|اين|أين|where)\s+(?:(?:ألقى|القى|احصل|أحصل|اجد|أجد|find|get)\s+)?/i,'').trim()||q;if(/برامج|programs/i.test(n)&&!/\bبرنامج\b/.test(n))q=`${q} برنامج تخصص`;if(/تقويم|calendar/i.test(n)&&!/اكاديمي|أكاديمي|academic/i.test(n))q=`${q} تقويم أكاديمي`;}
 return clean(q,800)}
function privateIntent(q0:string){const q=norm(q0);if(/تقويم.*(اكاديمي|الجامعه)|academic calendar|university calendar/.test(q))return'';if(/تقويمي|مواعيدي|مواعيد.*جوجل|جوجل.*مواعيد|google calendar|my calendar|وش عندي.*(تقويم|جوجل)|ايش عندي.*(تقويم|جوجل)|ويش عندي.*(تقويم|جوجل)/.test(q))return'calendar';if(/ملفاتي.*(درايف|drive)|ملفات.*(درايف|drive)|درايف.*ملف|google drive|my drive|وش عندي.*(درايف|drive)|افتح.*(درايف|drive)/.test(q))return'drive';return''}
function googleQuery(question:string){const q=clean(question,220);if(/جامعه نزوى|جامعة نزوى|university of nizwa|uon/i.test(q))return q;return `${q} near University of Nizwa Oman`}
function mapsSearchUrl(question:string){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(googleQuery(question))}`}
function mapsDirectionsUrl(question:string){return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent('University of Nizwa, Oman')}&destination=${encodeURIComponent(googleQuery(question))}`}
async function callBase(req:Request,body:any){const r=await fetch(BASE,{method:'POST',headers:{'content-type':'application/json','Origin':origin(req),...(PUBLIC_KEY?{apikey:PUBLIC_KEY,Authorization:`Bearer ${PUBLIC_KEY}`}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(16000)});const text=await r.text();let data:any={};try{data=JSON.parse(text)}catch{}return{r,text,data}}
async function callGoogle(question:string){if(!CONNECTOR_SECRET)return null;try{const r=await fetch(GOOGLE,{method:'POST',headers:{'content-type':'application/json','x-connector-secret':CONNECTOR_SECRET},body:JSON.stringify({query:googleQuery(question),limit:5}),signal:AbortSignal.timeout(8000)});return r.ok?await r.json():null}catch{return null}}
async function callPersonal(req:Request,action:string){const auth=req.headers.get('authorization')||'';if(!/^Bearer\s+\S+/i.test(auth))return{ok:false,status:401,data:{error:'auth_required'}};try{const r=await fetch(PERSONAL,{method:'POST',headers:{'content-type':'application/json',Authorization:auth,...(PUBLIC_KEY?{apikey:PUBLIC_KEY}:{})},body:JSON.stringify({action}),signal:AbortSignal.timeout(10000)});const data=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,data}}catch{return{ok:false,status:503,data:{error:'google_private_unavailable'}}}}
function fallback(base:any,question:string,lang:string){const search=mapsSearchUrl(question),directions=mapsDirectionsUrl(question),links=[...(Array.isArray(base?.links)?base.links:[])];if(!links.some((x:any)=>x?.url===search))links.push({type:'Google Maps',title:lang==='en'?'Search in Google Maps':'البحث في Google Maps',url:search,official:false,provider:'google_maps_fallback'});if(!links.some((x:any)=>x?.url===directions))links.push({type:'Google Maps',title:lang==='en'?'Directions from University of Nizwa':'الاتجاهات من جامعة نزوى',url:directions,official:false,provider:'google_maps_fallback'});return{...base,links:links.slice(0,10),connectors:{...(base?.connectors||{}),google_maps:{used:false,live:false,fallback:true,attribution:'Google Maps',reason:CONNECTOR_SECRET?'places_unavailable':'connector_not_configured'}}}}
function merge(base:any,google:any,lang:string,question:string){if(!google?.available||!Array.isArray(google.places)||!google.places.length)return fallback(base,question,lang);const places=google.places.slice(0,5);const lines=places.slice(0,3).map((p:any,i:number)=>`${i+1}. ${clean(p.name,160)}${p.address?` — ${clean(p.address,240)}`:''}${typeof p.open_now==='boolean'?` — ${p.open_now?(lang==='en'?'open now':'مفتوح الآن'):(lang==='en'?'closed now':'مغلق الآن')}`:''}`);const prefix=lang==='en'?'Live Google Maps options:':'خيارات مباشرة من Google Maps:';const answer=clean(base?.answer,5200);const mergedAnswer=`${answer}${answer?'\n\n':''}${prefix}\n${lines.join('\n')}`.trim();const links=[...(Array.isArray(base?.links)?base.links:[])];for(const p of places){if(p.maps_url&&!links.some((x:any)=>x?.url===p.maps_url))links.push({type:'Google Maps',title:p.name,url:p.maps_url,official:false,provider:'google_maps'})}const directions=mapsDirectionsUrl(question);if(!links.some((x:any)=>x?.url===directions))links.push({type:'Google Maps',title:lang==='en'?'Directions from University of Nizwa':'الاتجاهات من جامعة نزوى',url:directions,official:false,provider:'google_maps'});return{...base,answer:mergedAnswer,links:links.slice(0,10),google_places:places.map((p:any)=>({...p,provider:'Google Maps'})),connectors:{...(base?.connectors||{}),google_maps:{used:true,live:true,count:places.length,attribution:'Google Maps'}},sources_count:Number(base?.sources_count||0)+places.length,grounded:true,confidence:Math.max(Number(base?.confidence||0),.82)}}
function connectRequired(lang:string,error='not_connected'){return{answer:lang==='en'?'Connect your Google account first. Calendar and Drive access is optional and stays private to your account.':'اربط حساب Google أولًا. ربط Calendar وDrive اختياري، وبياناتك تظل خاصة بحسابك وما تدخل قاعدة المعرفة العامة.',links:[{type:'Google',title:lang==='en'?'Connect Google':'ربط Google',url:'/google-connect.html',official:false}],actions:[],suggestions:[],grounded:false,confidence:.99,sources_count:0,mode:'google_connect_required',connectors:{google_account:{used:false,private:true,error}}}}
function muscatDay(v:any){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Muscat',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v))}catch{return''}}
function eventTime(v:any,lang:string){try{return new Intl.DateTimeFormat(lang==='en'?'en-OM':'ar-OM',{timeZone:'Asia/Muscat',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))}catch{return clean(v,80)}}
function privateCalendar(data:any,question:string,lang:string){let events=Array.isArray(data?.events)?data.events:[];const n=norm(question);if(/اليوم|today/.test(n)){const today=muscatDay(new Date());events=events.filter((e:any)=>muscatDay(e.start)===today)}events=events.slice(0,8);if(!events.length)return{answer:lang==='en'?'No matching upcoming Google Calendar events were found.':'ما حصلت مواعيد مطابقة وقادمة في Google Calendar حاليًا.',links:[{type:'Google',title:lang==='en'?'Google settings':'إعدادات Google',url:'/google-connect.html',official:false}],grounded:true,confidence:.99,sources_count:1,mode:'google_calendar_private',connectors:{google_account:{used:true,private:true,service:'calendar'}}};const lines=events.map((e:any,i:number)=>`${i+1}. ${clean(e.summary,180)} — ${eventTime(e.start,lang)}${e.location?` — ${clean(e.location,180)}`:''}`);return{answer:(lang==='en'?`Your upcoming Google Calendar events:\n`:`مواعيدك القادمة في Google Calendar:\n`)+lines.join('\n'),links:events.filter((e:any)=>e.url).slice(0,4).map((e:any)=>({type:'Google',title:clean(e.summary,120),url:e.url,official:false})),grounded:true,confidence:.99,sources_count:1,mode:'google_calendar_private',connectors:{google_account:{used:true,private:true,service:'calendar',count:events.length}}}}
function privateDrive(data:any,lang:string){const files=(Array.isArray(data?.files)?data.files:[]).slice(0,10);if(!files.length)return{answer:lang==='en'?'No Google Drive files are currently authorized for UON Hub. The app uses drive.file rather than access to your whole Drive.':'ما فيه ملفات Google Drive مصرح بها لـUON Hub حاليًا. التطبيق يستخدم drive.file وما عنده وصول لكل ملفاتك.',links:[{type:'Google',title:lang==='en'?'Google settings':'إعدادات Google',url:'/google-connect.html',official:false}],grounded:true,confidence:.99,sources_count:1,mode:'google_drive_private',connectors:{google_account:{used:true,private:true,service:'drive'}}};const lines=files.map((f:any,i:number)=>`${i+1}. ${clean(f.name,200)}`);return{answer:(lang==='en'?`Drive files available to UON Hub:\n`:`ملفات Drive المتاحة لـUON Hub:\n`)+lines.join('\n'),links:files.filter((f:any)=>f.url).slice(0,4).map((f:any)=>({type:'Google',title:clean(f.name,120),url:f.url,official:false})),grounded:true,confidence:.99,sources_count:1,mode:'google_drive_private',connectors:{google_account:{used:true,private:true,service:'drive',count:files.length}}}}
async function privateAnswer(req:Request,intent:string,question:string,lang:string){const result=await callPersonal(req,intent==='calendar'?'calendar-upcoming':'drive-files');if(!result.ok){const err=clean(result.data?.error,100);if(result.status===401||['google_not_connected','google_reconnect_required','calendar_scope_missing','drive_scope_missing','invalid_session','auth_required'].includes(err))return connectRequired(lang,err||'not_connected');return{answer:lang==='en'?'Google is temporarily unavailable. Your other UON AI features still work normally.':'تعذر الوصول إلى Google مؤقتًا. باقي ميزات UON AI تشتغل بشكل طبيعي.',links:[{type:'Google',title:lang==='en'?'Google settings':'إعدادات Google',url:'/google-connect.html',official:false}],grounded:false,confidence:.7,sources_count:0,mode:'google_private_unavailable',connectors:{google_account:{used:false,private:true,error:err||'unavailable'}}}}return intent==='calendar'?privateCalendar(result.data,question,lang):privateDrive(result.data,lang)}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(req)});if(req.method!=='POST')return new Response(JSON.stringify({error:'method_not_allowed'}),{status:405,headers:headers(req)});try{const body=await req.json().catch(()=>({}));const question=clean(body.question,800);if(body.action==='history'||body.action==='feedback'||!question){const base=await callBase(req,body);return new Response(base.text,{status:base.r.status,headers:headers(req)})}const lang=body.language==='en'?'en':'ar';const pIntent=privateIntent(question);if(pIntent){const result=await privateAnswer(req,pIntent,question,lang);return new Response(JSON.stringify(result),{status:200,headers:headers(req)})}const useGoogle=placeIntent(question);const baseBody={...body,question:canonicalBaseQuestion(question)};const [base,google]=await Promise.all([callBase(req,baseBody),useGoogle?callGoogle(question):Promise.resolve(null)]);if(!base.r.ok)return new Response(base.text,{status:base.r.status,headers:headers(req)});const result=useGoogle?merge(base.data,google,lang,question):base.data;if(baseBody.question!==question)result.resolved_question=baseBody.question;return new Response(JSON.stringify(result),{status:200,headers:headers(req)})}catch(e){console.error('uon-ai-chat-v64',e);return new Response(JSON.stringify({error:'assistant_unavailable'}),{status:500,headers:headers(req)})}});
