create table if not exists public.university_programs (
  id bigint generated by default as identity primary key,
  source_key text unique,
  college text not null,
  degree text not null default 'برنامج',
  name_ar text not null,
  name_en text,
  official_url text,
  study_plan_url text,
  source_updated_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.university_programs add column if not exists source_key text;
alter table public.university_programs add column if not exists source_updated_at timestamptz;
create unique index if not exists university_programs_source_key_idx
  on public.university_programs(source_key) where source_key is not null;

create table if not exists public.university_guide_syncs (
  id bigint generated by default as identity primary key,
  source_url text not null,
  programs_count integer not null default 0,
  status text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.university_programs enable row level security;
alter table public.university_guide_syncs enable row level security;

drop policy if exists "Public read active university programs" on public.university_programs;
create policy "Public read active university programs"
on public.university_programs for select
to anon, authenticated
using (active = true);

drop policy if exists "Public read university sync status" on public.university_guide_syncs;
create policy "Public read university sync status"
on public.university_guide_syncs for select
to anon, authenticated
using (true);
