-- V31.6 official academic catalog and study-plan synchronization
create extension if not exists pgcrypto;
create table if not exists public.academic_colleges(id uuid primary key default gen_random_uuid(),name_ar text not null unique,name_en text not null,sort_order int not null default 100,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.academic_departments(id uuid primary key default gen_random_uuid(),college_id uuid not null references public.academic_colleges(id) on delete cascade,name_ar text not null,name_en text not null,sort_order int not null default 100,active boolean not null default true,unique(college_id,name_ar));
create table if not exists public.academic_programs(id uuid primary key default gen_random_uuid(),college_id uuid not null references public.academic_colleges(id) on delete cascade,department_id uuid references public.academic_departments(id) on delete set null,name_ar text not null,name_en text not null,degree_ar text,degree_en text,official_url text,sort_order int not null default 100,active boolean not null default true,unique(college_id,name_ar,degree_ar));
create table if not exists public.course_programs(course_code text not null references public.courses(code) on update cascade on delete cascade,program_id uuid not null references public.academic_programs(id) on delete cascade,requirement_type text not null default 'major' check(requirement_type in ('university','college','major','elective')),semester_no int,source_url text,primary key(course_code,program_id,requirement_type));
alter table public.courses add column if not exists college_ar text; alter table public.courses add column if not exists college_en text; alter table public.courses add column if not exists department_ar text; alter table public.courses add column if not exists department_en text; alter table public.courses add column if not exists requirement_type text default 'major'; alter table public.courses add column if not exists source_url text;
insert into public.academic_colleges(name_ar,name_en,sort_order) values
('كلية العلوم والآداب','College of Arts and Sciences',10),('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems',20),('كلية الهندسة والعمارة','College of Engineering and Architecture',30),('كلية العلوم الصحية','College of Health Sciences',40) on conflict(name_ar) do update set name_en=excluded.name_en,sort_order=excluded.sort_order,active=true;
with src(college_ar,college_en,department_ar,department_en,program_ar,program_en,degree_ar,official_url) as (values
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','علوم الحاسب','Computer Science','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','الإحصاء','Statistics','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','الرياضيات','Mathematics','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','الفيزياء','Physics','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','التقنية الحيوية','Biotechnology','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','الكيمياء','Chemistry','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة العربية','Arabic Language','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة الإنجليزية والترجمة','English Language and Translation','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة الفرنسية والترجمة','French Language and Translation','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة الألمانية والترجمة','German Language and Translation','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','علوم الحاسب','Computer Science','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','الإحصاء','Statistics','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','الرياضيات','Mathematics','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','الفيزياء','Physics','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','التقنية الحيوية','Biotechnology','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم العلوم الطبيعية والتطبيقية','Department of Natural and Applied Sciences','الكيمياء','Chemistry','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة العربية','Arabic Language','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة الإنجليزية والترجمة','English Language and Translation','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة الفرنسية والترجمة','French Language and Translation','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة الألمانية والترجمة','German Language and Translation','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية في علوم الحاسب','Computer Science Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية في الرياضيات','Mathematics Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية في الفيزياء','Physics Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية في الأحياء','Biology Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية في الكيمياء','Chemistry Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية في اللغة العربية','Arabic Language Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية في اللغة الإنجليزية','English Language Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية الخاصة','Special Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','رياض الأطفال','Kindergarten Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','التربية الفنية','Art Education','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','الإدارة التربوية','Educational Administration','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم التربية والدراسات الإنسانية','Department of Education and Humanities','الإرشاد النفسي','Psychological Counseling','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة العربية وآدابها','Arabic Language and Literature','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم والآداب','College of Arts and Sciences','قسم اللغات والترجمة','Department of Languages and Translation','اللغة الإنجليزية','English Language','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','المحاسبة','Accounting','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','إدارة الأعمال','Business Administration','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','الاقتصاد والتمويل','Economics and Finance','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','التجارة والتمويل الدولي','International Trade and Finance','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','التسويق','Marketing','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','إدارة السياحة والمرافق الترفيهية','Tourism and Recreational Facilities Management','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم نظم المعلومات','Department of Information Systems','نظم المعلومات','Information Systems','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم نظم المعلومات','Department of Information Systems','تصميم الويب وأمن المعلومات','Web Design and Information Security','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','المحاسبة','Accounting','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','إدارة الأعمال','Business Administration','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','الاقتصاد والتمويل – الإدارة المالية','Economics and Finance – Financial Management','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','الاقتصاد والتمويل – الاقتصاد الدولي','Economics and Finance – International Economics','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','الاقتصاد والتمويل – الصيرفة والتمويل الإسلامي','Economics and Finance – Islamic Banking and Finance','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','الاقتصاد والتمويل – اقتصاد الموارد الطبيعية','Economics and Finance – Natural Resource Economics','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','التجارة والتمويل الدولي','International Trade and Finance','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','التسويق','Marketing','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','إدارة السياحة والترفيه','Tourism and Recreational Management','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم نظم المعلومات','Department of Information Systems','إدارة العمليات','Operations Management','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم نظم المعلومات','Department of Information Systems','نظم المعلومات','Information Systems','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم نظم المعلومات','Department of Information Systems','تصميم الويب وأمن المعلومات','Web Design and Information Security','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','المحاسبة','Accounting','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','إدارة الأعمال','Business Administration','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','الماجستير التنفيذي في إدارة الأعمال','Executive Master of Business Administration','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','الاقتصاد','Economics','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم نظم المعلومات','Department of Information Systems','نظم المعلومات','Information Systems','ماجستير','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الاقتصاد والإدارة ونظم المعلومات','College of Economics, Management and Information Systems','قسم الإدارة والاقتصاد','Department of Management and Economics','دكتوراه الفلسفة في دراسات الأعمال','Ph.D. in Business Studies','دكتوراه','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','تقنيات الهندسة الكيميائية والبتروكيماوية','Chemical and Petrochemical Technologies','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم العمارة والتصميم الداخلي','Department of Architecture and Interior Design','العمارة','Architecture','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','التقنيات الكهربائية','Electrical Technologies','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','تقنيات هندسة الحاسب','Computer Technologies','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','التقنيات المدنية','Civil Technologies','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','التقنيات البيئية','Environmental Technologies','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم العمارة والتصميم الداخلي','Department of Architecture and Interior Design','تقنيات التصميم الداخلي','Interior Design Technologies','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','الهندسة الكيميائية والبتروكيماوية','Chemical and Petrochemical Engineering','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','الهندسة المعمارية','Architectural Engineering','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','الهندسة الكهربائية','Electrical Engineering','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','هندسة الحاسب','Computer Engineering','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','الهندسة المدنية','Civil Engineering','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم الهندسة','Department of Engineering','الهندسة البيئية','Environmental Engineering','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية الهندسة والعمارة','College of Engineering and Architecture','قسم العمارة والتصميم الداخلي','Department of Architecture and Interior Design','هندسة التصميم الداخلي','Interior Design Engineering','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم الصحية','College of Health Sciences','قسم العلوم الصحية','Department of Health Sciences','الصيدلة','Pharmacy','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم الصحية','College of Health Sciences','قسم العلوم الصحية','Department of Health Sciences','التمريض','Nursing','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم الصحية','College of Health Sciences','قسم العلوم الصحية','Department of Health Sciences','التجسير في الصيدلة','Bridging Pharmacy Diploma','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم الصحية','College of Health Sciences','قسم العلوم الصحية','Department of Health Sciences','التجسير في التمريض','Bridging Nursing Diploma','دبلوم','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم الصحية','College of Health Sciences','قسم العلوم الصحية','Department of Health Sciences','الصيدلة','Pharmacy','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en'),
('كلية العلوم الصحية','College of Health Sciences','قسم العلوم الصحية','Department of Health Sciences','التمريض','Nursing','بكالوريوس','https://www.unizwa.edu.om/index.php?contentid=619&lang=en')
), deps as (insert into public.academic_departments(college_id,name_ar,name_en,sort_order) select distinct c.id,s.department_ar,s.department_en,100 from src s join public.academic_colleges c on c.name_ar=s.college_ar on conflict(college_id,name_ar) do update set name_en=excluded.name_en,active=true returning id,college_id,name_ar)
insert into public.academic_programs(college_id,department_id,name_ar,name_en,degree_ar,degree_en,official_url,sort_order) select c.id,d.id,s.program_ar,s.program_en,s.degree_ar,case s.degree_ar when 'دبلوم' then 'Diploma' when 'بكالوريوس' then 'Bachelor' when 'ماجستير' then 'Master' else s.degree_ar end,s.official_url,100 from src s join public.academic_colleges c on c.name_ar=s.college_ar join public.academic_departments d on d.college_id=c.id and d.name_ar=s.department_ar on conflict(college_id,name_ar,degree_ar) do update set department_id=excluded.department_id,name_en=excluded.name_en,degree_en=excluded.degree_en,official_url=excluded.official_url,active=true;
alter table public.academic_colleges enable row level security; alter table public.academic_departments enable row level security; alter table public.academic_programs enable row level security; alter table public.course_programs enable row level security;
drop policy if exists public_read_colleges on public.academic_colleges; create policy public_read_colleges on public.academic_colleges for select using(active);
drop policy if exists public_read_departments on public.academic_departments; create policy public_read_departments on public.academic_departments for select using(active);
drop policy if exists public_read_programs on public.academic_programs; create policy public_read_programs on public.academic_programs for select using(active);
drop policy if exists public_read_course_programs on public.course_programs; create policy public_read_course_programs on public.course_programs for select using(true);
grant select on public.academic_colleges,public.academic_departments,public.academic_programs,public.course_programs to anon,authenticated;
create unique index if not exists courses_code_unique_v316 on public.courses(code);
