begin;

-- Keep support centers in the dedicated home section instead of duplicating them in tools.
update public.tool_registry
set placement='hidden', sort_order=130, updated_at=now(), updated_by='security-ui-cleanup'
where key='support-centers';

-- Public views must obey the querying role and underlying RLS.
alter view public.resource_feedback_summary set (security_invoker=true);
alter view public.daily_usage_analytics set (security_invoker=true);
revoke select on public.daily_usage_analytics from anon, authenticated;

-- Close unused or internal public surfaces.
drop policy if exists public_manage_subscriptions on public.notification_subscriptions;
revoke all privileges on public.notification_subscriptions from anon, authenticated;

drop policy if exists public_insert_platform_feedback on public.platform_feedback;
revoke insert on public.platform_feedback from anon, authenticated;

revoke execute on function public.uon_sync_feature_to_registry() from public, anon, authenticated;
revoke execute on function public.uon_sync_registry_to_feature() from public, anon, authenticated;
revoke execute on function public.uon_tool_history_trigger() from public, anon, authenticated;
revoke execute on function public.v20_notify_group() from public, anon, authenticated;
revoke execute on function public.v20_notify_summary() from public, anon, authenticated;

alter function public.uon_ai_normalize_text(text) set search_path='';

-- Keep the legacy production suggestion form compatible while validating every row.
drop policy if exists public_insert_pending_feature_suggestions on public.feature_suggestions;
create policy public_insert_pending_feature_suggestions
on public.feature_suggestions
for insert
to anon, authenticated
with check (
  coalesce(status,'pending')='pending'
  and category in ('feature','improvement','bug','content')
  and char_length(trim(coalesce(title,''))) between 3 and 120
  and char_length(trim(coalesce(details,''))) between 10 and 2000
  and char_length(coalesce(contact,'')) <= 200
  and char_length(coalesce(college,'')) <= 120
  and char_length(coalesce(page_url,'')) <= 1000
);

-- Private audit table used to throttle every password-protected admin endpoint.
create table if not exists public.admin_login_attempts(
 id bigint generated by default as identity primary key,
 client_hash text not null,
 success boolean not null default false,
 attempted_at timestamptz not null default now()
);
alter table public.admin_login_attempts enable row level security;
revoke all on public.admin_login_attempts from anon, authenticated;
create index if not exists admin_login_attempts_client_time_idx
on public.admin_login_attempts(client_hash,attempted_at desc);

create or replace function public.uon_admin_authorized(p_password text)
returns boolean
language plpgsql
security definer
set search_path=''
as $$
declare
 v_headers jsonb:=coalesce(nullif(current_setting('request.headers',true),''),'{}')::jsonb;
 v_ip text;
 v_hash text;
 v_failures integer;
 v_ok boolean;
begin
 v_ip:=split_part(coalesce(v_headers->>'x-forwarded-for',v_headers->>'cf-connecting-ip',v_headers->>'x-real-ip','unknown'),',',1);
 v_hash:=encode(extensions.digest(convert_to(trim(v_ip),'UTF8'),'sha256'),'hex');
 select count(*) into v_failures
 from public.admin_login_attempts
 where client_hash=v_hash and success=false and attempted_at>now()-interval '15 minutes';
 if v_failures>=8 then return false; end if;
 select exists(
  select 1 from public.admin_passwords
  where coalesce(role,'editor') in ('owner','admin','editor','moderator')
    and (
      (password_sha256 is not null and password_sha256=encode(extensions.digest(convert_to(p_password,'UTF8'),'sha256'),'hex'))
      or (password_hash is not null and password_hash=extensions.crypt(p_password,password_hash))
    )
 ) into v_ok;
 if v_ok then
  delete from public.admin_login_attempts where client_hash=v_hash and success=false;
 else
  insert into public.admin_login_attempts(client_hash,success) values(v_hash,false);
 end if;
 delete from public.admin_login_attempts where attempted_at<now()-interval '7 days';
 return v_ok;
end;
$$;
revoke all on function public.uon_admin_authorized(text) from public, anon, authenticated;
grant execute on function public.uon_admin_authorized(text) to service_role;

create or replace function public.uon_admin_login(p_password text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare a record;
begin
 if not public.uon_admin_authorized(p_password) then
  return jsonb_build_object('ok',false);
 end if;
 select role,display_name into a from public.admin_passwords
 where (password_sha256 is not null and password_sha256=encode(extensions.digest(convert_to(p_password,'UTF8'),'sha256'),'hex'))
    or (password_hash is not null and password_hash=extensions.crypt(p_password,password_hash))
 limit 1;
 if a is null then return jsonb_build_object('ok',false); end if;
 return jsonb_build_object('ok',true,'role',a.role,'display_name',a.display_name);
end;
$$;
revoke all on function public.uon_admin_login(text) from public;
grant execute on function public.uon_admin_login(text) to anon, authenticated, service_role;

-- Rate-limited, deduplicated browser error endpoint.
create or replace function public.uon_report_client_error(
 p_message text,
 p_source text default 'browser',
 p_details jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
 v_message text:=left(trim(coalesce(p_message,'')),500);
 v_source text:=left(trim(coalesce(p_source,'browser')),80);
 v_headers jsonb:=coalesce(nullif(current_setting('request.headers',true),''),'{}')::jsonb;
 v_ip text;
 v_client_hash text;
 v_recent integer;
 v_duplicate integer;
begin
 if char_length(v_message)<3 then raise exception 'invalid error message'; end if;
 v_ip:=split_part(coalesce(v_headers->>'x-forwarded-for',v_headers->>'cf-connecting-ip',v_headers->>'x-real-ip','unknown'),',',1);
 v_client_hash:=encode(extensions.digest(convert_to(trim(v_ip),'UTF8'),'sha256'),'hex');
 select count(*) into v_recent from public.system_errors
 where created_at>now()-interval '5 minutes' and details->>'client_hash'=v_client_hash;
 if v_recent>=12 then return jsonb_build_object('ok',false,'rate_limited',true); end if;
 select count(*) into v_duplicate from public.system_errors
 where created_at>now()-interval '5 minutes' and source=v_source and message=v_message
   and details->>'client_hash'=v_client_hash;
 if v_duplicate=0 then
  insert into public.system_errors(source,message,details)
  values(v_source,v_message,coalesce(p_details,'{}'::jsonb)||jsonb_build_object('client_hash',v_client_hash));
 end if;
 return jsonb_build_object('ok',true,'deduplicated',v_duplicate>0);
end;
$$;
revoke all on function public.uon_report_client_error(text,text,jsonb) from public;
grant execute on function public.uon_report_client_error(text,text,jsonb) to anon, authenticated, service_role;

-- Validated content-report endpoint with per-session throttling.
create or replace function public.uon_submit_content_report(
 p_source_table text,
 p_source_id text,
 p_content_title text,
 p_source_url text,
 p_report_type text,
 p_details text,
 p_page_url text,
 p_session_id uuid
) returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare
 v_id uuid;
 v_last timestamptz;
 v_type text:=trim(coalesce(p_report_type,''));
 v_details text:=trim(coalesce(p_details,''));
 v_source_table text:=nullif(trim(coalesce(p_source_table,'')),'');
 v_source_url text:=nullif(trim(coalesce(p_source_url,'')),'');
 v_page_url text:=coalesce(nullif(trim(coalesce(p_page_url,'')),''),'/');
begin
 if p_session_id is null then raise exception 'تعذر التحقق من الجلسة'; end if;
 if v_type not in ('broken_link','wrong_content','duplicate','inappropriate','outdated','other') then raise exception 'نوع البلاغ غير صالح'; end if;
 if char_length(v_details)<5 or char_length(v_details)>1000 then raise exception 'تفاصيل البلاغ غير صالحة'; end if;
 if v_source_table is not null and v_source_table not in ('tool_registry','summaries','whatsapp_groups','student_projects','courses','university_programs','site_notifications') then raise exception 'مصدر البلاغ غير صالح'; end if;
 if char_length(coalesce(p_source_id,''))>120 or char_length(coalesce(p_content_title,''))>220 then raise exception 'بيانات البلاغ طويلة جدًا'; end if;
 if char_length(coalesce(v_source_url,''))>1000 or char_length(v_page_url)>1000 then raise exception 'الرابط طويل جدًا'; end if;
 if v_source_url is not null and v_source_url !~ '^(https?://|/|[A-Za-z0-9._-]+\.html)' then raise exception 'رابط المصدر غير صالح'; end if;
 if v_page_url !~ '^(https?://|/)' then raise exception 'رابط الصفحة غير صالح'; end if;
 select last_submitted_at into v_last from public.content_report_limits where session_id=p_session_id for update;
 if v_last is not null and now()-v_last<interval '15 seconds' then raise exception 'انتظر قليلًا قبل إرسال بلاغ آخر'; end if;
 insert into public.content_reports(reason,content_title,details,page_url,page_title,status,source_table,source_id,source_url,report_type,session_id)
 values(v_type,nullif(left(trim(coalesce(p_content_title,'')),220),''),v_details,v_page_url,nullif((coalesce(nullif(current_setting('request.headers',true),''),'{}')::jsonb)->>'referer',''),'pending',v_source_table,nullif(left(trim(coalesce(p_source_id,'')),120),''),v_source_url,v_type,p_session_id)
 returning id into v_id;
 insert into public.content_report_limits(session_id,last_submitted_at) values(p_session_id,now())
 on conflict(session_id) do update set last_submitted_at=excluded.last_submitted_at;
 return v_id;
end;
$$;
revoke all on function public.uon_submit_content_report(text,text,text,text,text,text,text,uuid) from public;
grant execute on function public.uon_submit_content_report(text,text,text,text,text,text,text,uuid) to anon, authenticated, service_role;

-- Replace unrestricted analytics inserts with a validated and rate-limited RPC.
create or replace function public.uon_track_event(
 p_event_type text,
 p_page_path text,
 p_session_id text,
 p_metadata jsonb default '{}'::jsonb,
 p_user_agent text default null
) returns boolean
language plpgsql
security definer
set search_path=''
as $$
declare
 v_event text:=left(trim(coalesce(p_event_type,'')),80);
 v_session text:=left(trim(coalesce(p_session_id,'')),80);
 v_recent integer;
begin
 if v_event !~ '^[a-z0-9_:-]{2,80}$' or v_session !~ '^[A-Za-z0-9_-]{8,80}$' then return false; end if;
 select count(*) into v_recent from public.usage_events
 where session_id=v_session and created_at>now()-interval '1 minute';
 if v_recent>=60 then return false; end if;
 insert into public.usage_events(event_type,page_path,session_id,metadata,user_agent)
 values(v_event,left(coalesce(p_page_path,''),240),v_session,coalesce(p_metadata,'{}'::jsonb),left(coalesce(p_user_agent,''),300));
 return true;
end;
$$;
revoke all on function public.uon_track_event(text,text,text,jsonb,text) from public;
grant execute on function public.uon_track_event(text,text,text,jsonb,text) to anon, authenticated, service_role;
drop policy if exists public_insert_usage_events on public.usage_events;
revoke insert on public.usage_events from anon, authenticated;

-- Safe performance clean-up: cover foreign keys and remove only confirmed duplicates.
create index if not exists anonymous_message_reports_message_id_idx on public.anonymous_message_reports(message_id);
create index if not exists release_checks_release_id_idx on public.release_checks(release_id);
drop index if exists public.idx_content_reports_status_created;
drop index if exists public.reports_status_created_v42;
drop index if exists public.idx_courses_active_code;
drop index if exists public.resource_feedback_one_per_device;
alter table public.settings drop constraint if exists settings_key_unique;

commit;
