-- UON Hub V64.1 — private per-user Google connections.
-- Personal Google data is never inserted into uon_ai_knowledge by this migration.

create table if not exists public.uon_google_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  google_subject text,
  google_email text,
  status text not null default 'active' check (status in ('active','revoked','error')),
  granted_scopes text[] not null default '{}',
  calendar_read_enabled boolean not null default false,
  drive_file_enabled boolean not null default false,
  token_secret_id uuid,
  refresh_secret_id uuid,
  token_expires_at timestamptz,
  connected_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);

create table if not exists public.uon_google_connection_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists uon_google_connection_audit_user_created_idx
  on public.uon_google_connection_audit(user_id, created_at desc);

alter table public.uon_google_connections enable row level security;
alter table public.uon_google_connection_audit enable row level security;

drop policy if exists "google connection owner read" on public.uon_google_connections;
create policy "google connection owner read"
  on public.uon_google_connections for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "google connection audit owner read" on public.uon_google_connection_audit;
create policy "google connection audit owner read"
  on public.uon_google_connection_audit for select
  to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.uon_google_connections from anon;
revoke all on public.uon_google_connection_audit from anon;
revoke insert, update, delete on public.uon_google_connections from authenticated;
revoke insert, update, delete on public.uon_google_connection_audit from authenticated;
grant select on public.uon_google_connections to authenticated;
grant select on public.uon_google_connection_audit to authenticated;
grant all on public.uon_google_connections to service_role;
grant all on public.uon_google_connection_audit to service_role;
grant usage, select on sequence public.uon_google_connection_audit_id_seq to service_role;

create or replace function public.uon_google_store_connection(
  p_user_id uuid,
  p_access_token text,
  p_refresh_token text,
  p_google_subject text,
  p_google_email text,
  p_scopes text[],
  p_expires_at timestamptz
) returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_access_id uuid;
  v_refresh_id uuid;
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
  v_scopes text[] := coalesce(p_scopes, '{}'::text[]);
begin
  if v_role <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  if p_user_id is null or coalesce(length(p_access_token),0) < 10 then
    raise exception 'invalid_google_connection';
  end if;

  select token_secret_id, refresh_secret_id
    into v_access_id, v_refresh_id
  from public.uon_google_connections
  where user_id = p_user_id;

  if v_access_id is null then
    select vault.create_secret(
      p_access_token,
      'uon-google-access-' || p_user_id::text,
      'UON Hub personal Google OAuth access token'
    ) into v_access_id;
  else
    perform vault.update_secret(v_access_id, p_access_token, null, null, null);
  end if;

  if coalesce(length(p_refresh_token),0) >= 10 then
    if v_refresh_id is null then
      select vault.create_secret(
        p_refresh_token,
        'uon-google-refresh-' || p_user_id::text,
        'UON Hub personal Google OAuth refresh token'
      ) into v_refresh_id;
    else
      perform vault.update_secret(v_refresh_id, p_refresh_token, null, null, null);
    end if;
  end if;

  insert into public.uon_google_connections (
    user_id, google_subject, google_email, status, granted_scopes,
    calendar_read_enabled, drive_file_enabled,
    token_secret_id, refresh_secret_id, token_expires_at,
    connected_at, revoked_at, last_error, updated_at
  ) values (
    p_user_id, nullif(p_google_subject,''), nullif(p_google_email,''), 'active', v_scopes,
    ('https://www.googleapis.com/auth/calendar.events.readonly' = any(v_scopes)
      or 'https://www.googleapis.com/auth/calendar.readonly' = any(v_scopes)),
    ('https://www.googleapis.com/auth/drive.file' = any(v_scopes)),
    v_access_id, v_refresh_id, p_expires_at,
    now(), null, null, now()
  )
  on conflict (user_id) do update set
    google_subject = excluded.google_subject,
    google_email = excluded.google_email,
    status = 'active',
    granted_scopes = excluded.granted_scopes,
    calendar_read_enabled = excluded.calendar_read_enabled,
    drive_file_enabled = excluded.drive_file_enabled,
    token_secret_id = excluded.token_secret_id,
    refresh_secret_id = coalesce(excluded.refresh_secret_id, public.uon_google_connections.refresh_secret_id),
    token_expires_at = excluded.token_expires_at,
    revoked_at = null,
    last_error = null,
    updated_at = now();

  insert into public.uon_google_connection_audit(user_id, action, detail)
  values (p_user_id, 'connected', jsonb_build_object('scopes', v_scopes));
end;
$$;

create or replace function public.uon_google_get_tokens(p_user_id uuid)
returns table(access_token text, refresh_token text, expires_at timestamptz, scopes text[])
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
begin
  if v_role <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  return query
  select a.decrypted_secret,
         r.decrypted_secret,
         c.token_expires_at,
         c.granted_scopes
  from public.uon_google_connections c
  left join vault.decrypted_secrets a on a.id = c.token_secret_id
  left join vault.decrypted_secrets r on r.id = c.refresh_secret_id
  where c.user_id = p_user_id and c.status = 'active';
end;
$$;

create or replace function public.uon_google_update_access_token(
  p_user_id uuid,
  p_access_token text,
  p_expires_at timestamptz
) returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
  v_secret_id uuid;
begin
  if v_role <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  select token_secret_id into v_secret_id
  from public.uon_google_connections where user_id = p_user_id and status = 'active';
  if v_secret_id is null or coalesce(length(p_access_token),0) < 10 then
    raise exception 'google_connection_missing';
  end if;
  perform vault.update_secret(v_secret_id, p_access_token, null, null, null);
  update public.uon_google_connections
    set token_expires_at = p_expires_at, last_error = null, updated_at = now()
    where user_id = p_user_id;
end;
$$;

create or replace function public.uon_google_mark_used(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
begin
  if v_role <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  update public.uon_google_connections set last_used_at = now(), updated_at = now() where user_id = p_user_id;
end;
$$;

create or replace function public.uon_google_disconnect(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
  v_access_id uuid;
  v_refresh_id uuid;
begin
  if v_role <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  select token_secret_id, refresh_secret_id into v_access_id, v_refresh_id
  from public.uon_google_connections where user_id = p_user_id;
  if v_access_id is not null then delete from vault.secrets where id = v_access_id; end if;
  if v_refresh_id is not null then delete from vault.secrets where id = v_refresh_id; end if;
  update public.uon_google_connections set
    status = 'revoked', granted_scopes = '{}'::text[],
    calendar_read_enabled = false, drive_file_enabled = false,
    token_secret_id = null, refresh_secret_id = null, token_expires_at = null,
    revoked_at = now(), updated_at = now()
  where user_id = p_user_id;
  insert into public.uon_google_connection_audit(user_id, action)
  values (p_user_id, 'disconnected');
end;
$$;

revoke all on function public.uon_google_store_connection(uuid,text,text,text,text,text[],timestamptz) from public, anon, authenticated;
revoke all on function public.uon_google_get_tokens(uuid) from public, anon, authenticated;
revoke all on function public.uon_google_update_access_token(uuid,text,timestamptz) from public, anon, authenticated;
revoke all on function public.uon_google_mark_used(uuid) from public, anon, authenticated;
revoke all on function public.uon_google_disconnect(uuid) from public, anon, authenticated;
grant execute on function public.uon_google_store_connection(uuid,text,text,text,text,text[],timestamptz) to service_role;
grant execute on function public.uon_google_get_tokens(uuid) to service_role;
grant execute on function public.uon_google_update_access_token(uuid,text,timestamptz) to service_role;
grant execute on function public.uon_google_mark_used(uuid) to service_role;
grant execute on function public.uon_google_disconnect(uuid) to service_role;
