create table if not exists public.anonymous_action_limits (
  id bigint generated by default as identity primary key,
  client_hash text not null,
  action text not null,
  target_key text,
  success boolean,
  created_at timestamptz not null default now(),
  constraint anonymous_action_limits_action_check check (action ~ '^[a-z0-9_:-]{2,60}$')
);

alter table public.anonymous_action_limits enable row level security;
revoke all on table public.anonymous_action_limits from anon, authenticated;
grant all on table public.anonymous_action_limits to service_role;

alter table public.anonymous_profiles add column if not exists creator_hash text;
alter table public.anonymous_messages add column if not exists sender_hash text;
alter table public.anonymous_message_reports add column if not exists client_hash text;

create index if not exists anonymous_action_limits_client_action_created_idx
  on public.anonymous_action_limits(client_hash,action,created_at desc);
create index if not exists anonymous_action_limits_target_created_idx
  on public.anonymous_action_limits(client_hash,action,target_key,created_at desc);
create index if not exists anonymous_action_limits_created_idx
  on public.anonymous_action_limits(created_at);
create index if not exists anonymous_profiles_creator_created_idx
  on public.anonymous_profiles(creator_hash,created_at desc) where creator_hash is not null;
create index if not exists anonymous_messages_sender_created_idx
  on public.anonymous_messages(sender_hash,created_at desc) where sender_hash is not null;
create unique index if not exists anonymous_message_reports_message_client_uidx
  on public.anonymous_message_reports(message_id,client_hash) where client_hash is not null;

create or replace function public.uon_anonymous_client_hash()
returns text
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_headers jsonb:=coalesce(nullif(current_setting('request.headers',true),''),'{}')::jsonb;
  v_ip text;
  v_fallback text;
begin
  v_ip:=nullif(trim(split_part(coalesce(
    v_headers->>'x-forwarded-for',
    v_headers->>'cf-connecting-ip',
    v_headers->>'x-real-ip',
    ''
  ),',',1)), '');
  v_fallback:=concat('unknown|',coalesce(v_headers->>'user-agent',''), '|', coalesce(v_headers->>'accept-language',''));
  return encode(extensions.digest(convert_to(coalesce(v_ip,v_fallback),'UTF8'),'sha256'),'hex');
end;
$$;

revoke all on function public.uon_anonymous_client_hash() from public, anon, authenticated;
grant execute on function public.uon_anonymous_client_hash() to service_role;

create or replace function public.create_anonymous_profile(p_handle text,p_display_name text,p_secret text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_handle text:=lower(trim(coalesce(p_handle,'')));
  v_name text:=trim(coalesce(p_display_name,''));
  v_client_hash text:=public.uon_anonymous_client_hash();
  v_recent integer;
  v_id uuid;
begin
  if v_handle !~ '^[a-z0-9_]{3,24}$' then raise exception 'اسم الرابط يجب أن يكون 3-24 حرفًا إنجليزيًا أو رقمًا'; end if;
  if char_length(v_name) not between 2 and 40 then raise exception 'الاسم غير صالح'; end if;
  if char_length(coalesce(p_secret,''))<24 then raise exception 'مفتاح الحماية غير صالح'; end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_client_hash,0));
  select count(*) into v_recent
  from public.anonymous_action_limits
  where client_hash=v_client_hash and action='create_profile' and created_at>now()-interval '24 hours';
  if v_recent>=5 then
    return jsonb_build_object('ok',false,'error','تم الوصول للحد المؤقت لإنشاء الحسابات','rate_limited',true);
  end if;

  insert into public.anonymous_profiles(handle,display_name,secret_hash,creator_hash)
  values(v_handle,v_name,encode(extensions.digest(convert_to(p_secret,'UTF8'),'sha256'),'hex'),v_client_hash)
  on conflict (handle) do nothing
  returning id into v_id;

  insert into public.anonymous_action_limits(client_hash,action,target_key,success)
  values(v_client_hash,'create_profile',coalesce(v_id::text,v_handle),v_id is not null);
  delete from public.anonymous_action_limits where created_at<now()-interval '7 days';

  if v_id is null then
    return jsonb_build_object('ok',false,'error','اسم الرابط مستخدم');
  end if;
  return jsonb_build_object('ok',true,'id',v_id,'handle',v_handle,'display_name',v_name);
end;
$$;

create or replace function public.send_anonymous_message(p_handle text,p_body text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_profile public.anonymous_profiles%rowtype;
  v_id uuid;
  v_body text:=trim(coalesce(p_body,''));
  v_client_hash text:=public.uon_anonymous_client_hash();
  v_recent integer;
  v_target_recent integer;
begin
  select * into v_profile from public.anonymous_profiles
  where handle=lower(trim(coalesce(p_handle,''))) and is_active=true;
  if v_profile.id is null then raise exception 'الحساب غير موجود'; end if;
  if not v_profile.inbox_open then raise exception 'صندوق الرسائل مغلق حاليًا'; end if;
  if char_length(v_body) not between 2 and 500 then raise exception 'الرسالة يجب أن تكون بين 2 و500 حرف'; end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_client_hash,0));
  select count(*) into v_recent
  from public.anonymous_action_limits
  where client_hash=v_client_hash and action='send_message' and created_at>now()-interval '5 minutes';
  if v_recent>=15 then raise exception 'تم إرسال رسائل كثيرة، حاول بعد قليل'; end if;

  select count(*) into v_target_recent
  from public.anonymous_action_limits
  where client_hash=v_client_hash and action='send_message' and target_key=v_profile.id::text and created_at>now()-interval '10 minutes';
  if v_target_recent>=8 then raise exception 'تم إرسال رسائل كثيرة لهذا الحساب، حاول لاحقًا'; end if;

  insert into public.anonymous_messages(recipient_id,body,sender_hash)
  values(v_profile.id,v_body,v_client_hash)
  returning id into v_id;
  insert into public.anonymous_action_limits(client_hash,action,target_key,success)
  values(v_client_hash,'send_message',v_profile.id::text,true);
  delete from public.anonymous_action_limits where created_at<now()-interval '7 days';

  return jsonb_build_object('ok',true,'id',v_id,'sent',true);
end;
$$;

create or replace function public.report_anonymous_message(p_message_id uuid,p_reason text default 'محتوى غير مناسب',p_fingerprint text default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_client_hash text:=public.uon_anonymous_client_hash();
  v_recent integer;
  v_report_id uuid;
  v_reports_count integer;
  v_status text;
begin
  if p_message_id is null then raise exception 'الرسالة غير صالحة'; end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_client_hash,0));
  select count(*) into v_recent
  from public.anonymous_action_limits
  where client_hash=v_client_hash and action='report_message' and created_at>now()-interval '1 hour';
  if v_recent>=20 then raise exception 'تم إرسال بلاغات كثيرة، حاول لاحقًا'; end if;

  if not exists(select 1 from public.anonymous_messages where id=p_message_id and status='published') then
    raise exception 'الرسالة غير متاحة للبلاغ';
  end if;

  insert into public.anonymous_message_reports(message_id,reason,fingerprint,client_hash)
  values(
    p_message_id,
    left(coalesce(nullif(trim(p_reason),''),'محتوى غير مناسب'),120),
    left(nullif(trim(coalesce(p_fingerprint,'')),''),120),
    v_client_hash
  )
  on conflict (message_id,client_hash) where client_hash is not null do nothing
  returning id into v_report_id;

  insert into public.anonymous_action_limits(client_hash,action,target_key,success)
  values(v_client_hash,'report_message',p_message_id::text,v_report_id is not null);
  delete from public.anonymous_action_limits where created_at<now()-interval '7 days';

  if v_report_id is null then
    select reports_count,status into v_reports_count,v_status from public.anonymous_messages where id=p_message_id;
    return jsonb_build_object('ok',true,'duplicate',true,'reports_count',coalesce(v_reports_count,0),'status',v_status);
  end if;

  update public.anonymous_messages
  set reports_count=reports_count+1,
      status=case when reports_count+1>=3 then 'hidden' else status end
  where id=p_message_id and status='published'
  returning reports_count,status into v_reports_count,v_status;

  return jsonb_build_object('ok',true,'duplicate',false,'reports_count',v_reports_count,'status',v_status);
end;
$$;

create or replace function public.get_anonymous_inbox(p_handle text,p_secret text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_profile public.anonymous_profiles%rowtype;
  v_client_hash text:=public.uon_anonymous_client_hash();
  v_target text:=encode(extensions.digest(convert_to(lower(trim(coalesce(p_handle,''))),'UTF8'),'sha256'),'hex');
  v_failures integer;
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_client_hash,0));
  select count(*) into v_failures
  from public.anonymous_action_limits
  where client_hash=v_client_hash and action='inbox_auth_failed' and created_at>now()-interval '15 minutes';
  if v_failures>=12 then
    return jsonb_build_object('ok',false,'error','محاولات كثيرة، حاول بعد قليل','rate_limited',true);
  end if;

  select * into v_profile
  from public.anonymous_profiles
  where handle=lower(trim(coalesce(p_handle,'')))
    and secret_hash=encode(extensions.digest(convert_to(coalesce(p_secret,''),'UTF8'),'sha256'),'hex');

  if v_profile.id is null then
    insert into public.anonymous_action_limits(client_hash,action,target_key,success)
    values(v_client_hash,'inbox_auth_failed',v_target,false);
    delete from public.anonymous_action_limits where created_at<now()-interval '7 days';
    return jsonb_build_object('ok',false,'error','تعذر فتح الصندوق');
  end if;

  delete from public.anonymous_action_limits
  where client_hash=v_client_hash and action='inbox_auth_failed' and target_key=v_target;
  update public.anonymous_messages set is_read=true where recipient_id=v_profile.id and is_read=false;

  return jsonb_build_object(
    'ok',true,
    'profile',jsonb_build_object('handle',v_profile.handle,'display_name',v_profile.display_name,'bio',v_profile.bio,'inbox_open',v_profile.inbox_open),
    'messages',coalesce((
      select jsonb_agg(jsonb_build_object('id',m.id,'body',m.body,'reply',m.reply,'status',m.status,'is_read',m.is_read,'created_at',m.created_at) order by m.created_at desc)
      from public.anonymous_messages m where m.recipient_id=v_profile.id and m.status<>'deleted'
    ),'[]'::jsonb)
  );
end;
$$;

create or replace function public.manage_anonymous_message(p_handle text,p_secret text,p_message_id uuid,p_action text,p_reply text default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_profile_id uuid;
  v_status text;
  v_client_hash text:=public.uon_anonymous_client_hash();
  v_target text:=encode(extensions.digest(convert_to(lower(trim(coalesce(p_handle,''))),'UTF8'),'sha256'),'hex');
  v_failures integer;
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_client_hash,0));
  select count(*) into v_failures
  from public.anonymous_action_limits
  where client_hash=v_client_hash and action='manage_auth_failed' and created_at>now()-interval '15 minutes';
  if v_failures>=12 then
    return jsonb_build_object('ok',false,'error','محاولات كثيرة، حاول بعد قليل','rate_limited',true);
  end if;

  select id into v_profile_id from public.anonymous_profiles
  where handle=lower(trim(coalesce(p_handle,'')))
    and secret_hash=encode(extensions.digest(convert_to(coalesce(p_secret,''),'UTF8'),'sha256'),'hex');
  if v_profile_id is null then
    insert into public.anonymous_action_limits(client_hash,action,target_key,success)
    values(v_client_hash,'manage_auth_failed',v_target,false);
    delete from public.anonymous_action_limits where created_at<now()-interval '7 days';
    return jsonb_build_object('ok',false,'error','غير مصرح');
  end if;

  delete from public.anonymous_action_limits where client_hash=v_client_hash and action='manage_auth_failed' and target_key=v_target;

  if p_action='publish' then
    update public.anonymous_messages set status='published',reply=nullif(trim(p_reply),''),replied_at=case when nullif(trim(p_reply),'') is null then replied_at else now() end,published_at=now()
    where id=p_message_id and recipient_id=v_profile_id returning status into v_status;
  elsif p_action='hide' then
    update public.anonymous_messages set status='hidden' where id=p_message_id and recipient_id=v_profile_id returning status into v_status;
  elsif p_action='delete' then
    update public.anonymous_messages set status='deleted' where id=p_message_id and recipient_id=v_profile_id returning status into v_status;
  elsif p_action='inbox' then
    update public.anonymous_messages set status='inbox' where id=p_message_id and recipient_id=v_profile_id returning status into v_status;
  else
    raise exception 'إجراء غير صالح';
  end if;
  if v_status is null then raise exception 'الرسالة غير موجودة'; end if;
  return jsonb_build_object('ok',true,'status',v_status);
end;
$$;

create or replace function public.update_anonymous_profile(p_handle text,p_secret text,p_display_name text,p_bio text,p_inbox_open boolean)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_row public.anonymous_profiles%rowtype;
  v_client_hash text:=public.uon_anonymous_client_hash();
  v_target text:=encode(extensions.digest(convert_to(lower(trim(coalesce(p_handle,''))),'UTF8'),'sha256'),'hex');
  v_failures integer;
begin
  if char_length(trim(coalesce(p_display_name,''))) not between 2 and 40 then raise exception 'الاسم غير صالح'; end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_client_hash,0));
  select count(*) into v_failures
  from public.anonymous_action_limits
  where client_hash=v_client_hash and action='profile_auth_failed' and created_at>now()-interval '15 minutes';
  if v_failures>=12 then
    return jsonb_build_object('ok',false,'error','محاولات كثيرة، حاول بعد قليل','rate_limited',true);
  end if;

  update public.anonymous_profiles
  set display_name=trim(p_display_name),bio=left(trim(coalesce(p_bio,'')),160),inbox_open=coalesce(p_inbox_open,true),updated_at=now()
  where handle=lower(trim(coalesce(p_handle,'')))
    and secret_hash=encode(extensions.digest(convert_to(coalesce(p_secret,''),'UTF8'),'sha256'),'hex')
  returning * into v_row;

  if v_row.id is null then
    insert into public.anonymous_action_limits(client_hash,action,target_key,success)
    values(v_client_hash,'profile_auth_failed',v_target,false);
    delete from public.anonymous_action_limits where created_at<now()-interval '7 days';
    return jsonb_build_object('ok',false,'error','غير مصرح');
  end if;

  delete from public.anonymous_action_limits where client_hash=v_client_hash and action='profile_auth_failed' and target_key=v_target;
  return jsonb_build_object('ok',true,'handle',v_row.handle,'display_name',v_row.display_name,'bio',v_row.bio,'inbox_open',v_row.inbox_open);
end;
$$;

create or replace function public.get_anonymous_profile(p_handle text)
returns jsonb
language sql
stable
security definer
set search_path=''
as $$
 select case when p.id is null then null else jsonb_build_object(
  'handle',p.handle,'display_name',p.display_name,'bio',p.bio,'inbox_open',p.inbox_open,
  'messages',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'body',m.body,'reply',m.reply,'created_at',m.created_at,'published_at',m.published_at) order by m.published_at desc)
    from public.anonymous_messages m where m.recipient_id=p.id and m.status='published'),'[]'::jsonb)
 ) end
 from public.anonymous_profiles p where p.handle=lower(trim(coalesce(p_handle,''))) and p.is_active=true
$$;

grant execute on function public.create_anonymous_profile(text,text,text) to anon, authenticated;
grant execute on function public.send_anonymous_message(text,text) to anon, authenticated;
grant execute on function public.report_anonymous_message(uuid,text,text) to anon, authenticated;
grant execute on function public.get_anonymous_inbox(text,text) to anon, authenticated;
grant execute on function public.manage_anonymous_message(text,text,uuid,text,text) to anon, authenticated;
grant execute on function public.update_anonymous_profile(text,text,text,text,boolean) to anon, authenticated;
grant execute on function public.get_anonymous_profile(text) to anon, authenticated;