create table if not exists public.uon_ai_knowledge (
 id uuid primary key default gen_random_uuid(),
 title text not null,
 content text not null,
 category text not null default 'general',
 source_url text,
 source_title text,
 official boolean not null default false,
 active boolean not null default true,
 tags text[] not null default '{}',
 updated_at timestamptz not null default now(),
 created_at timestamptz not null default now()
);

create index if not exists uon_ai_knowledge_active_idx on public.uon_ai_knowledge(active,category);
create index if not exists uon_ai_knowledge_tags_idx on public.uon_ai_knowledge using gin(tags);

alter table public.uon_ai_knowledge enable row level security;
drop policy if exists "public read active ai knowledge" on public.uon_ai_knowledge;
create policy "public read active ai knowledge" on public.uon_ai_knowledge for select using (active=true);

create table if not exists public.uon_ai_questions (
 id bigint generated by default as identity primary key,
 question text not null,
 normalized_question text,
 answer_preview text,
 sources_count integer not null default 0,
 confidence numeric,
 success boolean not null default true,
 error_message text,
 created_at timestamptz not null default now()
);

alter table public.uon_ai_questions enable row level security;
revoke all on public.uon_ai_questions from anon, authenticated;
grant select on public.uon_ai_knowledge to anon, authenticated;
