create table if not exists public.public_rpc_rate_limits (
  id bigint generated by default as identity primary key,
  client_hash text not null,
  action text not null,
  target_key text,
  created_at timestamptz not null default now(),
  constraint public_rpc_rate_limits_action_check check (action ~ '^[a-z0-9_:-]{2,80}$')
);

alter table public.public_rpc_rate_limits enable row level security;
revoke all on table public.public_rpc_rate_limits from anon, authenticated;
grant all on table public.public_rpc_rate_limits to service_role;

create index if not exists public_rpc_rate_limits_lookup_idx
  on public.public_rpc_rate_limits(client_hash,action,target_key,created_at desc);
create index if not exists public_rpc_rate_limits_created_idx
  on public.public_rpc_rate_limits(created_at);

create or replace function public.uon_request_client_hash()
returns text
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_headers jsonb:=coalesce(nullif(current_setting('request.headers',true),''),'{}')::jsonb;
  v_ip text;
  v_agent text;
  v_lang text;
  v_raw text;
begin
  v_ip:=nullif(trim(split_part(coalesce(
    v_headers->>'x-forwarded-for',
    v_headers->>'cf-connecting-ip',
    v_headers->>'x-real-ip',
    ''
  ),',',1)), '');
  v_agent:=left(coalesce(v_headers->>'user-agent',''),240);
  v_lang:=left(coalesce(v_headers->>'accept-language',''),80);
  v_raw:=concat(coalesce(v_ip,'unknown'),'|',v_agent,'|',v_lang);
  return encode(extensions.digest(convert_to(v_raw,'UTF8'),'sha256'),'hex');
end;
$$;

revoke all on function public.uon_request_client_hash() from public, anon, authenticated;
grant execute on function public.uon_request_client_hash() to service_role;

create or replace function public.uon_public_rate_allow(
  p_action text,
  p_target_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
volatile
security definer
set search_path=''
as $$
declare
  v_action text:=lower(trim(coalesce(p_action,'')));
  v_target text:=nullif(left(trim(coalesce(p_target_key,'')),200),'');
  v_limit integer:=greatest(1,least(coalesce(p_limit,1),1000));
  v_window integer:=greatest(1,least(coalesce(p_window_seconds,60),604800));
  v_hash text:=public.uon_request_client_hash();
  v_count integer;
begin
  if v_action !~ '^[a-z0-9_:-]{2,80}$' then raise exception 'invalid_rate_action'; end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_hash||'|'||v_action||'|'||coalesce(v_target,''),0)
  );

  select count(*) into v_count
  from public.public_rpc_rate_limits
  where client_hash=v_hash
    and action=v_action
    and (v_target is null or target_key=v_target)
    and created_at>now()-make_interval(secs=>v_window);

  if v_count>=v_limit then return false; end if;

  insert into public.public_rpc_rate_limits(client_hash,action,target_key)
  values(v_hash,v_action,v_target);

  delete from public.public_rpc_rate_limits
  where created_at<now()-interval '7 days';

  return true;
end;
$$;

revoke all on function public.uon_public_rate_allow(text,text,integer,integer) from public, anon, authenticated;
grant execute on function public.uon_public_rate_allow(text,text,integer,integer) to service_role;

create or replace function public.uon_create_schedule_share(p_title text,p_payload jsonb,p_days integer default 90)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare v_id uuid; v_rows integer; v_title text:=trim(coalesce(p_title,''));
begin
 if jsonb_typeof(p_payload)<>'object' then raise exception 'invalid_payload'; end if;
 if jsonb_typeof(coalesce(p_payload->'rows','[]'::jsonb))<>'array' then raise exception 'invalid_schedule_rows'; end if;
 v_rows=jsonb_array_length(coalesce(p_payload->'rows','[]'::jsonb));
 if v_rows<1 or v_rows>100 then raise exception 'invalid_schedule_size'; end if;
 if octet_length(p_payload::text)>100000 then raise exception 'payload_too_large'; end if;
 if char_length(v_title)>120 then raise exception 'title_too_long'; end if;
 if not public.uon_public_rate_allow('schedule_share_create',null,20,3600) then raise exception 'rate_limited'; end if;
 insert into public.schedule_shares(title,payload,expires_at)
 values(left(coalesce(nullif(v_title,''),'الجدول الدراسي'),120),p_payload,now()+make_interval(days=>greatest(1,least(coalesce(p_days,90),365)))) returning id into v_id;
 return v_id;
end;
$$;

create or replace function public.uon_get_schedule_share(p_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_result jsonb; v_count_view boolean;
begin
 if p_id is null then return null; end if;
 select jsonb_build_object('id',id,'title',title,'payload',payload,'created_at',created_at,'expires_at',expires_at,'views',views)
 into v_result from public.schedule_shares where id=p_id and expires_at>now();
 if v_result is null then return null; end if;
 v_count_view:=public.uon_public_rate_allow('schedule_share_view',p_id::text,1,900);
 if v_count_view then
  update public.schedule_shares set views=views+1 where id=p_id and expires_at>now()
  returning jsonb_build_object('id',id,'title',title,'payload',payload,'created_at',created_at,'expires_at',expires_at,'views',views) into v_result;
 end if;
 return v_result;
end;
$$;

create or replace function public.increment_exam_question_vote(p_id integer,p_session_id uuid)
returns integer
language plpgsql
security definer
set search_path=''
as $$
declare v_votes integer; v_inserted integer;
begin
 if p_session_id is null then raise exception 'Session required'; end if;
 if not exists(select 1 from public.exam_questions where id=p_id and approved=true) then raise exception 'Question not found'; end if;
 if exists(select 1 from public.exam_question_votes where question_id=p_id and session_id=p_session_id) then
  select coalesce(votes,0) into v_votes from public.exam_questions where id=p_id and approved=true;
  return coalesce(v_votes,0);
 end if;
 if not public.uon_public_rate_allow('exam_question_vote',null,20,3600) then raise exception 'rate_limited'; end if;
 insert into public.exam_question_votes(question_id,session_id) values(p_id,p_session_id) on conflict do nothing;
 get diagnostics v_inserted=row_count;
 if v_inserted=1 then
  update public.exam_questions set votes=coalesce(votes,0)+1 where id=p_id and approved=true returning votes into v_votes;
 else
  select coalesce(votes,0) into v_votes from public.exam_questions where id=p_id and approved=true;
 end if;
 return coalesce(v_votes,0);
end;
$$;

create or replace function public.uon_toggle_confession_reaction(p_confession_id uuid,p_session_id uuid,p_reaction text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare current_reaction text; result jsonb;
begin
 if p_session_id is null then raise exception 'session_required'; end if;
 if p_reaction not in ('heart','laugh','sad','wow','fire') then raise exception 'invalid reaction'; end if;
 if not exists(select 1 from public.confessions where id=p_confession_id and status='approved') then raise exception 'confession unavailable'; end if;
 select reaction into current_reaction from public.confession_reactions where confession_id=p_confession_id and session_id=p_session_id;
 if not public.uon_public_rate_allow('confession_reaction_total',null,60,3600) then raise exception 'rate_limited'; end if;
 if not public.uon_public_rate_allow('confession_reaction_target',p_confession_id::text,8,3600) then raise exception 'rate_limited'; end if;
 if current_reaction=p_reaction then
  delete from public.confession_reactions where confession_id=p_confession_id and session_id=p_session_id;
 elsif current_reaction is null then
  insert into public.confession_reactions(confession_id,session_id,reaction) values(p_confession_id,p_session_id,p_reaction);
 else
  update public.confession_reactions set reaction=p_reaction,created_at=now() where confession_id=p_confession_id and session_id=p_session_id;
 end if;
 select jsonb_build_object(
  'heart',count(*) filter(where reaction='heart'),
  'laugh',count(*) filter(where reaction='laugh'),
  'sad',count(*) filter(where reaction='sad'),
  'wow',count(*) filter(where reaction='wow'),
  'fire',count(*) filter(where reaction='fire'),
  'mine',(select reaction from public.confession_reactions where confession_id=p_confession_id and session_id=p_session_id)
 ) into result from public.confession_reactions where confession_id=p_confession_id;
 return result;
end;
$$;

create or replace function public.uon_submit_resource_rating(p_resource_table text,p_resource_id text,p_session_id uuid,p_rating smallint,p_recommended boolean default null,p_comment text default null,p_reviewer_name text default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare r public.resource_feedback; avg_rating numeric; total_count int; v_existing boolean; v_id uuid;
begin
 if p_session_id is null then raise exception 'Session required'; end if;
 if p_resource_table not in ('summaries') then raise exception 'Unsupported resource'; end if;
 if p_resource_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then raise exception 'Invalid resource'; end if;
 v_id:=p_resource_id::uuid;
 if not exists(select 1 from public.summaries where id=v_id and approved is true) then raise exception 'Resource unavailable'; end if;
 if p_rating not between 1 and 5 then raise exception 'Rating must be 1-5'; end if;
 if char_length(coalesce(p_comment,''))>600 then raise exception 'Comment too long'; end if;
 if char_length(coalesce(p_reviewer_name,''))>80 then raise exception 'Reviewer name too long'; end if;
 select exists(select 1 from public.resource_feedback where resource_table=p_resource_table and resource_id=p_resource_id and session_id=p_session_id) into v_existing;
 if not v_existing then
  if not public.uon_public_rate_allow('resource_rating_total',null,30,3600) then raise exception 'rate_limited'; end if;
  if not public.uon_public_rate_allow('resource_rating_target',p_resource_id,5,86400) then raise exception 'rate_limited'; end if;
 end if;
 insert into public.resource_feedback(resource_table,resource_id,session_id,rating,recommended,useful,comment,reviewer_name,status,updated_at)
 values(p_resource_table,p_resource_id,p_session_id,p_rating,p_recommended,p_recommended,nullif(btrim(p_comment),''),nullif(btrim(p_reviewer_name),''),'approved',now())
 on conflict(resource_table,resource_id,session_id) do update set
  rating=excluded.rating,recommended=excluded.recommended,useful=excluded.useful,
  comment=excluded.comment,reviewer_name=excluded.reviewer_name,status='approved',updated_at=now()
 returning * into r;
 select round(avg(rating)::numeric,1),count(*) into avg_rating,total_count
 from public.resource_feedback where resource_table=p_resource_table and resource_id=p_resource_id and status='approved' and rating is not null;
 update public.summaries set rating=coalesce(avg_rating,0),updated_at=now() where id=v_id;
 return jsonb_build_object('id',r.id,'average',coalesce(avg_rating,0),'count',total_count);
end;
$$;

create or replace function public.uon_track_summary_open(p_summary_id uuid,p_kind text default 'view')
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
 if p_kind not in ('view','download') then raise exception 'Invalid kind'; end if;
 if not exists(select 1 from public.summaries where id=p_summary_id and approved is true) then return; end if;
 if not public.uon_public_rate_allow('summary_'||p_kind,p_summary_id::text,4,3600) then return; end if;
 if p_kind='download' then
  update public.summaries set downloads=coalesce(downloads,0)+1 where id=p_summary_id and approved is true;
 else
  update public.summaries set views=coalesce(views,0)+1 where id=p_summary_id and approved is true;
 end if;
end;
$$;

create or replace function public.uon_track_event(p_event_type text,p_page_path text,p_session_id text,p_metadata jsonb default '{}'::jsonb,p_user_agent text default null)
returns boolean
language plpgsql
security definer
set search_path=''
as $$
declare v_event text:=left(trim(coalesce(p_event_type,'')),80); v_session text:=left(trim(coalesce(p_session_id,'')),80); v_recent integer;
begin
 if v_event !~ '^[a-z0-9_:-]{2,80}$' or v_session !~ '^[A-Za-z0-9_-]{8,80}$' then return false; end if;
 if octet_length(coalesce(p_metadata,'{}'::jsonb)::text)>8192 then return false; end if;
 if not public.uon_public_rate_allow('usage_event',null,240,300) then return false; end if;
 select count(*) into v_recent from public.usage_events where session_id=v_session and created_at>now()-interval '1 minute';
 if v_recent>=60 then return false; end if;
 insert into public.usage_events(event_type,page_path,session_id,metadata,user_agent)
 values(v_event,left(coalesce(p_page_path,''),240),v_session,coalesce(p_metadata,'{}'::jsonb),left(coalesce(p_user_agent,''),300));
 return true;
end;
$$;

create or replace function public.uon_submit_confession_v2(p_text text,p_college text default null,p_program text default null,p_session_id uuid default null)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare v_id uuid; v_text text:=regexp_replace(trim(coalesce(p_text,'')), E'[\\u0000-\\u0008\\u000B\\u000C\\u000E-\\u001F]', '', 'g'); v_last timestamptz; v_college text:=nullif(trim(coalesce(p_college,'')),''); v_program text:=nullif(trim(coalesce(p_program,'')),'');
begin
 if char_length(v_text)<5 then raise exception 'الاعتراف قصير جدًا'; end if;
 if char_length(v_text)>1000 then raise exception 'الاعتراف أطول من الحد المسموح'; end if;
 if p_session_id is null then raise exception 'تعذر التحقق من الجلسة'; end if;
 if char_length(coalesce(v_college,''))>120 or char_length(coalesce(v_program,''))>160 then raise exception 'بيانات التصنيف طويلة جدًا'; end if;
 if not public.uon_public_rate_allow('confession_submit',null,12,3600) then raise exception 'انتظر قليلًا قبل نشر اعتراف جديد'; end if;
 select last_submitted_at into v_last from public.confession_submission_limits where session_id=p_session_id for update;
 if v_last is not null and now()-v_last<interval '10 seconds' then raise exception 'انتظر ثواني قبل نشر اعتراف جديد'; end if;
 insert into public.confessions(text,content,category,status,is_anon,college,program,published_at,comments_enabled)
 values(v_text,v_text,coalesce(v_college,'عام'),'approved',true,v_college,v_program,now(),true) returning id into v_id;
 insert into public.confession_submission_limits(session_id,last_submitted_at) values(p_session_id,now())
 on conflict(session_id) do update set last_submitted_at=excluded.last_submitted_at;
 return v_id;
end;
$$;

revoke execute on function public.uon_request_client_hash() from public, anon, authenticated;
revoke execute on function public.uon_public_rate_allow(text,text,integer,integer) from public, anon, authenticated;

revoke execute on function public.uon_create_schedule_share(text,jsonb,integer) from public, authenticated;
revoke execute on function public.uon_get_schedule_share(uuid) from public, authenticated;
revoke execute on function public.increment_exam_question_vote(integer,uuid) from public, authenticated;
revoke execute on function public.uon_toggle_confession_reaction(uuid,uuid,text) from public, authenticated;
revoke execute on function public.uon_submit_resource_rating(text,text,uuid,smallint,boolean,text,text) from public, authenticated;
revoke execute on function public.uon_track_summary_open(uuid,text) from public, authenticated;
revoke execute on function public.uon_track_event(text,text,text,jsonb,text) from public, authenticated;
revoke execute on function public.uon_submit_confession_v2(text,text,text,uuid) from public, authenticated;

grant execute on function public.uon_create_schedule_share(text,jsonb,integer) to anon;
grant execute on function public.uon_get_schedule_share(uuid) to anon;
grant execute on function public.increment_exam_question_vote(integer,uuid) to anon;
grant execute on function public.uon_toggle_confession_reaction(uuid,uuid,text) to anon;
grant execute on function public.uon_submit_resource_rating(text,text,uuid,smallint,boolean,text,text) to anon;
grant execute on function public.uon_track_summary_open(uuid,text) to anon;
grant execute on function public.uon_track_event(text,text,text,jsonb,text) to anon;
grant execute on function public.uon_submit_confession_v2(text,text,text,uuid) to anon;
